### ISSUE TITLE
NotFoundError: Node.insertBefore: Child to insert before is not a child of this node

### ISSUE THREAD

**Issue by 0bon** [solidjs/solid#1003]
### Describe the bug

I am using `sortablejs` to allow the user to reorder a `<ul>` list. I am using `@solid-primitives/storage` to pull from and persist changes to the browser's local storage. When the user changes the order, the updated order is automatically persisted. 

The problem is at random intervals whilst reordering, the component disappears and I get the following error:

`Uncaught DOMException: Node.insertBefore: Child to insert before is not a child of this node`

I should mention that the changes are successfully persisted, and a page refresh will show the updated order.

### Your Example Website or App

https://codesandbox.io/s/inspiring-driscoll-euflnn?file=/src/index.js

### Steps to Reproduce the Bug or Issue

Check out the codesandbox link. The code doesn't work but it gives you a basic idea of what I am doimg.

### Expected behavior

n/a

### Platform

Firefox 100
Solidjs latest

**Comment by ryansolid** [comment]
More than likely sortablejs is moving the elements but Solid's `<For>` is unaware of it. At a certain point the elements get so out of sync something is breaking. In general you can't just use sortablejs with a declarative framework, you need to move the element back to the original position and get the framework to move it by updating the data to match. You are updating the data but the element needs to be in the original position at that point.

I didn't look into this case specifically admittedly, but I've hit this enough times. This is why libraries like Solid, React, or Vue always have custom wrappers over sortablejs as they don't just offer this as an option.

This issue is relevant and has a simple solution: https://github.com/solidjs/solid/issues/826
