### ISSUE TITLE
<For> doesn't even shallow-diff objects

### ISSUE THREAD

**Issue by danieltroger** [solidjs/solid#1046]
### Describe the bug

When using <For> items are rerendered even though the input doesn't change if the value is an object

### Your Example Website or App

https://playground.solidjs.com/?hash=1357446748&version=1.4.1

### Steps to Reproduce the Bug or Issue

1. Go to playground https://playground.solidjs.com/?hash=1357446748&version=1.4.1
2. Check the console, see that the unchanging elements are being rerendered all the time

### Expected behavior

Only the things that actually changed rerender, as per https://www.solidjs.com/docs/latest/api#%3Cfor%3E

### Platform

- OS: macOS 12.2 (21D49)
- Browser: Firefox
- Version: 101.0b9 (64-bit)

**Comment by LXSMNSYC** [comment]
Well the input actually *does change*. Whenever you call `mock_api_response`, it produces a new set of arrays and objects, which isn't referentially equal to the stored signal's value. The solution here would be to provide a custom `equals` function to createSignal OR make the items comparable during iteration (a custom implementation to For) https://github.com/solidjs/solid/discussions/813#discussioncomment-2063718

**Comment by otonashixav** [comment]
You can use stores with reconcile if you need to diff data: https://playground.solidjs.com/?hash=-1828355856&version=1.4.1

**Comment by LXSMNSYC** [comment]
The keyed package is the one based on the link that I gave. Take note that it just doesn't compare keys, you can compare anything that belongs to the item. It aims to emulate React's selective key mechanism.

**Comment by ryansolid** [comment]
Yeah generally we recommend `reconcile` for deep diffing. It's probably what you want to be doing but I suspect it might not work with the polyfill. More over props sometimes are proxies (dynamic spreads) too so working in a platform without proxies might be an issue in general.

There is the `Key` which is basically like the `For` deep you are looking for I think. It lets you take whatever you want about the object to provide uniqueness. However, I'd caution there because ultimately unless you really only care one level deep it isn't what you want and its better to use proxies.

Finally there is another option which is to manually wrap reactivity yourself. Signals in Signals. It's a bit cumbersome though and the reason we use Stores.

**Comment by danieltroger** [comment]
@ryansolid I only need one level deep in this case and also in the potential future case that I'm thinking about. Where can I find documentation on `Key`? Do you mean `Index`?

<img width="647" alt="Screenshot 2022-06-09 at 10 22 31" src="https://user-images.githubusercontent.com/4047180/172800486-3ef508f4-a001-4529-8db9-66a809b08751.png">

**Comment by danieltroger** [comment]
`<Index>` worked, TYSM!

**Comment by LXSMNSYC** [comment]
@danieltroger We actually meant `Key` (The one you linked and the one in the link I mentioned)

**Comment by danieltroger** [comment]
I see. It's in a separate package though so I'd need to check how big it is and if it has unnecessary side-effects. `Index` seems to be fine for now! The diffing seems to just occur in the memos and reading of the signal given by `Index`

**Comment by ryansolid** [comment]
`<Index>` is key by index which is like not using the `key` in React. It works but it also not recommended for any sort of heavier data like model date, since it when items are move it commandeers the DOM node at the index instead of moving it which impact any state in the DOM like animations etc.. Key is basically the equivalent of `key` in React. We don't ship with `Key` because most of the time you wanted nested reactivity and opting into `<Key>` basically is always forcing a top-down reconcile and recreation of reactive nodes on nested updates. In a sense, Index does that too but it can be useful for simple data.

**Comment by danieltroger** [comment]
All I know about react is that I'm glad to not be working with it and that it's insanely inefficient but I can understand that `Index` is not gonna move nodes around if the values do. I'll keep `Key` in mind if I notice that using  `Index` is inefficient or I want something fancier. Thank you so much for all the info :)
