### ISSUE TITLE
`Dynamic` error in ssr mode

### ISSUE THREAD

**Issue by zoy-l** [solidjs/solid#1145]
### Describe the bug

Hi, I'm creating a css in js tool, the spa performs well, the development mode is normal under ssr rendering, and the build appears after `Cannot read properties of undefined (reading 'cloneNode')`

### Your Example Website or App

https://github.com/zoy-l/solid-vite-ssr

### Steps to Reproduce the Bug or Issue

yarn build
yarn server

### Expected behavior

Expect no error

### Screenshots or Videos

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/15136058/183299675-6ee826e5-31b5-479a-9bbf-0eeeefd46c3e.png">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
As far as I can tell the issue is in `@styils/solid` I'm going to look a little deeper and see what's going on but the hydration is not matching up when a component from it is present.

**Comment by zoy-l** [comment]
Thank you for your work, feel free to @me if needed 🖐

**Comment by ryansolid** [comment]
Yeah I figured it out but it is a weird one. And I imagine a quirk of Vite. The library `@styils/solid` and the rest of the app are referencing different versions of Solid. Vite defaults to the .cjs version and the module defaults to .esm version. For some reason in dev it pulls in the same version but in prod it doesn't. What happens is that the Dynamic gets called without access  to the unique id generator.

The simple solution seems to be add "@styils/solid" to `ssr.noExternal` list.

**Comment by zoy-l** [comment]
👏 wow! thanks... this works fine, i spent a weekend totally not thinking it was the problem here 😱
```js
export default defineConfig({
  plugins: [solidPlugin({ ssr: true })],
  server: { middlewareMode: true },
  ssr: {
    noExternal: [
      '@solidjs/router',
      process.env.NODE_ENV === 'production' ? '@styils/solid' : ''
    ].filter(Boolean)
  },
  appType: 'custom'
})
```

**Comment by GaZaTu** [comment]
@ryansolid I'm getting the same error (similar setting but doing ssg instead of ssr) and I would like to know how you figured out that it was because of some kind of version mismatch so I can debug it myself.

Additionally would this be solvable without using ssr.noExternal? Because the issue comes from my own components and not from a library. 😅

**Comment by ryansolid** [comment]
That's fixed in 1.5. But the trick is to pass the children in directly if they are there.

```js
<Dynamic {...props}>{props.children}</Dynamic>
```
In these cases children pass in always take precedence (same in other JSX frameworks) so it basically ignores the children in the spread.

The problem with existing SSR is that it was generating the string piecewise so there was no way for the spread to know where to insert the children. I now slightly de-opt spreads to render the whole element so we can insert them appropriately.

**Comment by GaZaTu** [comment]
OH my lord i finally got SSG to work 😅. It was a long and tough and painful journey (from trying to figure out SSG with vite+solid at all to literally writing my own fork of vite-ssg because nothing else worked).

But ye that was it, i guess? I still had artifacts tho like children being rendered in the wrong parents so i dropped almost all uses of `Dynamic`; overused that either way so its fine.

Thx

**Comment by ryansolid** [comment]
Yeah it's unfortunate that these sort of rough edges can creep up unexpectedly. Been working on curbing them out but it sometimes only takes one.
