### ISSUE TITLE
Destructuring assignment lost this bind

### ISSUE THREAD

**Issue by awx-marklov-cai** [solidjs/solid#1160]
### Describe the bug
<img width="822" alt="image" src="https://user-images.githubusercontent.com/103561593/184278467-2542ca8a-4170-4a95-84d4-bbcd9e7773b7.png">

<img width="629" alt="image" src="https://user-images.githubusercontent.com/103561593/184277951-b52465ea-5928-44e0-8efb-e2a36a4dc905.png">

### Your Example Website or App

/

### Steps to Reproduce the Bug or Issue

/

### Expected behavior

Should work with destruction

### Platform

solid-js: ^1.4.7
node: 16.15.0
typescript: ^4.7.4

**Comment by ryansolid** [comment]
This is sort of what is awkward about classes in JavaScript. This isn't anything Solid is doing. JavaScript just doesn't bind unless you do it yourself specifically. Otherwise, it uses the calling context which in this case is lost during destructuring.

See:
https://playground.solidjs.com/?hash=1231921722&version=1.4.1

**Comment by awx-marklov-cai** [comment]
> This is sort of what is awkward about classes in JavaScript. This isn't anything Solid is doing. JavaScript just doesn't bind unless you do it yourself specifically. Otherwise, it uses the calling context which in this case is lost during destructuring.
> 
> See: https://playground.solidjs.com/?hash=1082323589&version=1.4.1

Sorry for disturbing. Thanks !
