### ISSUE TITLE
Arrays in createSignal not updating in the view

### ISSUE THREAD

**Issue by outbackStack** [solidjs/solid#1164]
### Describe the bug

I am having trouble displaying the array signal updates using `<For>` control flow. In the console log, I can see the changes, but in the browser, they don't appear.

See example in solid playground

### Your Example Website or App

https://playground.solidjs.com/?version=1.4.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGU0Ac2hqsvAGLcvo5wznAAojIycMx80nIKyqoa2noWVlYy9BAxaLQQvADCDBAujAAUAJT8VrwOeWR8wITyIvQxZL5kcLgACi1t5AC6vAC8Dk4u7l5QamUgNbW8IrTMADIYcGSIvKC80PDbAOQAgoSEanCHvllouNsATFKDWAuSFZYQC8z1fAAWUKILgBJCCEeh8MZlOC+NBVEYAPmq+UWFz4ImcUFGOwAdLjmrRWu1KtjlmsNmRBgtaujcFBgGhKoNgHBsbTGB5utj9nBhmMWWyObhsQA3Gb0OBU3hdXr9IllZpwYVwxFzXHYhXC3yk9YQTbbYBqmlQQZvCrpZGSD5fCbhSLRXBlSqjRHzZG1b4QOgXbFqWgeeWy8jE7Xk4AABkG2JuuDNFtjCyEuCY+TKkoAPPDJbU078AIzw46MRhQfC8KbeMhp-R5zNuxZpmTcGC1xb12kmC4t1ttiRd7ttkTwgBysDgVdwg6z3bTE-hAFVrHwQWDcOPJ3X+zPBwvbrwACJoMjnEtrvvT-S4Rhn1tpgISELMX4jED4wlBioklY6zaSa-dkBlLccAwDCyq8KmG79rwM5XlOUHQbOIBATAXKjpIp5wVBW5-vB2YYCuyiQbheyjliKjRiomHwaKajis+yFRou0hUVBeTLuCz5QmB-yAnA7EOtCvCwsxRG4foiIsTeF7rsRN6IQx0bodJOHnpeKm1BUkiYVWd5-uOUAdnAen6I2jDNum4kLO8VhaZ8EBCKI4iOmBaZFFkpS8OJWorPQ8AlNigphBcfm4AAQvgQIiKmYBQGcKgVAAhNZmCSIMQA

### Steps to Reproduce the Bug or Issue

1. Change the unit input
2. Watch the changes in the `console.log` and the browser.

### Expected behavior

Both items should be updated

### Platform

Solid Playground

**Comment by ryansolid** [comment]
This is due to deep mutation. In SolidJS updates are isolated and fine-grained this means that any mutation that isn't part of the reactive system won't be guaranteed to be processed. Now you could "solve" this by cloning the new item. However this will lose the reference and cause the input to be recreated. See: https://playground.solidjs.com/?hash=1013432362&version=1.4.1

A better solution is to use our stores which are built for deep data structures: https://playground.solidjs.com/?hash=192428604&version=1.4.1

For further explanation of on stores and nested reactivity I suggest trying the Stores part of the tutorial: https://www.solidjs.com/tutorial/stores_nested_reactivity

**Comment by outbackStack** [comment]
Thank you @ryansolid !

What if the data is coming from `createResource`? How could I convert it to stores instead of signals?

See: [https://playground.solidjs.com/?version=1.4.1](https://playground.solidjs.com/?version=1.4.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGU0Ac2hqsvAGLcvo5wznAAojIycMy4QU4uAEpwdEysUrLyiip0Gtp6FlZWMvQQMWi0ELJwuMwAFgAizlAAFACU-Fa8gtVMlSCdXbwitMwAMhjJiLygvNDwUwDkAIKEhGpwC74laLhTAExSALpYA5JWZxBFJWUVvADCDBAujG0dlbz6+g4VZHzAhPIRPQYmRfGRqgAFQHA8iHXgAXgc8Tcnm8zX670+g2GYwmZCmMzmcEWKzWGy21l2vAOkmOAyxklalku72YPz+ANoQJBvgEMHouFCU3BuChXJhZCOCKRIUSyQYLDgzSiNQaTSZhVZ7N4tSgonWAEkIIQBdLmnBfGh2vCAHxvQa8dZ8ERNaXAAB0ns53PIbXdOPGEGShwGXRdguAaDah2AcHdgsYHmq7qJcMRcYTSdw7oAblA1PQ4KHeCKxT6yM1mgC4DnrXb0Z73dWc74A3iCY3w1BDozWpqupJmQNgqEIlEYpW6-bBmyIDk42paB4q9CQX620GyMAAAyHd3bXB996M-vdXC9XjNYsAHhtxa619qAEYbUtGIwoPheO4vPmyNf9GfO93gda8ZG4GBgIdB9BRMdYoOgmCJAQxCYJEG0ADlYDgADcHQ+9oOvPCbQAVUpXgjRNXBcPwkDUKI9CyJ2Xh6jQMg1k-GiUMI-RcEYbjQICCQQjqeEQG9CV1xGQNkkkAToJAZodjgGBLSnK86NQ3giP4gitIYm0QGUmAU2wyQuL0+jiMs-SMCo5RNK0wYiWlFQDxUGzULzAs4DE4z90paRPMQipKIFMTzSnXV9TgMLcHNNSgscpyPjtYLBgs5KrPQoyXBMg9zN42iUofXjdKyrpWgufT9CE+TcKgOC4Hq-RwMYSCb30BCNQgC4rCEURxEnBE7WvB4SmeVLWxGeh4Ced0szCdY5twAAhfADREK8wCgVYVFaABCHqwFpIA)

**Comment by ryansolid** [comment]
It's a bit more involved than that because you probably mean you want to diff since the data coming from the server is referentially unequal.

There are a couple of tricks to do this, but I'm actually working on making this much easier in 1.5. Currently you need to put the resource inside a store getter and then at the end of the fetcher call `reconcile` for it to deep diff. Solid's Realworld Demo does this trick but I want to improve on this.

**Comment by outbackStack** [comment]
Ok Cool, I will wait for your easier solution in `v1.5` 

I'm 3/4 of the way converting a big app over and so far so good 😊

**Comment by ryansolid** [comment]
storage option added in 1.5 on `createResource`
