### ISSUE TITLE
solid/html raise error

### ISSUE THREAD

**Issue by Hi-Alan** [solidjs/solid#1207]
### Describe the bug

Safari:
```
TypeError: null is not an object (evaluating '_$el5.firstChild')
```
Firefox:
```
Uncaught TypeError: _$el5 is null`
```
Chrome:
```
Uncaught TypeError: Cannot read properties of null (reading 'firstChild')
    at HTMLTemplateElement.eval [as create] (eval at parseTemplate (html.js:472:53), <anonymous>:8:15)
    at html (html.js:478:25)
    at App (error.js:5:16)
    at web-e5bc499a.js:167:53
```

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

Code:
```html
<!DOCTYPE html>
    <meta charset='utf-8'>
    <body>
      <script type="module">
        import { render } from 'https://cdn.skypack.dev/solid-js/web';
        import html from "https://cdn.skypack.dev/solid-js/html";

        const App = (props) => {
            return html`
                <table>
                  <tr>
                    <td width="112">Success</td>
                    <td width="30">
                      <input />
                    </td>
                  </tr>
                </table>
          `;
        }
        render(App, document.getElementById('root'))
      </script>
      <div id="root"></div>
    </body>
  </html>
```

### Expected behavior

got error

### Platform

- OS: [macOS]
- Browser: [Chrome, Safari, Firefox]
- Version: solid 1.5.4

**Comment by ryansolid** [comment]
I'm pretty sure I know what the error is but I'm unclear if it is easy to provide a better error message. In JSX we give more details on the error in dev mode, but we don't dev mode build's for Tagged Template Literals currently. The problem is we setup the template with `innerHTML` and cloneNode and the browser likes to insert `<tbody>` elements which screws up the walks from the generated code.

```js
const App = (props) => {
            return html`
                <table>
                  <tbody>
                    <tr>
                      <td width="112">Success</td>
                      <td width="30">
                        <input />
                      </td>
                    </tr>
                  </tbody>
                </table>
          `;
        }
```

The fix is to put a `<tbody>` in but the truth is the browser has a number of these potentially unexpected behaviors where they "fix" the HTML. In JSX which we build ahead of time we are working at using the build step to pre-emptively identify these scenarios, but here happening at runtime it is a bit more prohibitive.

**Comment by Hi-Alan** [comment]
It works fine now. Thank you for you reply, Ryan Carniato.
