### ISSUE TITLE
[Question] Uncaught (in promise) Error when using `createResource`

### ISSUE THREAD

**Issue by wesdse001** [solidjs/solid#1280]
Hi All,

I'm trying to learn the SolidJS `createResource` API. When I run the following code, the application crashes when the `userId` signal becomes a negative number, with an error in the console `Uncaught (in promise) Error: ID can't be less than 1`.

I would like my `fetchUser` to pass the error to my `data.error` inside my `<App />`. But it crashes as soon as the first error is encountered.

How do I catch the error and pass it along to `data.error`? If I use `try ... catch ...` I still have to throw an error in the catch block.

```js
import { render } from "solid-js/web";
import { createSignal, createResource } from "solid-js";

const fetchUser = async (id) => {
  if (id < 1) throw new Error("ID can't be less than 1");
  const response = await fetch(`https://swapi.dev/api/people/${id}`);
  return await response.json();
};

const App = () => {
  const [userId, setUserId] = createSignal();
  const [data, { mutate, refetch }] = createResource(userId, fetchUser);

  return (
    <>
      <input type="number" placeholder="Enter Numeric Id" onInput={(e) => setUserId(e.currentTarget.value)} />
      <button onClick={() => mutate({ name: "Mutated without promise" })}>Mutate</button>
      <button onClick={() => refetch()}>Refetch</button>
      <div>{data.loading ? "Loading..." : "Done"}</div>
      <div>{data.error ? data.error.message : "Success"}</div>
      <pre>{JSON.stringify(data(), null, 2)}</pre>
    </>
  );
};

render(App, document.getElementById("app"));
```

**Comment by ryansolid** [comment]
There are 2 ways to accomplish this. One is to wrap things in an `<ErrorBoundary>` which gives you a way to catch errors and display appropriately. The other is to use something like `<Show>` `<Switch>` or conditional logic to only read `data()` when there is no error.

What is happening here is that when you read a resource and it is in error it will throw because it is considered to be in an error'd state. This is what makes things like that `<ErrorBoundary>` work. The idea is that accessing the resource is a read. If a resource is ever in an invalid state the UI would be inconsistent with reality and must error. This pattern might seem weird at first but it ties the error to where they are used in the UI with boundaries allows for collecting these.

**Comment by wesdse001** [comment]
@ryansolid thank you so much!

I understand now. My app crashes because I always read data in the line `<pre>{JSON.stringify(data(), null, 2)}</pre>`.

I should not read data when `data.error` exists. This can be done use `<Show>`, `<Switch>`, or conditional logic.

In a real world app, wrapping these types component using `<ErrorBoundary>` at some parent component is good practice.
