### ISSUE TITLE
Is there any way to remove effect?

### ISSUE THREAD

**Issue by g-mero** [solidjs/solid#1332]
### Describe the bug

Is there a func to remove CreateEffect?
just like
```
createEffect(() => {
          console.log(process())
          if (process() == 100) {
            do somethig...
            removeEffect() //to remove this effect
          }
        })
```

### Your Example Website or App

*

### Steps to Reproduce the Bug or Issue

use CreateEffect

### Expected behavior

use a func to remove effect

### Platform

OS: windows
Browser: edge

**Comment by atk** [comment]
Just wrap the effect in its own `createRoot(dispose=>createEffect(…))` and call the `dispose()` function to actually remove the effect.

**Comment by LiQuidProQuo** [comment]
#### createCancellableEffect
https://playground.solidjs.com/?hash=1649138222&version=1.6.1

- `createRoot` will not auto dispose, so you might want to also hook into the owner cleanup.
- after calling dispose in the effect, make sure not to trigger new reactive tracking.

**Comment by g-mero** [comment]
thanks a lot

**Comment by snnsnn** [comment]
In Solid there is no subscription queue, every signal keeps its own subscriber list. Effects subscribe to changes when they read a signal and unsubscribe once they are run and this repeats in every update cycle. So, if you wrap the inner code with an outer condition practically you will be removing the effect once the condition is met since effect will not be able to subscribe for the next round of updates. https://www.solidjs.com/docs/latest#basic-reactivity

`createRoot` is a way to opt out of this automatic dependency tracking. Unfortunately proposed solutions create unnecessary wrapper around something that comes for free.
