### ISSUE TITLE
useContext form population causing Zod form validation to fail

### ISSUE THREAD

**Issue by 0bon** [solidjs/solid#1357]
### Describe the bug

Not sure where to post this but it seems to be an issue with ```useContext```, so I am going to make a bug report here first.

I am using ```useContext``` with a solidjs storage primitive ```createLocalStorage()```.
I am then creating a store ```Provider``` for a form, and then using the provider's values to pre-populate a form text input.

I am also using Zod for the validation, which  checks whether the form input is empty or not.

The strange thing is when the field is populated and the submit button is pressed a validation error is thrown stating that the field cannot be empty.
If I pass the variable via props instead, everything works as expected.

### Your Example Website or App

https://codesandbox.io/s/winter-tdd-n45wry?file=/src/main.tsx

### Steps to Reproduce the Bug or Issue

Click on submit button, you will see form error ```String must contain at least 1 character(s)```
Enter something into the input field and then press submit and everything should work as expected.

### Expected behavior

n/a

### Platform

latest solidjs
latest zod
latest storage primitives

**Comment by ryansolid** [comment]
Yeah it is strange. Since it is getting to the field and synchronously (I logged it in top level component). So I don't think the issue is with context. For submit to not have data I can only imagine it is how the form component is getting its data. Commenting out the validator shows an empty string. It's almost like it is relying on an input event to set its initial data.

Fvelte definitely doesn't appear to have it when clicking submit. I am unclear how the library gets its initial data but it definitely doesn't match up.

**Comment by 0bon** [comment]
The reason I mention solidjs as a possible cause is because if I use the traditional way of passing props from parent to child, this issue is non existent. It is possibly an issue with Zod, but the fact this only occurs with useContext could suggest a bug in the way useContext is passing data to the component.

**Comment by colinhacks** [comment]
> I am unclear how the library gets its initial data but it definitely doesn't match up.

@0bon Ryan is referring to @felte/solid here. I have no familiarity with this library but it's the most likely culprit

**Comment by ryansolid** [comment]
Yeah the data is missing even before it gets to Zod. This has nothing to do with Zod and probably little to do with `useContext`and everything to do with the form library. It isn't reading the state from the input at the right time somehow.. assuming that is how it gets the initial value. Is there a way to initialize Felte fields with a value?

**Comment by 0bon** [comment]
I was debugging the code, and it seems during the initial initialization, the dom is passed to the form function before the value is set. Although the value being set at a later point doesn't seem to trigger the listener, probably because the listeners are started after the value is available.

**Comment by ryansolid** [comment]
Yeah I see it timing wise. So I get what's happening but I'm a bit surprised this hasn't been hit/addressed before since the way you author with this library the form ref is going to happen first. Since they are reading from the DOM they should do it in an `onMount` or `useEffect` which should run after all the rendering.

**Comment by 0bon** [comment]
Maybe this is an interesting case for an additional feature - Namely, being able to specify whether ```use``` or similar refs should be executed before or after a render.

**Comment by ryansolid** [comment]
We already have the means to schedule both timings leaving as is and by using `onMount`. Being a JSX API we don't really have the syntax to make that configurable. In any case this feels like a Felte bug.
