### ISSUE TITLE
Reactivity being lost using if statement (conditional render)

### ISSUE THREAD

**Issue by albizures** [solidjs/solid#1377]
### Describe the bug

When the `loading` value is used in a conditional render the reactivity is lost, unlike the value is used within a ternary operator

```tsx
import { render } from "solid-js/web";
import { createResource, createSignal, For } from "solid-js";

const fetchUser = async (id: number) =>
	(await fetch(`https://swapi.dev/api/people/${id}/`)).json();

const users = [
  1,2,3
]

function Counter() {
  const userResorces = users.map(user => createResource(user, fetchUser));
 
  return (
    <div>
    	<For each={userResorces}>{([user], i) => {
          console.log(user.loading)
          return <div>{i} - {user.loading? 'loading...': 'Done  '}</div>
        }}</For> 
   
    	<For each={userResorces}>{([user], i) => {
          console.log(user.loading)
          if(user.loading) {
            return <div>loading...</div>
          }
          return <div> Done </div>
        }}</For>
    </div>
  );
}

render(() => <Counter />, document.getElementById("app")!);

```
This example is simple, however, the pattern is very common with larger jsx structures and both ways should work fine.

### Your Example Website or App

https://playground.solidjs.com/anonymous/8c410f26-dded-4e54-86ce-bd5f52ae6aa0

### Steps to Reproduce the Bug or Issue

1. Go to the example
2. Check the version using if statement
3. Notice it gets staled in the loading state

### Expected behavior

Both version, using if statement and ternary operator, should work the same

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
This is an implementation choice but it is one we do consistently. Our callbacks from control flow are untracked the same way component bodies are. It helps decouple nested logic from the parent control structure. Updating loading shouldn't cause list reconciliation to happen again. We could alternatively insert more tracking effects per row but that would carry a slight cost I wouldn't want to opt everyone into.

Additionally, while this means no early returns it also protects against unnecessary work without trying to do compiler optimizations against arbitrary JavaScript statement blocks. 

Even in that example the second one would create and insert a new div element instead of just updating the text. But probably the best answer for more complex views is use `<Show>`.

**Comment by albizures** [comment]
Thanks for the explanation, this statement really helped me to understand what really happens 
> Our callbacks from control flow are untracked the same way component bodies are.

However I think this aspect is not really well explained in the tutorial, and creates scenarios similar to what happens with React hooks and their rule.

Is this something that we need to get used to while working with solid? Having two 'realms' one with reactivity and another without it? Or this is going to change in future versions?

**Comment by ryansolid** [comment]
Yeah I don't see this changing. There are tracking zones and non-tracking. Both are necessary for things to work properly. Or rather things get a lot more confusing and error-prone without it. It might not seem that way right now, but the consequence of tracking in these sorts of cases can lead to more unexpected behavior. This is at least consistent and predictable. Since all JSX callbacks are not reactive, event handlers, control flow.. The only things that are reactive are JSX expressions and functions passed to hooks.

But Solid does have its rule. And it's basically a limitation of the JavaScript language, in that we have to be aware of losing reactivity if values are accessed outside of where they are tracked. This particular characteristic is arguably due to Solid's reactivity independent of components. In a sense, these callbacks are like component bodies because it is a logical root. This might not be intuitive right now and needs better documentation. It is mentioned in the API reference docs, but as you said missing from the tutorial.

**Comment by albizures** [comment]
Thanks @ryansolid! I appreciate your detailed comments 🙏

I'll close this issue, since this is intentionally.
