### ISSUE TITLE
Issue with createEffect using on/untrack on array signals

### ISSUE THREAD

**Issue by trfx351** [solidjs/solid#1409]
### Describe the bug

After upgrading an app from SolidJs 1.3.13 to 1.6.3, some effects stopped updating/re-running when dependencies are updated. The effects use on() with a dependency list including a signal with an array, and when adding items to the array the effects no longer re-run as they did in 1.3.13. The playground link shows an example of this. The code is a simplified version of the application code, where a store is used to hold an array of objects. The store is updated using the produce() API. The example shows 4 methods to print the length of the array:

1. Setting a signal in a createEffect block;   
2. Setting a signal in an On() block within createEffect, with the array as dependency
3. Setting a signal in an untrack() block within createEffect
4. Derived signal

In 1.3.13, all 4 methods work and clicking the "Test" button in the example updates all 4 printouts. In 1.6.3, methods 2 and 3 no longer work.

I noticed that if you change line 25: 
`on(items, (newItems) => {`    to `   on(() => items().map(x => x), (newItems) => {`   
the effect re-runs correctly on array change.

### Your Example Website or App

https://playground.solidjs.com/anonymous/06bb0f7e-b134-48fe-8637-ab8a14fb5d05

### Steps to Reproduce the Bug or Issue

Go to the playground link and click the Test button

### Expected behavior

All 4 methods should work to detect updates to the array.

### Platform

- OS: Windows
- Browser: Firefox, Edge
- Version: 1.6.3/1.6.4

**Comment by ryansolid** [comment]
Thanks for reporting. We made some changes in 1.4 to improve the efficiency of stores over notifying. Namely that updating an unrelated property would cause the top level object to notify unnecessarily. When in fact the only case where we wanted to do that is for arrays that change. Immutable changes or tracking length will work, but not tracking length no longer triggers. Let me see if there is a reasonable fix here.

I mean it's an interesting question. Because even patching length, there was some expectation that setting an index wouldn't cause the parent array to notify. Like the thing should list to the indexes it cares about or track the iterator. You should be able to set a new value in the index without everything that listens to a particular different index in the array getting notified.

The short solution is to use the $TRACK symbol..  `const items = () => data.items[$TRACK];` but probably not desired as being like the global way to access that state. I'd consider making length special-cased (it already is) but I'm worried it sets up the wrong expectations that it will notify whenever indexes change by saying `on` `items`. It is probably worth acknowledging arrays are special but there is a certain question of whether they intentionally are being used like a list, vs some sort of Map-like block storage. 

The current solution is more purist in that it only notifies when the items are changed Ie.. swapped. But I understand that isn't the intention here. `on` and `untrack` are really those sort of expert type APIs where you need to understand what you are doing since untracking the wrong thing loses reactivity.

**Comment by trfx351** [comment]
Hi Ryan, thanks for the quick reply. I saw there were some fundamental changes with arrays in the versions between 1.3 and 1.6 so I wasn't all that surprised to see something break.

In this case though I don't see how the .length property is affecting this. As you can see in the example, a standard createEffect or a derived signal work just fine (case 1 and 4) to track changes to the array. Printing the length was just for demonstration purposes. And the .length is accessed within the on() and untrack() scopes (in case 2 and 3), so should not be considered for reactive updates. Only changes to the array itself should be notifying of changes, and the array itself (or the signal accessing the array) is the dependency into the on() function.

Here is another example that does not use .length, but copies the store array into the s1-s3 signals, and lists the contents in a <For> loop: [https://playground.solidjs.com/anonymous/c9676aa8-07d7-4217-b382-82aafc23a30b](https://playground.solidjs.com/anonymous/c9676aa8-07d7-4217-b382-82aafc23a30b) 

This is actually closer to the case I have in my application code.

Or am I misunderstanding something here in your explanation/Solid functionality, and the recent changes?

**Comment by ryansolid** [comment]
Yeah. When I talk about making length special I meant looking for a certain property to tell the parent to notify. Right now if you subscribe to `items` for it to trigger it needs to be replaced. Pushing to it will only set the last index, and update the length. So if you aren't subscribed to either of those then it won't re-run which is why the `on` and `untrack` versions aren't working.

I was commenting that maybe a length change should be something that triggers the array. But right now every piece is independent. Like if you have something like:

```js
createEffect(() => console.log(items()[2]))
```
In the current behavior pushing wouldn't retrigger it if the array length is 3 or larger. Whereas triggering on length for example would. Or triggering on any array index would.

**Comment by trfx351** [comment]
I see what you mean now, thanks for the explanation. I have now refactored my code to use `()=> items.().length` as a dependency to `on()` and it works as before. It doesn't look quite as nice though :)

The new behavior makes sense for consistency/purist way as you mentioned, but it would be nice to have a built-in way to subscribe to changes in array structure (from push/pop/index assignment). Something similar could be done for regular objects, if you would like to subscribe to changes to any property on the object. Maybe a consistent API for arrays and objects could be developed here to subscribe to any change to the reactive source. But that may not fit with the fine-grained reactivity concept though, and moving more towards an observable event library.  

Anyway I have things working again and understand the new behavior, thanks again for your help.
