### ISSUE TITLE
solid-js/store `reconcile()` with key throws given null array items

### ISSUE THREAD

**Issue by sqwishy** [solidjs/solid#1416]
### Describe the bug

When using reconcile with an array that contains `null`, an exception is raised in `applyState()`.

``` javascript
const [_, setState] = createStore({ "items": [null] })
setState(reconcile({ "items": ["something"] }))
```

Similarly for the opposite, where the array in the store has a non null item being reconciled with a null item.

Not entirely sure if I'm just misunderstanding the API but it seems like it should just modify the store to match the target state, so set the array to `[null]` in the example above.

For others that might run into this issue, a **workaround** seems to be to explicitly pass a null key to reconcile: `setSolved(reconcile(whatever, { key: null }));`. Since the exception is raised when trying to get the key on a null value, but this code is skipped if `key` is falsely (`key` defaults to "id" per the docs).

### Your Example Website or App

https://playground.solidjs.com/anonymous/17154c68-141f-495d-8fa5-cdf2a2837e9d

### Steps to Reproduce the Bug or Issue

I dunno just run the playground thing maybe; for me it shows an exception in the console in the bottom right of the page.

### Expected behavior

No exception is raised I guess and the state matches the target.

### Platform

Fedora Linux, Firefox 105.0.2

**Comment by LiQuidProQuo** [comment]
didn't test this fix, but we are missing null guard. 
so that is a possible fix direction

source is in `applyState`

![image](https://user-images.githubusercontent.com/105608035/206935974-56c92b05-8207-4cdc-a708-ea34223b0eb9.png)


with the above patch
<img src="https://user-images.githubusercontent.com/105608035/206936074-bc3143e6-91a7-4ba3-b770-4fe5e1809fc3.png" height="300"/>

without the patch 
<img src="https://user-images.githubusercontent.com/105608035/206936093-a0cdeb56-c56a-4b0a-9433-acc828bc1e14.png" height="300"/>

**Comment by ryansolid** [comment]
Thanks @LiQuidProQuo. This looks correct.
