### ISSUE TITLE
Incorrect "jsx-runtime“ exports

### ISSUE THREAD

**Issue by LancerComet** [solidjs/solid#1429]
### Describe the bug

In package.json there is an incorrect jsx-runtime exports: [L97](https://github.com/solidjs/solid/blob/main/packages/solid/package.json#L97)

```json
"./jsx-runtime": {
  "types": "./types/jsx.d.ts",
  "default": "./dist/solid.js"
}
```
where `./dist/solid.js` is incorrect. This will break compiler such a SWC or TSC when jsx runtime was imported directly (i.e, no `vite-plugin-solid`, even no vite).

The correct setup should be:

```json
"./jsx-runtime": {
  "types": "./types/jsx.d.ts",
  "default": "./h/jsx-runtime/dist/jsx.js"
}
```

### Your Example Website or App

https://github.com/LancerComet/solid-jsx-runtime-issue

### Steps to Reproduce the Bug or Issue

1. Setup a new project which no `vite-plugin-solid` was introducted.
2. Let SWC or TSC use JSX Runtime directly, like:

`.srcwc`:
```json
{
  "jsc": {
    "transform": {
      "react": {
        "runtime": "automatic",
        "importSource": "solid-js"
      }
    }
  }
}
```

or ` tsconfig.json`:
```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "solid-js"
  }
}

```

### Expected behavior

The correct setup in [here](https://github.com/solidjs/solid/blob/main/packages/solid/package.json#L97) should be:

```json
"./jsx-runtime": {
  "types": "./types/jsx.d.ts",
  "default": "./h/jsx-runtime/dist/jsx.js"
}
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/10321350/208066180-3763b72e-bc55-44c2-9c9a-5f50aca2e767.png)

### Platform

Platform doesn't matter

**Comment by ryansolid** [comment]
This is intentional. We don't generally use a jsx-runtime but we need it for TS. We have a custom transform that has a completely different type of runtime. The expectation is to use `"jsx": "preserve"` and use our babel plugin. One day I hope we support a SWC one as well.

However, in some specific cases we support the the standard transform. This has reproccusions on ergonomics and performance. It is different enough it actually needs its own types because you need to author differently with it. We put that under its own location. Not to be confused with the preferred path.

**Comment by LancerComet** [comment]
Didn't expect that, and I'm starting to be curious about how the solidjs works. I am closing this issue for being given good explanation.
