### ISSUE TITLE
Calling sub-function of effect asynchronously breaks effect reactivity

### ISSUE THREAD

**Issue by melektron** [solidjs/solid#1464]
### Describe the bug

When an effect contains a sub function which accesses reactive data (signals or stores), the effect stops tracking those sources as soon as that sub function is called asynchronously (with setTimeout or another external method like a button click event).

The following example works as expected:
```typescript
createEffect(() => {
    const subFunction = () => {
         console.log(someSignal());
         console.log(someStore.a);
    }

    // some further checks

    subFunction();
}
```

When the function is called asynchronously however, the effect stops tracking:
```typescript
createEffect(() => {
    const subFunction = () => {
         console.log(someSignal());
         console.log(someStore.a);
    }

    // some further checks

    setTimeout(subFunction, 1000);
    // or even: setTimeout(() => { subFunction(); }, 1000);
}
```

The first time a change is detected, the effect runs and executes the subFunction after 1 second. But any further changes to the data sources will no longer be registered.

This also applies to cases where subFunction is sometimes called by the effect directly, but then later because of some condition is called asynchronously. After the asynchronous call, the effect stops tracking the data sources, even when the next execution would be synchronous again. 

I have provided a playground below that illustrates the problem.

### Your Example Website or App

https://playground.solidjs.com/anonymous/395346e0-ed35-437e-9f68-e3975f3a5716

### Steps to Reproduce the Bug or Issue

The playground contains two simple examples. A simple example with just one signal and a more complex example involving stores and nested reactivity, but both show the same behavior.

When clicking the button "Increment A", "Increment B" or "Increment C", the console prints the new values (a is a single signal while b and c are contained in a store and a single effect tracks both of them so they will be printed together.

The "Switch Stores" button swaps the used store contained in a signal to test nested reactivity and should update the same effect as b and c. 

Then click the "Make async" button which enables the execution of the sub function via a timeout. When clicking any of the Increment buttons or the switch stores button, they should do the same thing as before with one second delay. When clicking again however, nothing happens because the effect doesn't run anymore, even when switching back to synchronous mode using the "Make sync" button.

### Expected behavior

I would expect the effect to check for it's sources when it is created or first run, and then keep tracking those same sources. As it seems to me (I don't know exactly how it works however) the effect re-evaluates the sources every time and doesn't track them anymore when they are not accessed before return of the effect. This seems unintuitive for me.

### Screenshots or Videos

No special screenshots, the playground contains everything.

### Platform

- OS: macOS, iOS, Linux
- Browser: Only Chrome, Safari, Safari mobile tested
- Version: 1.6.7, 1.6.8 

### Additional context

I stumbled across this because I tried to implement a user confirmation that sometimes asks the user whether to use the changed data values or not, but only asks the user in some special cases and not every time. After the prompt, further changes were not detected even if they did not need user confirmation.

**Comment by ryansolid** [comment]
This is very much intentional. We keep the dependencies up to date so as to not over-execute. Like if something stops listening then there is no need to have it trigger anymore. In a lot of teaching materials I use silly examples like this:

https://codesandbox.io/s/conditional-dependency-hbjg6

But the truth is we use the same sort of logic to do conditional branching in our JSX rendering. You wouldn't want dead branches to still be tracking.

Additionally this is how automatic dependency tracking works. It is in synchronous. Same in Vue or MobX or any runtime auto-tracking reactive system. When an arbitrary callback comes back async it is no longer under our tracking context.  In one sense it might be seen as a limitation but its also an advantage that compiled solutions can't emulate. 

Trying to patch the browser in these cases leads to a ton of unwarranted complexity (things like zone.js from Angular). And in most cases like data fetching where early side effects are expensive, having something downstream also track and perhaps accidentally trigger the whole effect to re-run is problematic. In that case, the answer is typically to break it apart into multiple computations.

In this case, I don't quite follow the scenario but the solution usually involves hoisting the tracking parts up. Whether that is being explicit with `on` or manual.

**Comment by melektron** [comment]
Thanks for the explanation! 

In the end, I solved my issue by adding "useless" access to all the data required at the top of the effect that is always run but the result discarded. Using ```on``` wasn't a solution for me as it would have gotten to confusing because of my nested data structure.

Anyway, now I understand  more about how effects work, so thanks again for explaining this and thanks for creating this awesome Framework!
