### ISSUE TITLE
Infinite loop when a component throws after an effect has been registered

### ISSUE THREAD

**Issue by vjoao** [solidjs/solid#1478]
When a component throws for some reason (e.g TypeError) but an effect has been defined before that, if the parent had defined an `onError` to capture the throw, the render enters an infinite loop.

Minimal reproduction: https://playground.solidjs.com/anonymous/43632f41-5383-4774-ba79-e64f30c97e28

Seems to repro in all versions.

**Comment by ryansolid** [comment]
Thanks for the report. This is an interesting one. The weirdest part is I can't seem to figure out how it is getting set back to stale. Between the finally and the catch is suddenly shows up. Puzzling.

**Comment by ryansolid** [comment]
Alright i know what this is. It was a bug fix based on a suggestion from $mol framework creator and maybe isn't practical in eager computed frameworks like Solid is today. The thought is if something throws in a memo, it should mark itself stale again so that it throws the next time it is read/calculated instead of being treated like it has resolved. Unfortunately for us that is creating the loop. 

I think that behavior is correct so the real thing we want to be doing here is basically prevent the effect from running. The question is it reasonable to throw away the whole side effect chain and I think the answer is no. On any given update we wouldn't much perhaps but on initial render we are throwing away everything.

The course has to be on error we cleanup any owned things. They are invalid anyway and would be cleaned up next cycle anyway. I will make the fix.

**Comment by fabiospampinato** [comment]
> if something throws in a memo, it should mark itself stale again

Is this the code that does that?

https://github.com/solidjs/solid/blob/a572c12c29c91e587f08a11b7768caee107560de/packages/solid/src/reactive/signal.ts#L1337

If so shouldn't all the dependencies of the memo be marked as stale too?

I'm not sure how this leads to a loop though 🤔

Like I've no idea why this is loopy:

```ts
render(() => <App />, document.getElementById("app"));
```

But this isn't:

```ts
render(App, document.getElementById("app"));
```

**Comment by ryansolid** [comment]
It's the hidden computation from the component in Dev Mode that is causing this whole thing. I think the simplest reproduction I have is:
https://playground.solidjs.com/anonymous/3c4c71ad-772b-4900-bb3f-2fe8868e8ea3

The problem is the effect gets queued and it sees its stale parent and causes that to re-run. It's related to Solid's runTop mechanism.
