### ISSUE TITLE
undefined behavior when using `undefined` to delete a key in a store that was initialized with `undefined` 

### ISSUE THREAD

**Issue by LiQuidProQuo** [solidjs/solid#1507]
### Describe the bug

> it seems to be behaving inconsistently, if the property is already set to undefined it doesn't delete it, otherwise it deletes it. 

thank @fabiospampinato  for the summary 

### Your Example Website or App

https://playground.solidjs.com/anonymous/d299daac-96c8-4670-b857-4d99e706fbfe

### Steps to Reproduce the Bug or Issue

see playground logs, where it logs `'a' in state`

App1 
 - initialize key `a` with undefined 
 when checking 'a' in state before,  it return true
 but after setting key to `undefined`  to trigger delete, the key remain and the after check is also true.

App2 
 - initialize key `a` with a value (defined)
  when checking 'a' in state before and after setting to undefined it 
  works as expected. setting key to undefined in solid deletes the key

### Expected behavior

it is expected that setting a key to undefined will delete the key, to create a more consistent experince.

### Platform

playground

**Comment by ryansolid** [comment]
I'm not going to lie. We're likely never going to fix this. Atleast not before 2.0 timeline with the new store mechanisms. We aren't going to parse through every value checking for undefined on initialization or set. There is unwrap but it has early exits. And even then for the path-based syntax I imagine it will work the same since one is a value and one is a "command". Like if you set an object with an undefined value we don't delete it. It's only happening on merge and direct set. The mental model here for the setter is a DSL and in so this is by design.

**Comment by LiQuidProQuo** [comment]
This issue main focus is not the initial  store value being undefined, but rather that you can't delete it if it was.

there is no need to eagerly check the store ( hopefully ) , to check in the time of delete, if the key exists, delete it.
