### ISSUE TITLE
For component does not preserve input focus

### ISSUE THREAD

**Issue by adamjedlicka** [solidjs/solid#1520]
### Describe the bug

If you use the For component for iterating over array coming from signal/resource and rendering inputs, focus is lost when source signal/resource si mutated.

### Your Example Website or App

https://playground.solidjs.com/anonymous/db8d23b7-4b7f-42e1-bf93-c06e51e7616b

### Steps to Reproduce the Bug or Issue

First input is normal and typing inside works as expected.

Second row of inputs is rendered by For and focus is lost during typing.

Third row of inputs is rendered by Index, focus is not lost, but Index brings its own issues.

### Expected behavior

I would expect to not loose focus when typing inside the second row of inputs in the playground.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by LiQuidProQuo** [comment]
from the docs `<For/>` is **A referentially keyed loop** 

"str1" is not referentially equal to "str2", and so the item is updated.


![image](https://user-images.githubusercontent.com/105608035/216729320-1a0adb64-7cac-4ecd-9584-8e56facbc19c.png)

**Comment by adamjedlicka** [comment]
Yeah good point. This can be solved by wrapping the array values into objects and not changing the object reference when mutating the values. But this seems like a hack.

Would it be possible to add new prop to the For component which would override the keying algorithm? For example if I iterate over array of objects with IDs, it could use the IDs for keying instead of object references.

**Comment by thetarnav** [comment]
If you want to use keys for comparing items, there is `<Key>` component in solid-primitives lib for that: https://github.com/solidjs-community/solid-primitives/tree/main/packages/keyed#key

**Comment by ryansolid** [comment]
Before going to `Keyed` this is the case for `Index`. The tricky part of `Keyed` is were something deep not to match you'd have recreated reactivity generally. So it's use is much narrower.

But yes we don't track deep. The Store section of the tutorials on the site is a good reference to how this works and how we approach it.

**Comment by adamjedlicka** [comment]
Oh I didn't know about that one. Thats perfect. Thank 🙂 

So I guess this issue can be closed?

**Comment by atk** [comment]
As an aside, if you ever want to reset the selection after changing the value for wherever reason, there's also a selection primitive in solid-primitives.

**Comment by adamjedlicka** [comment]
@ryansolid Index can't be used in my case because Index doesn't work (expected) with TransitionGroup. Key with TransitionGroup works flawlessly.

**Comment by LiQuidProQuo** [comment]
> Would it be possible to add new prop to the For component which would override the keying algorithm? For example if I iterate over array of objects with IDs, it could use the IDs for keying instead of object references.

that is an incredible idea, adding `key_by: callback`. 

though, it is not ideal, for "strings", because it going to be hard even for you to track what changes without some meta data.
like id, or object reference identity.


wrapping is probably the best course of action for the use case of simple primitives list.


started a poll with your great suggestion, which is the 2nd time I see people asking for it 
https://github.com/solidjs/solid/discussions/1523

**Comment by ryansolid** [comment]
Yeah, I've considered this because the comparison is the cheapest part of this really so whether it is referential or by function is fine. I was concerned it would send people on the path and keep immutable data, as that is a terrible pattern. Like keyed fits a very specific window. If nested reactivity is involved it is very wasteful.

That being said the biggest win would be that I think if done right it could get rid of the need for having both Index and For. Not sure that is reasonable for performance. To do this the signature would have to return functions for both the data and the index. That's true of this keyBy call as well.

I'm sure people would like this but I'm concerned there may be less understanding of the repercussions.

> @ryansolid Index can't be used in my case because Index doesn't work (expected) with TransitionGroup. Key with TransitionGroup works flawlessly.

Yeah Index wouldn't move the items so there is nothing to animate.. That being said I'm unclear how `Key` solve it over `For` since the only identity is the string itself which when mutated would lose that identity. Once you are dealing with objects and ids. `For` should work.

**Comment by adamjedlicka** [comment]
@ryansolid In my actual use case, I'm rendering list of objects with IDs into a table of inputs (something like excel table). I need inputs to bo controlled (they can reference each other so typing into one can affect the others) and I want swapping and removal/addition of rows to be animated. For this use case, only Key component, keyed by my object IDs works.

**Comment by ryansolid** [comment]
There is a way to make Resources use Stores internally but the API is a bit clunky right now. `Key` is fine for single depth things, but ideally, it shouldn't need to exist. But that's for me to figure out. Thanks for clarifying. Anyway, I think the question is answered.
