### ISSUE TITLE
Components are re-rendered when using For multiple times with the same array that contains JSX

### ISSUE THREAD

**Issue by webblocksapp** [solidjs/solid#1536]
Given the following array:
```typescript
const elements = [{ text: "Comp1", children: <Comp1 /> }]
```

Iterating the same array `n` times that contains JSX with a `For` component, JSX runs `n` times. Sometimes `For` needs to be split for complex layouts. In the following example, the same array is iterated 2 times for rendering different items making JSX be rendered 2 times, despite JSX being called only in 1 iteration `(item.children)`.

```tsx
<>
    <div class="nav nav-tabs flex-grow-1 d-flex justify-content-end ps-2 pe-2 pt-2">
      {/**
         * Iterating the same array that contains JSX with a For component,
         * JSX is run twice. Sometimes <For /> needs to be split for complex layouts.
         * If you comment the first <For />, component mounts 1 time as expected.
      */}
      <For each={props.elements}>
        {(item) => (
          <div class="nav-item">
            <span class="nav-link">{item.text}</span>
          </div>
        )}
      </For>
    </div>
    <div class="tab-content border border-top-0">
      <For each={props.elements}>{(item) => item.children}</For>;
    </div>
</>
```

The previous code can be visualized on the following [playground link](https://playground.solidjs.com/anonymous/e10f7994-8487-4e12-b8b1-8830222afec6).

### Your Example Website or App

https://playground.solidjs.com/anonymous/e10f7994-8487-4e12-b8b1-8830222afec6

### Steps to Reproduce the Bug or Issue

**Current behavior:** The component gets mounted `n` times if the `<For />` component is called `n` times when using the same array but rendering different item properties.

```tsx
<>
       <For each={props.elements}>
          {(item) => item.text
      </For>
      {//--------------------------}
      {//--------------------------}
      <For each={props.elements}>
          // Here children is mounted twice because For 
          // is called 2 times with the same array
          {(item) => item.children}
      </For>
</>
```

### Expected behavior

**Expected behavior:** The component must be mounted 1 time no matters how many times is called the `<For />` component when using the same array but rendering different item properties.

### Platform

- OS: macOS Monterrey
- Browser: Chrome
- SolidJS Version: 1.6.10

**Comment by webblocksapp** [comment]
I found this solution to only affect the reusable component. I'm seeing that in solid is problematic consuming directly props. Always there is a hidden edge case with JSX. Most of them are needed to wrap props in a signal.

https://playground.solidjs.com/anonymous/6950ed75-587a-4161-82a9-d4ca20deb197

I think Solid docs must add a chapter related to its particular JSX behavior and best practices,
despite Solid uses JSX, it behaves differently.

However, I keep the thread open if there could be any solution from the Solid transpiler.

**Comment by ryansolid** [comment]
Yeah this isn't something that is very much by design. `<Comp1 />` is roughly the same as `Comp1()` so it will render each time it is access via props and more over it generally needs to be lazy to ensure proper context. Ie we need to access it lazily under the right part of the DOM. 

The only ways to address this would be change the nature of Solid's JSX not to just be function calls and elements. Ie this would no longer be true:
```tsx
const div: HTMLDivElement = <div />
```

Generally speaking Solid doesn't have JSX elements, so if you want to pass around the ability to create them you can use a function. Honestly, this is something I think about a lot so I wouldn't count out that possibility, but it also be a significant change.

I agree some more thought could be put towards docs here. It's tricky because we are very clear about the behavior and the way we teach about what Solid does explains it. The challenge is that the repercussions aren't necessarily obvious to follow. This suggests more guides/best practices being necessary.
