### ISSUE TITLE
HTML entities not being parsed when attribute value is not literal

### ISSUE THREAD

**Issue by viridia** [solidjs/solid#1553]
### Describe the bug

I'm working on migrating my code from React to Solid, and I have a text input field whose "placeholder" attribute is `"Search&hellip;"`. In React, this renders as `"Search..."`, but in Solid it renders as `"Search&hellip;"`.

This works correctly if I use a string literal on the input element, but it does not work if I pass the placeholder in as a variable.

Specifically:

```ts
<input type="text" onClick={increment} placeholder="Search&hellip;" /> // Works
<input type="text" onClick={increment} placeholder={"Search&hellip;"} /> // Does not
```

### Your Example Website or App

https://playground.solidjs.com/anonymous/168ced71-f7ef-4f6e-943b-9450b3b1d015

### Steps to Reproduce the Bug or Issue

Set an attribute with an HTML entity in a variable and observe the result.

### Expected behavior

HTML entities should be parsed.

### Platform

all

**Comment by andersk** [comment]
Wait stop, this is not a bug!

`placeholder="Search&hellip;"` is HTML syntax that sets the `placeholder` attribute to the 7-character string `Search…`. It’s very important that the browser decodes HTML entities here, because that allows you to include a literal double-quote in a quoted attribute as `placeholder="&quot;"`.

`placeholder={"Search&hellip;"}` is JavaScript syntax that passes the 14-character string `Search&hellip;`. It’s very important that HTML entities are *not* decoded here, because a JavaScript string is just a string and not HTML syntax. It can already represent every string value (e.g. `placeholder={"\""}`), and must be consistent with `placeholder={str}` where `str` happens to have the string value `Search&hellip;`.

I don’t know how you determined React’s behavior, but [my test](https://codesandbox.io/s/react-attribute-escaping-test-d3j5j7?file=/index.js:124-133) indicates that it agrees with Solid 1.6.11: `Search…` for the first and `Search&hellip;` for the second.

**Comment by viridia** [comment]
Hmmm. My original React code was different than the example I gave above - I was trying to simplify things so that the example wouldn't be too complicated.

My original code looked like this:

```tsx
<TextInput placeholder="Search&hellip;" />
```

Where `TextInput` was a component that internally rendered an `input` element, and the "placeholder" property was forwarded to it. This rendered "Search..." as expected.

Maybe React was parsing the literal string on the outer component JSX? In other words, it was happening at a level above.

**Comment by andersk** [comment]
Okay yes, *that* is a bug.

```tsx
import { render } from "solid-js/web";

function TextInput(props: { placeholder: string }) {
  return <input type="text" placeholder={props.placeholder} />;
}

function App() {
  return <TextInput placeholder="Search&hellip;" />;
}

render(() => <App />, document.getElementById("app")!);
```

[Solid](https://playground.solidjs.com/anonymous/c61fed72-892a-4801-9de5-c466009179ef) incorrectly gives `Search&hellip;`; [React](https://codesandbox.io/s/react-attribute-escaping-test-2-sgudzv) gives `Search…`.

**Comment by ryansolid** [comment]
Hmm... I wasn't aware strings were treated differently in React's JSX. Since in Solid 1 & 2 are treated identical as we hoist into the template via static analysis if we can. Ie it gets cloned as part of the node.. I thought it made sense to do so. But if these are expected to be treated different we can do that.

**Comment by andersk** [comment]
The Solid compiler should still be allowed to do that optimization, as long as it applies the correct escaping and unescaping rules at each step. The only difference happens during parsing:

- When parsing JSX, an attribute value without `{}` should be unescaped as HTML, and an attribute value inside `{}` should be parsed as JavaScript without HTML unescaping. (Babel already takes care of these details.)
- When serializing constants hoisted into a template as HTML, they should all be escaped as HTML.

**Comment by andersk** [comment]
I think I’ve found the Babel footgun that led to the original bug. A `StringLiteral` node that came from the `value` of a `JSXAttribute` node remembers its original serialization as HTML, and uses that same serialization even when it’s reserialized as JavaScript. The solution is to construct a fresh `StringLiteral` node with the same string.

```js
import { parse } from "@babel/parser";
import * as t from "@babel/types";
import { CodeGenerator } from "@babel/generator";

const code = '<input placeholder="Search&hellip;" />';
let ast = parse(code, { plugins: ["jsx"] });

// Extract the StringLiteral node for the placeholder attribute value.
let value = ast.program.body[0].expression.openingElement.attributes[0].value;

console.log(value);
// Node {
//   type: 'StringLiteral',
//   start: 19,
//   end: 35,
//   loc: SourceLocation {
//     start: Position { line: 1, column: 19, index: 19 },
//     end: Position { line: 1, column: 35, index: 35 },
//     filename: undefined,
//     identifierName: undefined
//   },
//   extra: { rawValue: 'Search…', raw: '"Search&hellip;"' },
//   value: 'Search…'
// }

// It has the correct string:
console.log(value.value);
// Search…

// But Babel remembers its original serialization, which was for HTML,
// not for JavaScript!
ast = t.objectExpression([
  t.objectProperty(t.stringLiteral("placeholder"), value),
]);
console.log(new CodeGenerator(ast).generate().code);
// {
//   "placeholder": "Search&hellip;"
// }

// Build a fresh StringLiteral with the same string:
value = t.stringLiteral(value.value);

console.log(value);
// { type: 'StringLiteral', value: 'Search…' }

console.log(value.value);
// Search…

// Now it serializes correctly for JavaScript.
ast = t.objectExpression([
  t.objectProperty(t.stringLiteral("placeholder"), value),
]);
console.log(new CodeGenerator(ast).generate().code);
// {
//   "placeholder": "Search\u2026"
// }
```
