### ISSUE TITLE
props.children displays a stale item when used in an HTML literal template

### ISSUE THREAD

**Issue by chvelkov** [solidjs/solid#1567]
### Describe the bug

The demo has two identical parent components - one uses JSX, the other html literal template.
Both of them have a <Dynamic> child. The problem is that the parent using html literal shows a stale item.
Just click a few times between the **Child1** and **Child2** buttons to toggle the component used in <Dynamic> and you'll see it.

### Your Example Website or App

https://playground.solidjs.com/anonymous/32190134-5f35-4e56-98c5-be42f5044509

### Steps to Reproduce the Bug or Issue

Click on Child1 and then on Child2. Notice that there are now two children in the parent using the HTML literal template.

### Expected behavior

The JSX and the html literal template should have the same behavior

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by branlok** [comment]
Hello chvelkov,

If you make the following correction, you'll get the behaviour that you were expecting. 

```diff
const OuterHTML = (props) => {
  return html`<div>
      <div>HTML wrapper (not working correctly)</div>
-      <div style="background-color: red">${() => props.children}</div>
+      <div style="background-color: red"><${() => props.children}/></div>
    </div>`;
};
```

Essentially the Child1 and Child2 you passed into your wrappers are still JSX components.

The rule to insert them in the html`` must be wrapped with angle brackets like so `<${props.children}/>`

Since you contained those component as a signal. To track them in html``, you have to wrap it in another function, which you've already done. So the final shape becomes `<${() => props.children}/>`
 
 You can find more info here [solid/html docs](https://github.com/solidjs/solid/tree/main/packages/solid/html)

**Comment by chvelkov** [comment]
[branlok](https://github.com/branlok), got it, thank you!

I'm wondering, if there's a way for Solid to warn about this and similar cases or to even throw an error, if it something is being improperly used. In this particular case it looks like it's working without angle brackets, until it's used in combination with <Dynamic> like in the demo and then we get this completely unexpected behavior.

**Comment by ryansolid** [comment]
Yeah I wouldn't expect to need angle brackets here at quick look. Dynamic resolves Component definitions into specific instances. At which point the property access should generate it. Dynamic itself returns a Memo which is a function but inserting it should be able to handle that I would think.
