### ISSUE TITLE
Async results do not update state when SSR+Streaming

### ISSUE THREAD

**Issue by gxxcastillo** [solidjs/solid#1587]
### Describe the bug

My local state object, created with `createStore()` is not being updated consistently when async content is streamed to the client.

Note, the issue is only present if content is streamed, normal SSR will not have the issue.

(More details in the readme of the example repo).

### Your Example Website or App

https://github.com/gxxcastillo/bugref-solidjs-state

### Steps to Reproduce the Bug or Issue

1. pnpm install
2. pnpm build
3. pnpm start
4. Wait a few seconds for the stream to resolve
5. Note the input fields are updated with the results of the api call, but the "Hello ..." and "Your id is ..." text is not updated.
6. Note typing in any of the input fields updates "Hello ..." and "Your id is ...".

### Expected behavior

As a user I expect all places that reference `state` to be updated when `setState()` is called.  Instead, only some places are updated.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by gbj** [comment]
I think in part this is because you are not actually reading from the resource under the `<Suspense/>`. Effects don't run on the server at all, so the replacement `<Suspense/>` fragment that streams down from the server is rendered with `...`. But if you read from the resource under the `<Suspense/>`, it works exactly as you'd expect
```jsx
<header>
  <h1>Hello {data()?.first} {data()?.last}!</h1>
  <p>Your id is {data()?.id}</p>
</header>
```

Now you're left with the slightly different question of how you want to coordinate your local updates with that resource that you've loaded. I'd personally probably rewrite what you had by using an `undefined` initial value and deriving each field from the combination of the resource and the state.

```jsx
export function User() {
  const [data] = createResource(mockData, callApi);
  const [state, setState] = createStore(undefined);
  const first = () => state?.first || data()?.first;
  const last = () => state?.last || data()?.last;
  const id = () => state?.id || data()?.id;

  return (
    <div class={styles.User}>
        <p>The following values should first render with initialValue and then render with the results of `callApi()`</p>
      <Suspense fallback={() => 'loading...'}>
          <div class={styles.App}>
            <header>
              <h1>Hello {first()} {last()}!</h1>
              <p>Your id is {id()}</p>
            </header>

            <form>
              <input placeholder='first' value={first()} onInput={(event) => setState('first', event.currentTarget.value)}/>
              <input placeholder='last' value={last()}  onInput={(event) => setState('last', event.currentTarget.value)}/>
              <input placeholder='id' value={id()}  onInput={(event) => setState('id', event.currentTarget.value)}/>
            </form>
          </div>
         // ...
```

This seems to work exactly as you're intending, but YMMV.

**Comment by gxxcastillo** [comment]
Thanks @gbj. I think your solution provides a workaround but I don't see how it addresses the issue of `state` not getting updated correctly?  I grant that the example I provide is contrived but nonetheless, I would expect `state` would always render the correct value so long as it's within the same JSX function, otherwise, how could there be a single source of truth when it comes to the current state? 

For example, why does this render one value upon the resolution of the callApi promise:
```
<h1>Hello {state.first} ...
```

and this render another?
```
<input placeholder='first' value={state.first} ... />
```

**Comment by ryansolid** [comment]
I haven't had a chance to look into this but do keep in mind on the server there is no reactivity. Only resources triggering Suspense boundary updates. In so it is possible when not using resource reads etc, for things to get out of sync. This might seem restrictive in a sense, but we also can't control what happens outside of Suspense boundaries because of the timing of Streaming. The parent could already be flushed. So we can't do like reactivity up type scenarios. I'm not saying that is what is going on here, but if deriving from resources solves the problem, it is likely a variation on that.

**Comment by ryansolid** [comment]
Ok I have the answer to your question. It's a hydration quirk. Basically, it does only send the initial server data in your original code. This means the client assumes the server matches it and doesn't update it as it already has the updated value at the time it hydrates. For inserts, we know how to skip it, for attributes we set it again which should not matter since it is already the same value. This may be optimized away in the future but we shouldn't depend on this behavior. It just so happens that the bug reveals this behavior.

Interestingly this is one of the few places that doesn't trigger a hydration warning in dev since we tend to not read from the DOM to compare values and the structure was unchanged. I will think about this. But as far as I can see there is no other action to take at this time.

**Comment by gxxcastillo** [comment]
@ryansolid, the fact that the state object has one value and the client is rendering a different value should be a bug, no?  Or, is there a different approach that should be used to update state and expect it to be updated everywhere that it's being tracked?

For example, here's one other thing that doesn't seem right in this scenario: upon entering a value into any of the inputs, the UI immediately goes from showing the initial value ("...") to showing the actual string that is in the object after the api call resolved ("Yimmy" in the case of the "first" field) + the new value that was just entered.  This tells me the UI is tracking the state, because it knows the current value is "Yimmy" but it's just not rendering it.

Ex of what is getting rendered at each of the stages:

initial render:
```
first: "..."
last: "..."
id: "..."
```

upon api call resolution:
```
first: "..."
last: "..."
id: "..."
```

upon entering "TTT" into the "first" input:
```
first: "YimmyTTT"
last: "..."
id: "..."
```

**Comment by ryansolid** [comment]
It's basically a hydration error that we probably should find a way to warn in dev, but it doesn't raise flags right now because we don't read the DOM generally in libraries like this.

Because as far as the client can tell at hydration time upon API resolution it should be the updated values. So it doesn't touch the DOM but thinks that first is. The append is interesting though. Because if the value is coming from the event and being replaced then how does it contain the old value to append. Mind you if Gregs example works I'd go along that route, because we are basically trying to debug a situation that shouldn't exist in the first place.

**Comment by gxxcastillo** [comment]
> Mind you if Gregs example works I'd go along that route

I ran into this issue while building out an evaluation demo for my team and I'm pushing back on Greg's solution and the closing out of this issue because it implies that we cannot rely on canonical state objects. My concern is that it would be prohibitive to maintain an application where the UI can not be relied on to stay in sync with canonical state objects.

>  because we are basically trying to debug a situation that shouldn't exist in the first place.

Maybe this is where I'm missing something, can you explain more of what you mean? What's the situation that shouldn't exist?

**Comment by gbj** [comment]
I won't pretend to speak for Ryan, and I'm not a Solid expert by any means, so take this with a grain of salt.

From my perspective, your example breaks two rules/guidelines/best practices:
1. Don't use effects to synchronize state within the reactive system. i.e., don't write to a store from inside an effect. Instead, derive what can be derived. (This is what my solution did, deriving the correct current value from the async resource loaded from the server and from your local store; I wouldn't call it a workaround but if what you want is a global state store, I can understand why you would see it that way.)
2. `<Suspense/>` is triggered by reading resources under it. The only reason your `<Suspense/>` does *anything* in the example is the total incidental resource read you do at the very end of line 70. If you remove this I'm pretty sure the suspense just resolves immediately, because you're accessing the value of the store but not reading the value of the resource under it.

As Ryan said, effects don't run on the server, so when you write into a store from an effect like this you're creating a mismatch between the server's understanding of the state and the client's. When it resolves the suspense fragment, the server reads from the *original* store value because the effect setting the store to the resource's value has not run. However, the client assumes that the server is sending the correct HTML and so it does not need to update anything.

I don't know if "you're holding it wrong" is ever really a helpful answer, and you may be right that the framework should notice this or do something about it, but your example was unidiomatic code that produced a bug, whereas the (I think) more idiomatic solution does not.

**Comment by gxxcastillo** [comment]
Thanks for helping to flush that out a bit more @gbj 🙏
