### ISSUE TITLE
After version 1.6.13 (DOM expressions 0.35.19), hydration markers like <!> are showing up in fragments

### ISSUE THREAD

**Issue by CalLavicka** [solidjs/solid#1651]
### Describe the bug

After [this](https://github.com/ryansolid/dom-expressions/commit/0856f45269fa898145164d7170c0d6b4cf6c3003) change to DOM expressions, any fragments with dynamic data are being separated by `<!>` when compiling with hydration turned on. This means that processing of that fragment via (for example) the `children` helper will pick up those text elements. This is a breaking change from earlier versions of solid, and is an inconsistency when compiling with hydration vs. without.

For example,
```javascript
<>
  {props.string1}
  {props.string2}
</>
```
Will produce an array of `[string1, '<!>', string2]` with hydration turned on when read externally. When hydration is turned off (or on earlier versions), it would be `[string1, string2]`

### Your Example Website or App

https://playground.solidjs.com/anonymous/c949a993-8db4-4fe8-9180-9959b8d330b8

### Steps to Reproduce the Bug or Issue

1. Go to the link above
2. Open up code output and toggle between client side and client side with hydration
3. See how the `<!>` string gets added to the array.

The playground can't run the hydration code, but if you do it locally it will log it out as a child. You can also copy the hydration output into the left side and run it and see the marker get logged out.

### Expected behavior

We could fix the `children` helper to handle these markers just like insert does, but it would still be a breaking change from before and between hydration / non-hydration if you don't use the children helper. I would just expect these markers to not appear in the fragment's array at all.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 111

**Comment by ryansolid** [comment]
I agree. I thought the solution was good but it was flawed. I have a better fix in 1.7 which handles at insertion into the DOM time instead of at compilation time. I realized that Components were skipped. But I didn't consider impact on fragments that would be passed through to other components.

That being said markers are necessary otherwise hydration is broken a different way, adjacent text nodes were getting merged and messing up mapping in the browser. 

Not too sure to do about 1.6 at this point. I could try to backport the specific fix.
