### ISSUE TITLE
[Firefox] Render into iframe.contentDocument has bad behavior

### ISSUE THREAD

**Issue by ricochet1k** [solidjs/solid#1688]
### Describe the bug

Long story short, it seems that memoized tags are somehow broken when rendering directly into an iframe. It works on initial render, but once a signal updates something they become stringified, displaying as `[object Text][object HTMLDivElement]` etc.

Just a guess, but Is it possible there's an `instanceof Element` somewhere? My understanding is that iframes have different instances of a lot of the common root classes so instanceof won't work as expected across the iframe boundary

### Your Example Website or App

https://playground.solidjs.com/anonymous/1015507a-acb2-487a-b382-965a543a210f

### Steps to Reproduce the Bug or Issue

- Open https://playground.solidjs.com/anonymous/1015507a-acb2-487a-b382-965a543a210f
- Watch how the initial render looks okay, then after the Interval they switch to `[object Text][object HTMLDivElement]` even though it was only count that changed

### Expected behavior

It should work like it normally does when not rendered into an iframe.

### Platform

- OS: macOS
- Browser: Firefox
- Version: 111.0.1

**Comment by ryansolid** [comment]
Ah I see. Yeah this issue only appears in Firefox and isn't present in Chrome, Edge, or Safari. The renderer does check if it is an `instanceof Node` (https://github.com/ryansolid/dom-expressions/blob/21fdba5bcab25986a2b93003aaace100b2231cdc/packages/dom-expressions/src/client.js#L449).

I'm gathering the fix is to check against `item.ownerDocument.defaultView.Node`. Alright.
