### ISSUE TITLE
typescript fetchpriority in image

### ISSUE THREAD

**Issue by LuisCoderDev** [solidjs/solid#1690]
### Describe the bug

In a webpage sometimes you have a large contenful paint with images, when this happend you dont want to use loading lazy property in your image instead you want to use fetchpriority

### Your Example Website or App

https://github.com/LuisCoderDev/solid_image

### Steps to Reproduce the Bug or Issue

Run the proyect and see the error type in the img tag

`Property 'fetchpriority' does not exist on type 'ImgHTMLAttributes'`

### Expected behavior

img should have the posibility to add `fetchpriority='high'` 

i found more info [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/fetchPriority) in the mdn docs maded by mozilla

### Platform

- OS: Windows
- Browser: Opera
- Version: 1.7.3

**Comment by snnsnn** [comment]
I was going to open a PR but it seem it is already added:

https://github.com/ryansolid/dom-expressions/blob/1d04cc14bbde62e06d852eac9e85252359c6b304/packages/dom-expressions/src/jsx.d.ts#L860

By this PR https://github.com/ryansolid/dom-expressions/pull/237

But not merged because of this error: https://github.com/ryansolid/dom-expressions/actions/runs/4694305232/jobs/8322332238

**Comment by LuisCoderDev** [comment]
any update ?
