### ISSUE TITLE
createResource doesn't rerun fetcher on signal changes with equals: false

### ISSUE THREAD

**Issue by ghinda** [solidjs/solid#1692]
### Describe the bug

`createResource` doesn't rerun the fetcher on signal updates with the same value, when the signal is using `equals: false`.
It basically operates as if `equals` was not specified.

This seems to be a newer issue, as it used to work on older versions - can't tell exactly when it broke.

### Your Example Website or App

https://playground.solidjs.com/anonymous/cb608af9-02df-4960-840f-3e107e4b6c37

### Steps to Reproduce the Bug or Issue

Press the button in the demo multiple times.

### Expected behavior

The resource's fetch should run on each button press.

### Platform

- OS: Linux
- Browser: Chromium
- Version: 112

**Comment by ryansolid** [comment]
We started using a `createMemo` wrapper on the source so that we would execute it randomly outside of the expected context and minimize over-execution where we internally grabbed the value. I have to admit it seems unlikely we change this back nor do I see this really a configurable thing. The source is basically the identity of the resource and there are other ways to retrigger it.

I do see why one might think that this would work though. It is interesting in general with equals false not being the default most composition will lose it very quickly but I can see desire for flexibility in base primitives. It is just not a place I'd see giving it. Resource API is under review so we will give it some thought.

**Comment by ghinda** [comment]
It does make sense for the source to be "the identity of the resource". I'm basically piggybacking on resource for `loading` and `error`, so not really the intended use case.

The `createMemo` source wrap does make it a bit more difficult to have a resource that:
- Doesn't fetch when initialized
- Can be refetched manually at any time, even with the same source value

I'm going to rely on `info.refetching` as workaround.
I understand your reasoning, so closing this.
