### ISSUE TITLE
Accessing children prop outside of JSX triggers hydration warning

### ISSUE THREAD

**Issue by marbemac** [solidjs/solid#1729]
### Describe the bug

Per title - receive hydration warnings when accessing the children prop in any way (besides rendering props.children of course) in SSR context.

```tsx
export const Stack: ParentComponent = (props) => {
  // Accessing children in any way (even just a console.log) causes hydration warning
  console.log(props.children);

  return props.children;
};
```

For context, I came across this while trying to create a "stack" component that injects a divider element between children (simplified below):

```tsx
export const Stack: ParentComponent = (props) => {
  return (
    <For each={Array.isArray(props.children) ? props.children : [props.children]}>
      {(c, i) => {
        return (
          <>
            {/* add a divider */}
            {i > 0 ? <hr /> : null}
            
            {c}
          </>
        )
      }}
    </For>
  );
};
```

### Your Example Website or App

https://stackblitz.com/github/marbemac/solid-streaming-lazy-bug/tree/children-bug

### Steps to Reproduce the Bug or Issue

1. Go to https://stackblitz.com/github/marbemac/solid-streaming-lazy-bug/tree/children-bug
2. Click on "open in new tab" in the top right
3. Open dev tools to see the hydration warnings in the console

### Expected behavior

No hydration warning.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 1.7.5

**Comment by ryansolid** [comment]
If you are accessing `children` outside of a single location and for retrospection you should use the the `children` helper. Each lazy access recreates them and there are cases where that messes up hydration id matching. This issue is similar to this: https://github.com/solidjs/solid/issues/1485

In general you don't want to access props.children multiple times if you can avoid it SSR aside, but this accents it. A tradeoff of having things directly return the DOM elements.

For your specific case `children` has a `toArray` helper which I'm realizing isn't documented. 

```js
const c = children(() => props.children)
return (
    <For each={c.toArray()}>
      {(c, i) => 
        <>
          {/* add a divider */}
          {i() > 0 ? <hr /> : null}
          {c}
        </>
      }
    </For>
  );
```

I've opened an issue: https://github.com/solidjs/solid-docs/issues/257

The rest of docs for children are here: https://www.solidjs.com/docs/latest/api#children

**Comment by marbemac** [comment]
Ah yes I have played around with `children()` (and the `toArray` helper). After digging into it a bit more, turns out the issue was a bit more specific, and of course that "one extra bit of functionality" seems to be the culprit 😅. I'm allowing the consumer to optionally customize the divider, which introduces an extra conditional. This extra conditional seems to cause the hydration warning, but only sometimes.

```tsx
interface StackProps {
  divider?: true | ValidComponent;
  children: JSX.Element;
}

const Stack = (props: StackProps) => {
  const c = children(() => props.children).toArray();

  return (
    <For each={c}>
      {(c, i) => (
        <>
          {/* optionally add a divider. default to <hr> w option to render custom component */}
          {i() > 0 && props.divider ? (
            props.divider === true ? (
              <hr />
            ) : (
              props.divider
            )
          ) : null}
          
          {c}
        </>
      )}
    </For>
  );
};
```

### Usage

**This works just fine! No hydration error, renders with the custom divider, etc:**

```tsx
const CustomDivider = () => {
  return "---";
};

<Stack divider={CustomDivider}>
  <div>one</div>
  <div>two</div>
</Stack>
```

**This results in a hydration error:**

```tsx
<Stack divider>
  <div>one</div>
  <div>two</div>
</Stack>
```

---

Honestly at this point since it's so specific I can probably just remove the feature that allows for a custom divider to be supplied (thus removing the extra `?` conditional that seems to be causing an issue), so it's not a big deal. Reporting though in case this is a symptom of some other bug..

**Comment by marbemac** [comment]
Ok a weird twist - the hydration warning goes away if adjusted to use `Show`:

```tsx
const Stack = (props: StackProps) => {
  const c = children(() => props.children).toArray();

  return (
    <For each={c}>
      {(c, i) => (
        <>
          {/* optionally add a divider. default to <hr> w option to render custom component */}
          <Show when={i() > 0 && props.divider}>
            {props.divider === true ? <hr /> : props.divider}
          </Show>

          {c}
        </>
      )}
    </For>
  );
};
```

**Comment by ryansolid** [comment]
Hmm... well props.divider is potentially JSX too right.. It probably should to be wrapped in `children` when it is a custom option as you are accessing it multiple times. Why Show works is interesting. Ternary compilation does differ and it must be impacting element creation in a specific way. 

I think what we are seeing is a combination of a couple things that usually don't happen/happen together. I think the answer here is to use `children` on `props.divider` but it may be worth looking at ternary execution. Honestly I think ultimately this is related to the issue I talked about in my previous response. Since I have a better answer there I will continue to track that there and close out this one. I'm glad you have a working solution.

**Comment by marbemac** [comment]
No problem, working for now - thanks @ryansolid!
