### ISSUE TITLE
Error when creating a new memo, using the createMemo function

### ISSUE THREAD

**Issue by szagi3891** [solidjs/solid#1747]
### Describe the bug

When I click on the "Create new counter" button, a message appears in the browser console: "computations created outside a `createRoot` or `render` will never be disposed".

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

```
import styles from './App.module.css';
import { Accessor, Setter, createMemo, createSignal } from 'solid-js';

export class Value<T> {
    public readonly get: Accessor<T>;
    public readonly set: Setter<T>;

    constructor(initValue: T) {
        const [get, set] = createSignal(initValue);
        this.get = get;
        this.set = set;
    }
}


class Counter {
  readonly counter = new Value(0);

  readonly odd = createMemo((): boolean => {
    return this.counter.get() % 2 === 0;
  });
}

const bounterBox = new Value(new Counter());

const createNewCounter = () => {
  bounterBox.set(new Counter());
};

const up = () => {
  const counter = bounterBox.get().counter;
  counter.set(counter.get() + 1);
};

function App() {
  const aa = bounterBox.get();
  const aa2 = aa.odd;

  return (
    <div class={styles.App}>
      <div>Counter = {bounterBox.get().counter.get()}</div>
      <div>Odd = {bounterBox.get().odd() }</div>
      <div onClick={up}>up</div>
      <div onClick={createNewCounter}>Create new counter</div>
    </div>
  );
}

export default App;

```

### Expected behavior

I would expect the new memo to be created without any problems

### Platform

- OS: macOS
- Browser: Chrome
- Version: solid-js: 1.6.10

**Comment by szagi3891** [comment]
This is bad news. For me, this feature of solid-js does not allow me to use it. I use react + mobx. There I can create such constructions without any problems.

@ryansolid - Or have you thought about improving the signals ? The solidjs itself is impressive, but the flaw above may put many people off solidjs

**Comment by thetarnav** [comment]
The memo created inside `Counter` here does not have an owner computation so it won't ever be disposed by the owner structure.
It's fine to have global memos, effects, etc. but solid will give you a warning as creating computations outside of reactive owners (e.g. in event-handlers, or after setTimeout) is a common mistake that can silently cause bugs or memory leaks in your app.
You can wrap any global computation with `createRoot` to get rid if the error. It will have the same exact behavior, but you'll make the ownership more explicit.
```ts
const bounterBox = createRoot(() => new Value(new Counter()))
```

**Comment by snnsnn** [comment]
> @ryansolid - Or have you thought about improving the signals ? The solidjs itself is impressive, but the flaw above may put many people off solidjs

It has nothing to do with signals and there is no limitation where you can use an effect, also you don't get an error but a warning against possible memory leak.

In React we maually manage an effect's dependencies by passing an array and again manually clean up resources by returning a clean up function from the effect. Solid does both of them for you automatically. In order to run the auto cleanup logic you need to access those values in a scope in which they can be tracked. Those auto tracking scopes are created inside runWithOwner callbacks. `render` or `createRoot` functions use runWithOwner internally.

So there is no flow but an API around a design pattern (disposable).

You can read more about it here: https://stackoverflow.com/a/76030785/7134134

**Comment by ryansolid** [comment]
MobX does have self-disposing computeds which is one of the features we're looking at for 2.0. Ultimately there will be a sink which does need disposal though albeit effects or autorun etcc and that is what Solid's roots do. Solid is setup to automatically handle this as it is optimized for hierarchical structures whereas say MobX you have to do manual disposal. This was an intentional design decision. I would like to make Memos completely lazy but in the meanwhile this is by design. Thanks for comments on this issue.

**Comment by szagi3891** [comment]
I think I understand.  It seems to me that this design decision is dictated by the nature of javascript itself. What javascript lacks is a "destructor". 

Something similar in javascript would be useful:
https://doc.rust-lang.org/std/ops/trait.Drop.html

**Comment by szagi3891** [comment]
@ryansolid 

Perhaps it is worth utilizing this mechanism?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry

Subscriptions can be attached to DOM elements. When all references to the DOM element disappear, the currently attached subscriptions would be cleaned up.

**Comment by szagi3891** [comment]
https://v8.dev/features/weak-references
