### ISSUE TITLE
`Setter<bigint>` should not be assignable to `Setter<number>` and vice versa

### ISSUE THREAD

**Issue by erhant** [solidjs/solid#1818]
### Describe the bug

`Setter<number>` is assignable to `Setter<bigint>`. `Accessor<number>` is not assignable to `Accessor<bigint>`.

The same goes for the opposite case: `Setter<bigint>` is assignable to `Setter<number>`. `Accessor<bigint>` is not assignable to `Accessor<number>`.

The type error should be there for `Setter` too, just like it is for `Accessor`.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-6dfgbm?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

- Open stackblitz as given above.
- Once packages are installed, you will see the type error for `Accessor` but not for `Setter`.

### Expected behavior

`Setter<number>` should not be assignable to `Setter<bigint>`.

### Platform

- OS: macOS
- Browser: Brave (Chrome)
- Version: see below
```json
  "devDependencies": {
    "typescript": "^5.1.3",
    "vite": "^4.3.9",
    "vite-plugin-solid": "^2.7.0"
  },
  "dependencies": {
    "solid-js": "^1.7.6"
  }
```

**Comment by otonashixav** [comment]
This isn't specific to `number` and `bigint`, in fact any function with one generic type that returns that type, with compatible args is assignable to any `Setter`: [example](https://playground.solidjs.com/anonymous/5959e12b-19be-43f4-b20f-c70a2243ec6d). See https://github.com/microsoft/TypeScript/issues/50050.

It might be reasonable to remove the generic from `Setter` to solve this, and no longer narrow its return type to that specified by its parameters. **This would break code which expects `set(v)` to return the type of `v` rather than the type of the signal**, which was the intent of the initial change https://github.com/solidjs/solid/commit/851bd63202d6e9eb6907c77a26ac323ce728d206.

https://playground.solidjs.com/anonymous/b5d0dba5-83ca-4bbe-bbfd-8d268e0dfc9f is what this could look like with the existing type test cases.

**Comment by ryansolid** [comment]
I don't know if this is reasonable do. @otonashixav I trust your opinion on this. If the current types are what make the most sense we can close this as known given how TS works. Otherwise we can revisit it. But I admit I don't think I quite get the subtleties. The desire for the Setter to not use the type of Signal was just to make it more specific? Also @Jager567 if you have any opinions.

**Comment by erhant** [comment]
Thanks for the detailed explanations. I haven't used Solid enough to make more comments on this subject now that there seems to be a bit more depth to why it was designed this way, so I'm leaving this to your hands.

**Comment by otonashixav** [comment]
Okay weirdly I managed to fix? this only slightly changing the current type. So honestly I have no idea what's going on, potentially typescript is inferring variance differently due to the change.
