### ISSUE TITLE
Solid-start incompatible with ag-grid-solid: The requested module 'solid-js/web' does not provide an export named 'className'

### ISSUE THREAD

**Issue by xarthurx** [solidjs/solid#1839]
### Describe the bug

Trying to use AgGrid inside solidjs by:
```
import  AgGridSolid  from "ag-grid-solid";
```

When refreshing my `customModule.jsx`, the main webpage shows the error.

### Your Example Website or App

https://github.com/xarthurx/soildStartTest

### Steps to Reproduce the Bug or Issue

- `npm init solid@latest`
- `npm install ag-grid-solid`
- `npm run dev` to start the engine -- everything works correctly
- add `import  AgGridSolid  from "ag-grid-solid";` to `src/routes/index.jsx`
- got the errror:
![image](https://github.com/solidjs/solid/assets/1921878/6dcbe131-0c94-48e6-9a59-889ca1362ca4)

### Expected behavior

Everything should be imported correctly.

### Platform

- OS: Windows
- Browser: Chrome
- Version: newest

### Additional context

When using 
```
npx degit solidjs/templates/ts my-app
```

to initialize the project and do the same test, there seems no issue.
So I guess this might be an issue related to `solid-start`, not `solid`.

**Comment by ryansolid** [comment]
Yeah this is just because the AGGrid package hasn't been set up for SSR. Like if you turn ssr: false in your SolidStart options it would work.

I don't know if AG-Grid has browser-specific dependencies that would require it to be loading only there but I suspect it might. But in anycase in the current state it is packaged in a way that will work in SSR.

To do so it would have to have a "solid" export that would point at the source code so we could compile it for ssr mode as both the client and server builds would be different than what is packaged there. And example package that shows how to bundle this is https://github.com/solidjs-community/rollup-preset-solid.

If your desire is for it to render on the server your best bet is to request them to support SSR (not sure if they do). If the desire is to have it not render during server side in a SSR setup there are some patterns for doing that in SolidStart and some features we are working on to lazy load it only into the client.

**Comment by xarthurx** [comment]
> Yeah this is just because the AGGrid package hasn't been set up for SSR. Like if you turn ssr: false in your SolidStart options it would work.
> 
> I don't know if AG-Grid has browser-specific dependencies that would require it to be loading only there but I suspect it might. But in anycase in the current state it is packaged in a way that will work in SSR.
> 
> To do so it would have to have a "solid" export that would point at the source code so we could compile it for ssr mode as both the client and server builds would be different than what is packaged there. And example package that shows how to bundle this is https://github.com/solidjs-community/rollup-preset-solid.
> 
> If your desire is for it to render on the server your best bet is to request them to support SSR (not sure if they do). If the desire is to have it not render during server side in a SSR setup there are some patterns for doing that in SolidStart and some features we are working on to lazy load it only into the client.

Thank you for the reply.
I'm actually a bit new to solid and totally new to SolidStart. 
Silly question... where can I turn the option "ssr:false" off? I browsed the doc, but don't see a setting file...

**Comment by xarthurx** [comment]
Ah, never mind.
I created a new repo with the guild, and found out:
![image](https://github.com/solidjs/solid/assets/1921878/569a0292-81a5-4013-a1e2-79f47f1e7ed5)

**Comment by xarthurx** [comment]
> Yeah this is just because the AGGrid package hasn't been set up for SSR. Like if you turn ssr: false in your SolidStart options it would work.
> 
> I don't know if AG-Grid has browser-specific dependencies that would require it to be loading only there but I suspect it might. But in anycase in the current state it is packaged in a way that will work in SSR.
> 
> To do so it would have to have a "solid" export that would point at the source code so we could compile it for ssr mode as both the client and server builds would be different than what is packaged there. And example package that shows how to bundle this is https://github.com/solidjs-community/rollup-preset-solid.
> 
> If your desire is for it to render on the server your best bet is to request them to support SSR (not sure if they do). If the desire is to have it not render during server side in a SSR setup there are some patterns for doing that in SolidStart and some features we are working on to lazy load it only into the client.

FYI, ag-grid developer said they will not support ssr:
https://github.com/ag-grid/ag-grid/issues/6929

**Comment by xarthurx** [comment]
There's another questions related to this issue:

```
 version  0.2.26
 adapter  static
file:///C:/Users/xar/source/docRepo/ddmRemake/node_modules/solid-start-static/index.js:26
      if(!config?.solidOptions?.ssr) throw new Error('solid-start-static needs ssr to be enabled for pre-rendering routes at build time');
``` 

When I build the site to a static site, I got the above error...

Does it mean that with `ssr` disabled, I cannot generate a static site?

**Comment by ryansolid** [comment]
Yeah, because static sites are server-rendered. You render all the pages on the server and then load them as you navigate to it. A client-rendered SPA is technically a static site in a sense that you don't need a server for it, but it isn't the same. A SPA will serve a single index.html that is basically blank and do everything in the client. A "static" site involves pre-rendering all the pages on the server.

If you want Static site generation with something like this we need to have it be skipped on server rendering generation and to only render that part in the client.
