### ISSUE TITLE
`Show` component guard problem

### ISSUE THREAD

**Issue by denbon05** [solidjs/solid#1840]
### Describe the bug

```ts
const Block: Component<{ block: Resource<ETHBlock> }> = (props) => {
  return (
    <Show when={props.block()}> // guard??
      <li class="list-group-item card">
        <div class="card-body d-flex justify-content-between">
          <BlockMainInfo block={props.block} />
          <div class="flex-grow-1 text-end">
            <BlockSecondaryInfo block={props.block()} />
/*                              ^^^^
Type 'Block | undefined' is not assignable to type 'Block'.
  Type 'undefined' is not assignable to type 'Block'.ts(2322)
BlockSecondaryInfo.tsx(12, 39): The expected type comes from property 'block' which is declared here on type 'IntrinsicAttributes & { block: Block; }'
*/
          </div>
        </div>
      </li>
    </Show>
  );
};

export default Block;
```

### Your Example Website or App

https://github.com/denbon05/blockexplorer

### Steps to Reproduce the Bug or Issue

Use `Show` as guard, following code doesn't know about value exists after it was checked via `Show`.

### Expected behavior

`Show` component should provide guard logic.

### Platform

- OS: Linux
- Browser: Brave, Chrome, whatever
- Version:"solid-js": "^1.7.8"

**Comment by dev-rb** [comment]
You can make use of the `keyed` prop or use type assertion using `!`

`const Block: Component<{ block: Resource<ETHBlock> }> = (props) => {
  return (
    <Show when={props.block()} keyed> // guard??
      {block => (
        <li class="list-group-item card">
          <div class="card-body d-flex justify-content-between">
            <BlockMainInfo block={props.block} />
            <div class="flex-grow-1 text-end">
              <BlockSecondaryInfo block={block} />
            </div>
          </div>
        </li>
      )}
    </Show>
  );
};

export default Block;`

**Comment by denbon05** [comment]
@dev-rb yes, with `keyed` works.  Generally, `null` assertion is not a good idea to use :/
Anyway, thanks for quick response.
Shouldn't `Show` work as a guard without additional wrapper or `null` assertion?

**Comment by dev-rb** [comment]
As far as I know, you can't type guard in the JSX tree with just elements. 

Additionally, since `block` here is a function, typescript can't infer what the return of the function will be. Even if it makes sense to us, typescript itself is not smart enough to know that the return value will not be `null`.

**Comment by ryansolid** [comment]
You don't even need keyed since Solid 1.7:

```jsx
const Block: Component<{ block: Resource<ETHBlock> }> = (props) => {
  return (
    <Show when={props.block()}>
      {block => (
        <li class="list-group-item card">
          <div class="card-body d-flex justify-content-between">
            <BlockMainInfo block={block()} />
            <div class="flex-grow-1 text-end">
              <BlockSecondaryInfo block={block()} />
            </div>
          </div>
        </li>
      )}
    </Show>
  );
};

export default Block;
```

But yeah generally JSX has no way of knowing. We don't use special Language Server features here because `<Show>` doesn't need to be `<Show>` it could be `<ConditionalLayout>`, `<Suspense>`, etc.. so this is no way for JSX to know this. In fact I don't any composable/control control flow in a template language is able to infer this on native primitives like  Svelte's `#each`. Which means once you compose you hit the same problem again.

In JavaScript all we have is native language like ternaries (or like `for`/`if` statements), so that would be the answer other than the fact that functions can't be viewed as values in TS. Like:
```js
signal() && signal().something
```
Doesn't pass type checks. Ironically Object getters lie the other way. As you can write:
```js
const state = {
  get value() { return Math.random() < 0.5 ? undefined :  { something: "hi" }}
}

state.value && state.value.something
```
And have that pass type checking.

In so all we can really do is use function guards hence why there is the callback form of `<Show>`.

If you want to hear more of the subject I talk at length in this stream as it isn't a perfect solution (Null Asserted Control flow marker) https://www.youtube.com/watch?v=2fW6JaJHoCE&t=2627s.

In any case this isn't really something we can fix. Any JSX framework has the same issue on components.. any templating system that uses generic components for control flow would too. Unfortunately for us double access of values is awkward otherwise native language would suffice. In which case all we have is function guards of null assertion. You can still write the function guards but including it in the component seemed like a better choice.
