### ISSUE TITLE
createDeferred returns `undefined` under Suspense context during transitions 

### ISSUE THREAD

**Issue by elite174** [solidjs/solid#1883]
### Describe the bug

When I do navigation between pages (using solid-router) `createDeferred` returns undefined. However, it will work fine, if it's not under Suspense component.

@ryansolid is that intended?

### Your Example Website or App

https://playground.solidjs.com/anonymous/3bd44fd8-dc61-4866-97f8-6c316742edca

### Steps to Reproduce the Bug or Issue

https://playground.solidjs.com/anonymous/3bd44fd8-dc61-4866-97f8-6c316742edca

### Expected behavior

It should return initial value

### Platform

solid 1.7.11
- OS: [Windows]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by elite174** [comment]
![image](https://github.com/solidjs/solid/assets/13636224/2d55e1ff-8399-435a-89b3-bcc96806b992)

I checked the implementation, and could this be a solution?

**Comment by ryansolid** [comment]
Possibly... The other possibility is to look at `node.tValue`. Async nature of this primitive does make it difficult as it isn't really aware of Suspense. This was really important for the pre-1.0 version of Suspense but now is pretty challenging to handle properly with transitions. It's basically side effectful by nature.  I'm pretty sure the problem here is `node.value`. I will a get fix in.
