### ISSUE TITLE
Reconciling a store isn't as smart as I'd hope/expect

### ISSUE THREAD

**Issue by danieltroger** [solidjs/solid#1925]
### Describe the bug

I don't know if this is asking for too much, but when reconciling a store containing an array of objects with mostly new data, solid-js is smart enough to "recognize" objects where one value stayed the same, when unrelated values change, but not when the position of an item changes.

### Your Example Website or App

https://playground.solidjs.com/anonymous/a173c0f0-3060-4809-a619-f0c6b7c749f6

### Steps to Reproduce the Bug or Issue

1. Go to https://playground.solidjs.com/anonymous/a173c0f0-3060-4809-a619-f0c6b7c749f6
2. Click "change data"
3. Observe solid-js being really smart and not re-rendering our component (the random number doesn't change)
4. Click "change position"
5. Observe solid-js no longer recognizing the object and re-rendering our component (the random number changes)

### Expected behavior

Solid-js is really really smart and figures out that our component hasn't changed and therefore just moves the "old" object in the store

### Platform

- OS: macOS 14.0 (23A344)
- Browser: Firefox
- Version: 119.0b9

### Additional context

If this is a wontfix with createStore, how would you solve this?

**Comment by julianwagle** [comment]
Is this a bug in a new release? Updating arrays of objects stopped working for me within the last day. I had the version set to ^1.7.6. I hardcoded the value at 1.7.6, and now my app is working again. I also had to delete the dist folder and even close out dev tools, strangely enough.

**Comment by ryansolid** [comment]
The problem with the example is it creating a new reference each time. The naive algorithm can't tell its the same thing if it is a new object. Like it goes to diff the array and it sees a different object how would it know? It really can't. At which point it replaces the whole thing instead of triggering just the data changing. And the renderer can't know because it is executing functions at that point. It doesn't know if the function it's calling is the same and it didn't keep track of the previous arguments passed etc...

To solve this you have two solutions. Keep stable references like say:
https://playground.solidjs.com/anonymous/11d2fe72-2685-4cd6-a39a-dcc37edd4e25

Or alternatively use the key. By default it's `id`. But we can make it `component` for this example:
https://playground.solidjs.com/anonymous/7332b603-548b-461f-a069-ad5fa2c28956

I'd like to explore more complex keys in the future to handle nested objects with different keys perhaps but this does the job for a lot of things.

**Comment by danieltroger** [comment]
> Or alternatively use the key. By default it's id. But we can make it component for this example:

Oh yes, this is AMAZING. Just what I needed. (Don't have control over where the data is created so can't keep stable references.) Sorry for not finding this in the docs and thanks a lot. Should I close the issue because there's a good solution or should I keep it open as a reminder to take the algorithm from naive to genius? But an algorithm that could deal with this would probably be too slow anyway so I'll close for now.

**Comment by danieltroger** [comment]
@ryansolid is it possible to specify the key in `mapArray` too? From the docs it doesn't seem possible but it would be great.

**Comment by ryansolid** [comment]
`mapArray` wouldn't work or need different design. We assume if references match that our work is done with mapArray. `reconcile` on match of key diffs further. We don't have the ability to know nested reactivity exists downstream. `mapArray` doesn't even have a signal per row for the data from an API standpoint. 

This exists: https://github.com/solidjs-community/solid-primitives/tree/main/packages/keyed

But I haven't brought it core mostly in that it generally is going to be inefficient after shallow depth. Because this knowledge of the diff would have to carry all the way. Like sure new item with the same key, update signal and move position. Well nothing downstream realizes it is the same object. It's possible that you have some same references further down but in a lot of cases you won't. I've been concerned people would find this as the simple solution instead of finding the better solution in in most cases which is stable references/Stores.

**Comment by danieltroger** [comment]
> This exists: https://github.com/solidjs-community/solid-primitives/tree/main/packages/keyed

Ah, interesting, that's certainly good to know.


> But I haven't brought it core mostly in that it generally is going to be inefficient after shallow depth. Because this knowledge of the diff would have to carry all the way. Like sure new item with the same key, update signal and move position. Well nothing downstream realizes it is the same object.
> I've been concerned people would find this as the simple solution instead of finding the better solution in in most cases which is stable references/Stores.


Hmm, I think you're imagining this in a more complex way than I'd need for my usecase. Basically what I want could be described as placing a memo into certain parts of a store, if that makes sense?

So I have a store which are the props from a react component (this store is general for every component and does not have a "key" set). Now these props contain an array of content blocks to show in a product listing. However, every content block contains a react component. I want to pass them to our underlying solidjs library, but I need to convert the react components to solid components first (I have a function called `wrap_solid_in_react` that I need to call for each `content` property of the blocks). The solidjs lib takes all incoming data and reconciles it into a store again that now is diffed on `content` but I don't know if that's relevant.

(structure is basically
```
type Props = {
// random shit
contentBlocksByRow?: {content: React.FC, spanColumns: number; spanRows: number; position: "left" | "right" | "center" }[]
};
```
)

Anyway, when I wrap the functions I'm using mapArray on the store data. As far as I understand what's happening right now is that mapArray kinda goes by index, since I assume that the store that has the react component props falls back to diffing by index since it doesn't recognize a key. The store will keep the references to objects the same as long as they stay at the same index (the objects coming from react obviously have different references every time because react re-executes everything on re-rendere), but if the objects move, `mapArray` will throw away an item and just start again.

What I hoped for with specifying a key to mapArray would be that mapArray keeps going by reference, but if a reference doesn't match it checks if there's an item where the key matches instead. But I now realise probably like no-one else would have that usecase. Because for me it's better if the wrong item in mapArray gets other data (since react then still can re-use it's portal and maybe some DOM elements) than if an item gets re-created.

I'm probably way over-optimising this lol but it's interesting to learn how things work.

Also good to know. since the objects I get in mapArray have reactive properties all I'm returning is an object with getters that in turn call the other getters (and wrap the content property) so basically mapArray wouldn't need to understand anything about the nested structure. Maybe there is a better thing to use here than mapArray?



mapArray doesn't really know
