### ISSUE TITLE
`children()` helper breaks downstream reactivity when used with Context API

### ISSUE THREAD

**Issue by seniorjoinu** [solidjs/solid#1926]
### Describe the bug

When used inside the context provider JSX, `children()` helper breaks reactivity of values passed via the context.

### Your Example Website or App

https://playground.solidjs.com/anonymous/dd4b0563-7e80-4afe-b89c-8c3356c00fa8

### Steps to Reproduce the Bug or Issue

1. Open the provided playground
2. Observe nothing being rendered
3. See the big comment in the middle of the snippet
4. Comment one line and uncomment another
5. Observe children being rendered as expected

### Expected behavior

Reactivity of context values passed to children wrapped in `children()` helper should work the same way as for plain `props.children`.  

### Platform

- OS: Ubuntu 22.04
- Browser: Chrome 116.0.5845.96, Firefox 118.0.2

**Comment by ryansolid** [comment]
Yeah not much to be done here. Ownership happens at creation not at read. I've played with a bunch of variations where we could change that and it breaks. For example if reads happen in multiple locations which one owns it.. the first? the last? That can be non-deterministic. When does reactivity get released? When the first read gets released? The context that it was created under might not even exist anymore.

Another consideration why are we using the `children` helper here. Probably to process it, introspective it. At which point you are going to be getting values and resolving them before the Provider is even created. So that would never work.

The only way this could work is if JSX was not processed until inserted. However, for that to work then `<div />` could no longer be an `HTMLDivElement`. It would need be some custom structural wrapper that doesn't become a `HTMLDivElement` until it is inserted. And that has its own overhead mechanically and cognitively.

While we can avoid needing additional components in most cases, this is not a place that we can implicitly.

**Comment by titoBouzout** [comment]
IF memo becomes lazy, this will work as expected, right?

**Comment by titoBouzout** [comment]
Mmh, tried this and didn't work
https://playground.solidjs.com/anonymous/6925d12c-f825-4071-bbaf-006f5cdb87af

**Comment by ryansolid** [comment]
> If memo becomes lazy, this will work as expected, right?

No... owner doesn't change. I was hoping that it would but it really doesn't. Unless you make unsafe assumptions. I've been trying to determine whether that's acceptable but it would be near impossible to convey to the end user.

**Comment by seniorjoinu** [comment]
Maybe there is a way to get rid of `children` helper at all?

**Comment by ryansolid** [comment]
> Maybe there is a way to get rid of `children` helper at all?

I mean sure, but that would just remove child introspection. Someone could always just not use the feature.
