### ISSUE TITLE
`createResource` is always in pending state when used with `<Show>` component

### ISSUE THREAD

**Issue by mishimalisa** [solidjs/solid#1934]
### Describe the bug

The resource remains `pending` even after the fetcher throw an error.
With astro it remains `unresolved`: https://stackblitz.com/edit/github-bxb9uz-fpjsjd?file=src%2Fcomponents%2FSolidItem.tsx
Using only solid-js: https://playground.solidjs.com/anonymous/ca7145c1-2ac3-44ab-a5c0-5f4fc3ec13fe

Also, the loading state remains `true` and the error state remains `false`.

### Your Example Website or App

https://playground.solidjs.com/anonymous/ca7145c1-2ac3-44ab-a5c0-5f4fc3ec13fe

### Steps to Reproduce the Bug or Issue

1. create a simple `createResource`
2. throw an error inside it
3. Show the state as `fallback` with `<Show>` component

### Expected behavior

With Astro, I expected the `state.error` to be `true` after the fetcher throws an error.

### Platform

- Browser: Chrome
- Solid: 1.8.4

**Comment by ryansolid** [comment]
Yeah this is an interesting one in terms of expectation. Technically the reason this doesn't update is when the `Show` component goes to update it throws. Because resources error on read on write. So the show when never gets to the point where it can apply the update. 

So basically to solve this either you use ErrorBoundary which is generally the recommended approach (often in conjunction with Suspense):
https://playground.solidjs.com/anonymous/479c6304-fd0d-40fc-a5a5-007547c30cdd

Or if you guard on `loading` and `error` (or equivalent states) rather than read of the value it also won't error there: https://playground.solidjs.com/anonymous/d8bd9fb6-42da-4281-9dfa-0a2f5ac6cb51

**Comment by mishimalisa** [comment]
[In the documentation it says:](https://docs.solidjs.com/references/api-reference/basic-reactivity/createResource)
> createResource takes an asynchronous fetcher function and returns a signal that is updated with the resulting data when the fetcher completes.

So, I expected the read function to work just like a signals, and return `undefined` when my fetcher errors.

But, now i understand why `ErrorBoundary` should be used, the documentation mentions it, but it never explains in detail why it should be used or demonstrates the recommended pattern.

**Comment by mishimalisa** [comment]
`Suspense` + `ErrorBoundary` works as expected, but I get a hydration mismatch warning with Astro, I'm not sure why.
Reproduction: https://stackblitz.com/edit/github-bxb9uz-kum69s?file=src%2Fcomponents%2FSolidSuspense.tsx

**Comment by ryansolid** [comment]
I see.. this is a timing issue with Solid + Astro. Might be new in 1.8. You only hit this when a resource errors I imagine because its the only time we serialize data for hydration in synchronous rendering. But it is calling an inline script before the hydration script is added. I temporarily fixed it by adding this to the layout:

`import { generateHydrationScript } from "solid-js/web"`

`<div set:html={generateHydrationScript()}></div>`

But I imagine others will hit this at some point so I will need to look at the Astro/Solid renderer.

**Comment by ryansolid** [comment]
The original issue was by design. The new issue with Astro I'm tracking here: https://github.com/solidjs/solid/issues/1962

**Comment by CreativeTechGuy** [comment]
I realize this is closed, but after wasting many hours on this, I feel like if this was really by design, it should be much more explicit in the docs.

It's unclear why calling `response()` throws an error or would hit an ErrorBoundary. It seems like since there's already a `response.error` property to check if there's an error, that you should be able to safely access the response without it breaking the component. At least that is how other similar libraries (like [TanStack Query](https://tanstack.com/query/latest/docs/react/guides/queries)) handle the very similarly named query response values. I'd expect that I'd have to opt-in to the suspense/error boundary throwing behavior.

------

To summarize my understanding here, when using `createResource`, it needs to be used like this:

```jsx
const [response] = createResource(...);

return (
    <>
        <Show when={response.loading}>Resource loading...</Show>
        <Show when={response.error}>Resource errored {response.error.message}</Show>
        {/* This version is intuitive but breaks reactivity in a surprising way */}
        {/* <Show when={response()}>{(data) => <div>Success {data()}</div>}</Show> */}
        {/* This next part is the unintuitive part which is required for it to work when the resource errors */}
        <Show when={response.state === "ready" && response()}>{(data) => <div>Success {data()}</div>}</Show>
    </>
);
```

But oddly, if the equivalent code is written using `Switch`/`Match`, the issue isn't present. So somehow it's unique to `Show`.

```jsx
<Switch fallback={<div>Loading...</div>}>
    <Match when={response.error}>
        {(err) => <div>Error: {err().message}</div>}
    </Match>
    <Match when={response()}>{(data) => <div>Data: {data()}</div>}</Match>
</Switch>
```

------

Given all this, it feels like there's a bug here. Or at the very least, that the behavior is so confusing/unintuitive that something should be changed to avoid this surprise.

Currently all the docs say on the subject is: `(Note: if you anticipate errors, you may want to wrap createResource in an ErrorBoundary.)` Which feels like a very relaxed suggestion rather than a necessity. Furthermore, wrapping the component in an ErrorBoundary limits our ability to show fine grained error messages in the existing UI since an ErrorBoundary swaps out the entire component.

**Comment by lundal** [comment]
I agree that this is extremely unintuitive behavior, and would classify it as a bug. Why should reading `data()` cause the resource to not update its state? At the very least it should be clearly documented in https://docs.solidjs.com/reference/basic-reactivity/create-resource. At the moment it only says:
> `data` works like a normal signal getter: use `data()` to read the last returned value of `fetchData`. But it also has extra reactive properties: `data.loading` tells you if the fetcher has been called but not returned, and `data.error` tells you if the request has errored out; if so, it contains the error thrown by the fetcher. (Note: if you anticipate errors, you may want to wrap `createResource` in an [ErrorBoundary](https://docs.solidjs.com/reference/components/error-boundary).)

**Comment by PBK-B** [comment]
> > [@ryansolid](https://github.com/ryansolid) I'm a solidjs newbie and this counter-intuitive problem caused me to waste a day troubleshooting and finally found it here. Although using ErrorBoundary + Show to wrap the view can get it to the "correct" state, the state obtained in createEffect is not synchronized at all and remains `pending`. I don't know if this is intentional or a bug. But I believe there are ways to achieve a more intuitive development experience (it would be great if someone could tell me where I can track this optimization later, or do I need to create an issue).
> > playground: https://playground.solidjs.com/anonymous/8e50f73c-2bf6-4a66-a89e-157c466c4153
> 
> It's because the `res()` inside the createEffect is still throwing. If you do e.g. this it will work:
> 
>  createEffect(() => {
> 	console.log('res',  res.state, res.loading, res.error,!res.error && res());
> });

@madaxen86 thank you for your generous guidance. however, as my friends said above, I did not find the relevant description copy in the document. please correct me if I missed anything.

**Comment by madaxen86** [comment]
> description

There's this part in the docs covering createResource and error handling. There's also a code example with Switch/Match showing that res.error should be checked before calling the accessor or adding a ErrorBoundary.
[https://docs.solidjs.com/guides/fetching-data#using-createresource](https://docs.solidjs.com/guides/fetching-data#using-createresource)
