### ISSUE TITLE
Attempting to access a stale value from <Show> that could possibly be undefined.

### ISSUE THREAD

**Issue by phungleson** [solidjs/solid#1959]
### Describe the bug

Hi peeps,

I have a rather complex application with many stores and recently have this issue.

`Attempting to access a stale value from <Show> that could possibly be undefined. This may occur because you are reading the accessor returned from the component at a time where it has already been unmounted. We recommend cleaning up any stale timers or async, or reading from the initial condition.`

I know where I set the store that causes the issue, but I don't know which `<Show />` throws the actual error.

It would be helpful if solid can show me where the issue is so that debug it further, perhaps by throwing Error with stack trace?

https://github.com/solidjs/solid/blob/main/packages/solid/src/render/flow.ts#L16

Cheers,

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

I would like to see the stack trace to debug further.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 1.8.x

**Comment by phungleson** [comment]
Actually after a few seconds, it throws an `Uncaught Error` which is not very helpful either

```
dev.js:967 Uncaught Error: Attempting to access a stale value from <Show> that could possibly be undefined. This may occur because you are reading the accessor returned from the component at a time where it has already been unmounted. We recommend cleaning up any stale timers or async, or reading from the initial condition.
    at castError (dev.js:967:10)
    at handleError (dev.js:980:17)
    at runComputation (dev.js:712:12)
    at updateComputation (dev.js:681:3)
    at runTop (dev.js:786:7)
    at runQueue (dev.js:857:42)
    at completeUpdates (dev.js:813:84)
    at runUpdates (dev.js:803:5)
    at batch (dev.js:435:10)
    at setStore (dev.js:221:5)
```

**Comment by ryansolid** [comment]
Yeah I have to admit this was one of my concerns with introducing the function version of the API. You are looking at the stack trace. For consistency we need to error but this is pretty hard to trace because any prop that you pass down could be accessing it in an event handler etc completely detaching it from where the error happens. The fact this is the downstream result of a setStore call is odd though.

Unfortunately I won't be much help here without a reproduction. It is possible this case is actually a bug and not expected behavior but I won't be able to tell. Your best bet is to put a breakpoint where the error is thrown, but it may be still tricky to debug, but at least we could see what computation is running at the time etc...

**Comment by phungleson** [comment]
Thanks for taking a look, I managed to solve this by removing some code here and there, but didn't have time to dig out the actual issue.

I think it is around passing `<Component />` as part of props, I will look into further if others have similar issues.

Close this for now.
