### ISSUE TITLE
createEffect is not triggered when children change

### ISSUE THREAD

**Issue by 279095090** [solidjs/solid#1969]
### Describe the bug

In the example, there are two Child components, one of which passes the Signal directly, and the other Signal is contained in the div. When the button is clicked, createEffec in the Child component is only activated once

### Your Example Website or App

[example](https://codesandbox.io/p/sandbox/defereffect-forked-2c7ssl?file=%2Fsrc%2Findex.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clph2k2mk00073p6f4w50zf9c%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clph2k2mj00033p6fsoc1h77y%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clph2k2mj00043p6fqbel1jw9%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clph2k2mj00063p6fbq8vwhpr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B52.289174325990174%252C47.710825674009826%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clph2k2mj00033p6fsoc1h77y%2522%253A%257B%2522id%2522%253A%2522clph2k2mj00033p6fsoc1h77y%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clph2k2mj00063p6fbq8vwhpr%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clph2k2mj00053p6f6kpwiy7d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clph2k2mj00063p6fbq8vwhpr%2522%252C%2522activeTabId%2522%253A%2522clph2k2mj00053p6f6kpwiy7d%2522%257D%252C%2522clph2k2mj00043p6fqbel1jw9%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clph2k2mj00043p6fqbel1jw9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to Reproduce the Bug or Issue

just click the button,then see the console.

### Expected behavior

How can createEffect be triggered when the sigal in the div changes and why

### Platform

- OS: [macOS]
- Browser: [Chrome, Safari, Firefox]
- Version: [1.0.0]

**Comment by mosheduminer** [comment]
When the children are wrapped in a div, the effect does not trigger _because the children prop has not updated_. Instead, the text of the div is updated directly. Actually recreating the div would be inefficient, because jsx in solid (unlike vdom frameworks) results in actual DOM nodes, and it would be horrendous for performance if large chunks of those were often getting recreated.

(Ny the way, for the same reason, it's unrecommended to access `props.children` twice, as each prop access reruns the prop expression, which will recreate the div - which is not ideal. We have the `children()` helper function to cache the result of `props.children`).

**Comment by ryansolid** [comment]
Thanks @mosheduminer, that is the correct answer.

**Comment by 279095090** [comment]
Thanks @mosheduminer .
If this is the design, then if I have a scenario like this: I have a sub-component that needs to complete some operations when Children changes, how do I implement it?

**Comment by mosheduminer** [comment]
Solid doesn't have a way for you to listen like that. So the solution will need to involve listening to a callback that you set up instead, or listening to the updating state (but that may not a solution for your case, since you need to react after some operation, which may not be a state update). I can't give a more specific suggestion without more detail about what toy are trying to do.
