### ISSUE TITLE
SVG JSX Types broken for `<symbol>`

### ISSUE THREAD

**Issue by ChristophP** [solidjs/solid#1972]
### Describe the bug

When using an inline SVG in JSX with code like the following,  `<symbol widht="20">`, `tsc` throws a type error saying

```
test.tsx:11:7 - error TS2322: Type '{ children: Element; id: string; width: string; viewBox: string; fill: string; }' is not assignable to type 'SymbolSVGAttributes<SVGSymbolElement>'.
  Property 'width' does not exist on type 'SymbolSVGAttributes<SVGSymbolElement>'.

11       width="12"
         ~~~~~

Found 1 error in test.tsx:11
```

This is strange, because `width` (among others) seems to be explicitly allowed on `<symbol>` according to [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol#attributes)

### Your Example Website or App

https://github.com/ChristophP/solid-js-svg-type-error

### Steps to Reproduce the Bug or Issue

1. Clone this repo
2. `npm ci`
3. `npx tsc` -> See the type error

### Expected behavior

The `width` attribute should be allowed on the `Symbol` element (unless MDN is wrong)

### Platform

Node: 18
OS: MacOS
Solid-JS Version: 1.8.5

### Additional context

MDN docs for `<symbol>`: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol#attributes

**Comment by santoshyadavdev** [comment]
I will open a PR @ryansolid

**Comment by santoshyadavdev** [comment]
@ryansolid do you want me to add other props mentioned on MDN docs too?

**Comment by ryansolid** [comment]
> @ryansolid do you want me to add other props mentioned on MDN docs too?

Sure anything that is missing.

**Comment by ChristophP** [comment]
@santoshyadavdev thanks for taking care of this. For our use case we would need the other props as well. `width` is just the first one that gave the error that's why only that is mentioned in my original post.

**Comment by santoshyadavdev** [comment]
@ChristophP yes I will add other props soon in this PR

**Comment by santoshyadavdev** [comment]
@ryansolid @ChristophP I have added all the props as per MDN docs

**Comment by ChristophP** [comment]
@santoshyadavdev Awesome, thanks for doing this. :-)

**Comment by ryansolid** [comment]
Hmm.. interestingly mdn doesn't show symbol having width: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/width

The reason I'm mentioning this is adding all the attributes to global sort of clobbered the types. As far as I can tell they don't all belong there. I can see that symbol has width.. but it doesn't have other ones that don't appear in the global list. I think putting the stuff global probably isn't right. I'm going to add it to symbol but we probably need to take a more one off approach here. Which sucks because it means more one off issues like this but, like preserveAspectRatio has different meaning on different elements. It isn't exactly global etc..

**Comment by ChristophP** [comment]
Weirdly Symbol does have width on this MDN Page https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol#attributes   
even though it's not mentioned on the element list that have width on the Page @ryansolid mentioned
