### ISSUE TITLE
Contexts not accessible from web components created by HTML strings

### ISSUE THREAD

**Issue by apademide** [solidjs/solid#1976]
### Describe the bug

If required, more context is available in Solid's Discord: https://discord.com/channels/722131463138705510/1182006344128151693/1182006344128151693

### General flow
I have an API that shares JSON content used by the Solid frontend app. Some of the properties contains text as HTML which itself uses web components as placeholders for values only known by the frontend. This means part of the DOM tree is generated by direct HTML injection rather than Solid JSX.

For precision, it's actually `DocumentFragment`s that get injected after the HTML's been passed to DOMPurify, but the reproductible example uses straight `innerHTML` and strings so I consider it irrelevant. 

### Behavior
Whenever trying to access a context with `useContext()` from a web component that has been injected in the DOM by innerHTML or `<div>{functionThatReturnsDocumentFragment("<web-comp></web-comp>")}</div>` in the JSX, it's unavailable and returns the default value. 

### Worth mentioning
When the context provider itself is a web component OR the consumer web component is added directly in Solid's JSX, it works.
Please do find various pairs of context providers/consumers in the [linked Solid playground](https://playground.solidjs.com/anonymous/64fbab2d-93dd-4c92-bd1c-12a6c4356574), where all work as expected except for the one where the web component is injected by other mean than Solid JSX within a context provider that's not a web component. 

### Additional note
Trying to understand what was going on, I tried to mess around a bit. I checked the context code and climbed up to `getOwner()`, where I found that `getOwner().context` is `null` within those web components. Might be either obvious or useful, I'll let you be the judge of that. 

### Your Example Website or App

https://playground.solidjs.com/anonymous/64fbab2d-93dd-4c92-bd1c-12a6c4356574

### Steps to Reproduce the Bug or Issue

The linked playground provides a fully (not) working repro, where you can see the behaviour. 

### Expected behavior

I expect the web components to be able to access the value of their parent context providers regardless of how they're added to the DOM.

### Platform

- OS: macOS
- Browser: Safari, checked with Firefox
- Version: Safari 17.0
+ Solid Playground

**Comment by ryansolid** [comment]
Yeah this is pretty hard. Web Components can upgrade async so I had to come up with my own way to handle it with Solid Element. This is why most Context in frameworks doesn't work with Web Components. Admittedly back when I used web components I had it wrap my whole application so because the root was in a web component I could use the parent as the lookup. I think I use a combination of slots, and compiling the current rendering context into the element.

We would need to have another location for it to look up the context somehow. You could set the `_$owner` property on your element after creation before connecting it to the DOM and that might do the trick. Assuming where you create it you can `getOwner`. The thing is Solid isn't going to be writing a bunch of stuff into the DOM in general and in many cases the representation isn't even one for one.. like fragments. So our JSX can handle the insertion but top level you would need to somehow connect it yourself.
