### ISSUE TITLE
ErrorBoundary breaks when using useExternalSource

### ISSUE THREAD

**Issue by modderme123** [solidjs/solid#1982]
### Describe the bug

Because we create ErrorBoundary with an undefined function, when executing runTop with useExternalSource, we try to call the external source with this function which is null

(Additionally, ensuring fn is defined before calling it in the external source isn't sufficient, because then nested effects won't update)

### Your Example Website or App

https://playground.solidjs.com/anonymous/72c24d21-c2e7-4cc5-916a-b907330bef22

### Steps to Reproduce the Bug or Issue

1. Click the button
2. `TypeError: fn is not a function` is logged

### Expected behavior

No error is logged, and this works the same as if the externalSourceFactory was not introduced.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 120

**Comment by nev1d** [comment]
As a result of small research, i found out, that problem is in this line:
![image](https://github.com/solidjs/solid/assets/69861627/a43f2aad-9d9f-473b-8735-0cebf8090514)

IMO, using a non-nulish in this scenario is not good practice and this bug can be founded on type checking level.

So there is probably 2 ways:
1. Remove non-nulish and add an additional checking for undefined before function calling
2. Try to understand why in this scenario we need undefined and maybe create a correct callback if we dont

@ryansolid after approval i will open PR

**Comment by ryansolid** [comment]
This whole thing was sort of a hack until 2.0 can introduce the proper thing. I wanted to create basically an inert context. If you give it a function it thinks it has something to execute. The type stuff is sort of besides the fact. Roots work like this so during execution generally seemed ok, but I didn't take external source into consideration with this change and without it having a concept of inert context as Milo said it won't work.
