### ISSUE TITLE
The content of `Match` components gets runned again even if it's not needed

### ISSUE THREAD

**Issue by AFatNiBBa** [solidjs/solid#1998]
### Describe the bug

When there are multiple `Match` in a `Switch` the order is taken into consideration to choose which one should be shown.
My problem is that the content of an active `Match` gets re-executed if its order changes, even if it still remains selected.
This is a problem when creating a dynamic number of `Match` from an array

### Your Example Website or App

https://playground.solidjs.com/anonymous/88e4ffce-525c-49f4-ba62-2f8806fb3204

### Steps to Reproduce the Bug or Issue

In my example the selected `Match` is always the one containing the number 3 and a message gets printed on the console every time a branch content gets executed.
Pressing the buttons will change the generated branches, and the selected one will print a message each time its position changes

### Expected behavior

I expected that the content of the active `Match` would be executed just once, since it's always the selected one

### Platform

(Not needed)
- OS: Windows
- Browser: Edge
- Version: 120.0.2210.77

**Comment by ryansolid** [comment]
Yeah the problem seems to be that we use the index for the equality check which probably isn't necessary. The Matches appear to be stable. I'm trying to think of any cases where index would actually matter. And I don't. As long as the same match is matched we don't care. If someone changes the order we will re-evaluate anyway and if it resolves to the same it is still good. And if it doesn't then no problem.

Ok will get this in the next release.
