### ISSUE TITLE
Unable to use in nextjs after build

### ISSUE THREAD

**Issue by track23** [solidjs/solid#2054]
### Describe the bug

The part written in solid-js is packaged and introduced in nextjs. When the next build occurs, it prompts ReferenceError: window is not defined.

The same code can be built using svelte and used in nextjs。

my code(solid-js)
```tsx
// index.tsx
import { render } from "solid-js/web";

import "./index.css";
import App from "./App";

const widget = () => {
  const root = document.getElementById("root");
  render(() => <App />, root!);
};

export default widget;
```

Using it in nextjs
```tsx
'use client'
import { useEffect } from 'react'
import solidApp from 'my-solid-app'

export default function Page() {
  useEffect(() => {
    solidApp()
  },[])
  return <div id="root"></div>
}
```

This is my vite config
```js
import { defineConfig } from "vite";
import solid from "vite-plugin-solid";

export default defineConfig({
  plugins: [solid()],
  build: {
    lib: {
      entry: "./src/index.tsx",
      formats: ["es"]
    },
  },
});
```

### Your Example Website or App

https://github.com/vitejs/vite/tree/main/packages/create-vite/template-solid-ts

### Steps to Reproduce the Bug or Issue

1 build solidejs project
2 Using it in nextjs client components（In effect hook）
3 netx build

### Expected behavior

Can be used normally

### Platform

windows
next 13.5.4
nodejs 18.15.0

**Comment by ryansolid** [comment]
This seems like it is an issue with how you are importing the code into Next, or how Next is bundling it.

I think we will need a bit more details on how the code is getting included in Next. Preferably a reproduction. That error suggests that client code is being bundled into your server bundle. Since it sounds like your intention is to use this in the browser only that client code is there seems fine. However, you might need to lazy import it to prevent the bundler from bringing it on the server. 

Blind I'd say try:
```js
'use client'
import { useEffect } from 'react'

export default function Page() {
  useEffect(() => {
    import('my-solid-app').then(mod => mod.default());
  },[])
  return <div id="root"></div>
}
```
The fact it works with Svelte is probably related to where browser APIs are being accessed and not the fact it isn't being included on the server. Depending on other build configuration above may not work (like if they inline dynamic imports on the server) but lets hope that isn't the case.

**Comment by track23** [comment]
`` import('my-solid-app').then(mod => mod.default());``
This can be used normally。

But why can't we be like svelte, 
```tsx
"use client";
import { useEffect } from "react";
import svelteApp from "my-svelte-app";

export default function Page() {
  useEffect(() => {
    svelteApp();
  }, []);
  return <div id="app"></div>;
}
```
Sorry, I cannot provide more code as I have deleted it. 
The nextjs code only has the above point. I just wanted to test whether I can use the solidjs app when rendering on the client side, but an error occurred during build

**Comment by ryansolid** [comment]
Honestly without understanding the call stack of what's going on it's pretty hard to tell. Obviously none of our tooling uses `window`, so realistically there seems to be 2 possibilities here:

1. This is a build error because code is getting pulled in that references window and it can't resolve the symbol. However, this is unlikely given Svelte would also reference the window/document somewhere, and most bundlers if they can't find a global symbol aren't going to choke. They expect it to be on `globalThis`.

2. It is a runtime issue where something is being called at a global scope that references `window`. I don't believe we have any of those anymore at least in the core lib but without a stack trace might be hard to track down. In this case Svelte app may just not have a top-level reference like that so it isn't hitting the issue. But it doesn't mean in absence of `import()` the client side Svelte app isn't getting bundled into the server app unnecessarily.

**Comment by track23** [comment]
You're right, it's my problem. My previous attempts were too hasty. Both svelte and solid can only be dynamically introduced and used in nextjs. Thank you for your help.
