### ISSUE TITLE
Changing the "data-type" of a `createStore` attribute causes referenced data to be modified

### ISSUE THREAD

**Issue by hawkerboy7** [solidjs/solid#2063]
### in short
When switching from data-type in `createStore({ current: null })` => `setStore("current", {})` shouldn't a `structuredClone()` be made of the new data-type to prevent referenced data from being manipulated?

### Describe the bug

First a huge tanks to ryansolid (I did not @mention him to prevent maybe unwanted notifications) and the Contributors for this great project!!!

I ran into this issue and I made an example because I am not sure how this concept is named.
https://playground.solidjs.com/anonymous/89aecb87-da00-4fa8-bfc3-72794555d630

**Issue**
When you have some jobs `jobs = [{ name: "A" }, { name: "B" }, { name: "C" }]`
and you create a `[stats, setStats]  = createStore({ current: null })`
and later update that attribute with `setStats("current", jobs[0])`
and later update that attribute with `setStats("current", jobs[1])`
`jobs[0]` is modified!

If you start with: `createStore({ current: {} })` instead of `{current: null}` this does not happen.
I tried other data-types (`integer`, `string`) as well and this behavior is the same.

**Reason**
The example on the playground.solidjs.com indicates:
`Argument of type '{ name: string; }' is not assignable to parameter of type 'StoreSetter<null, ["current"]>'.
  Type '{ name: string; }' provides no match for the signature '(prevState: null, traversed: ["current"]): null'`

So "switching a data-type" (if that is what it is named) is not possible / should not be done.
However this code (as you can see in the playground) does run without error's and now silently causes unexpected behavior (or at least to me :smile:).

**Question / proposal**
As of right now I am working in JS not TS so I won't be able to see this types of issue from TS.
Though probably an easy ask and a lot harder to implement, would it not be better/safer if the setter of `createStore` would do any of these things:
- log a warning when this happens but continue
- throw when this happens
- on "data-type switch" perform the switch as it is doing now, but use a `structuredClone()` to do it so referenced data does not  get modified on future modifications of the same "data-type".

### Your Example Website or App

https://playground.solidjs.com/anonymous/89aecb87-da00-4fa8-bfc3-72794555d630

### Steps to Reproduce the Bug or Issue

1. Open the link: https://playground.solidjs.com/anonymous/89aecb87-da00-4fa8-bfc3-72794555d630
2. Look at the logs saying `{ "name": "A" } { "name": "B" } { "name": "C" }`
ending in:  `{ "name": "C" } { "name": "B" } { "name": "C" }`

### Expected behavior

The logs should keep saying `{ "name": "A" } { "name": "B" } { "name": "C" }`

### Platform

- OS: Linux
- Browser: Chrome & Firefox
- Version: 1.8.12

**Comment by ryansolid** [comment]
Yeah. Structured clone on any set would lose reference and be super unperformant. The reason the hijacking comes in is that the whole `setStore` API is a DSL of sorts. Objects shallow merge as [mentioned in the docs].(https://www.solidjs.com/docs/latest/api#updating-stores). It was a choice to reduce `setStore` calls and mimic top level `setState` calls in React back in a time before Hooks existed. I think it is confusing as an API but it is also something that won't be changed in 1.0.

What you should be doing is:
```js
setStats({ current: jobs[0] })
setStats({ current: jobs[1] })
```
This won't merge jobs.. the fact the other wasn't merging was due to the fact that things that aren't deemed the same type can't be. That being said though at some point some deeper change might mutate one of these objects so I wouldn't expect to hold on to them. One of the reasons reference is important is equality checks, and the other is multiple instances of the same store data in multiple locations, so just cloning isn't really an option.
