### ISSUE TITLE
using createStore setter function to update array results in argument is not iterable error

### ISSUE THREAD

**Issue by tx-tim** [solidjs/solid#2067]
### Describe the bug

When using the setter returned from `createStore` to update an array, i get an error that indicates the array is not an iterable. I know it's not undefined as in #1277 because I can log out the values of the store.  I've set up a demo on codepen [here](https://codepen.io/tx-tim-the-selector/pen/gOEdNKb).

In the demo, I'm attempting to update the status of ToDo items in an event handler and then move completed items from a New Todo list to a Done list.

Then in the todo component I have an event handler that calls the setter function from returned from `createStore` almost exactly like in the [example docs](https://www.solidjs.com/docs/latest/api#updating-stores):

```
const setComplete = (e) => {
    setState(state, l => [...l, {id: props.toDo.id, data: props.toDo.data, status: 'complete'}]);
  };

```

### Your Example Website or App

https://codepen.io/tx-tim-the-selector/pen/gOEdNKb

### Steps to Reproduce the Bug or Issue

1. go to https://codepen.io/tx-tim-the-selector/pen/gOEdNKb
2. click on one of the items where you see the app is rendered
3. open the console an see the error "TypeError: l is not iterable"

### Expected behavior

I would expect the setState function to update the array item in the store, and for the item to then move to the corresponding list

### Platform

- OS: [e.g. macOS]
- Browser: [e.g. Chrome, Firefox]
- Version: [1.7]

**Comment by hawkerboy7** [comment]
Hi @tx-tim,

I think it should be this:
```javascript
const setComplete = (e) => {
    setState(l => [...l, {id: props.toDo.id, data: props.toDo.data, status: 'complete'}]);
  };
```
Though you won't get an error it still won't work.
If you do `typeof l` you see it is an object.
`createStore([])` apparently turns your array into an object with 0,1,2,... as the keys of that object.

So effectively your doing this:
```javascript
const array = [...obj]; // TypeError: obj is not iterable
```

I just started with SolidJS so not sure why `setState` does that.

I think the SolidJS way of changing your example would be to target get the task index in the array and update the specific `completed` field only, instead of creating a new array and overwriting the old one with the update.
```javascript
setState(0, "status", "completed")
```

**Comment by ryansolid** [comment]
Thanks @hawkerboy7. Your response is mostly correct. `typeof someArray` will be "object" even for arrays so that doesn't mean it can't be iterated. The problem with iteration was the store being passed in as the first argument. It definitely can be spread like shown.

I would add, I think that the codepen is not using our JSX transform so things like the For component aren't updating because the `each` property is manually being wrapped in a function. I went and wrapped every expression in a function and this "works".  I mean it doesn't behave the way I would expect but that is the way the code is written.

```js
/** @jsx h */

const $ = document.querySelector.bind(document);

import { render } from "https://cdn.skypack.dev/solid-js/web";
import h from "https://cdn.skypack.dev/solid-js/h";
import { For } from "https://cdn.skypack.dev/solid-js";
import { createStore } from "https://cdn.skypack.dev/solid-js/store";

var todoList = 
[
    {
        "id": 1,
        "status": "complete",
        "data": {}
    },
    {
        "id": 2,
        "status": "skipped",
        "data": {}
    },
    {
        "id": 3,
        "status": "skipped",
        "data": {}
    },
    {
        "id": 4,
        "status": "new",
        "data": {}
    }
];

const [state, setState] = createStore(todoList);

function App() {
  return (
    <div>
      <TaskList heading="New" tasks={() => state.filter((item)=>item.status === 'new')} />
      <TaskList heading="Done" tasks={() => state.filter((item)=>item.status !== 'new')}/>
    </div>
  );
}

function TaskList(props) {
  return(<div>
      {() => props.heading}
      <For each={() => props.tasks}>
        {item => (
         <Task task={item} />
        )}
      </For>
  </div>)
}

function Task(props) {
  const setComplete = (e) => {
        setState(l => [...l, {id: props.task.id, data: props.task.data, status: 'complete'}]);
  }
  return(
    <div onClick={setComplete}>
      task:{() => props.task.id} | {() => props.task.status}
  </div>)
}

render(() => <App />, $("#app"));
```

So instead of doing that I copied it into our playground where it uses our JSX transform:
https://playground.solidjs.com/anonymous/78c23588-b553-45df-8f28-5aec7cda77ca

**Comment by tx-tim** [comment]
@hawkerboy7 @ryansolid thanks for your replies - I have a much better understanding now - cheers!
