### ISSUE TITLE
Hydration Mismatch - createResource

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid#2104]
### Describe the bug

On initial server start I see a Hydration Mismatch. Clicking the reset error button here will make it go away:

<img width="104" alt="Screenshot 2024-03-19 at 16 34 14" src="https://github.com/solidjs/solid/assets/74932975/34948f04-a59c-47a7-9272-d19e435a836f">

Clicking refresh will make it appear again:
<img width="88" alt="Screenshot 2024-03-19 at 16 34 57" src="https://github.com/solidjs/solid/assets/74932975/f91720fe-1fd4-4c96-9fa9-92450d8236c0">

The error is:
`Hydration Mismatch. Unable to find DOM nodes for hydration key: 0-0-0-0-0-0-0-3`

### Your Example Website or App

https://stackblitz.com/edit/github-mabc11-lznifr?file=src%2Fapp.tsx

### Steps to Reproduce the Bug or Issue

Make a bare example, enable SSR, and inserted this in app.tsx:

```tsx
import { Show, createResource } from 'solid-js';

export function getData() {
  return `some data`;
}

export default function App() {
  const [data] = createResource<string>(getData);

  return (
    <main>
      <Show when={data.state === 'ready'} fallback={<p>Loading</p>}>
        <p>Loaded: {data()}</p>
      </Show>
    </main>
  );
}
```

### Expected behavior

I expected it to load and show the data just fine, like when ssr:false.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 122
- Solid Start 0.7.6

**Comment by ryansolid** [comment]
Hmm.. yeah no this is tricky because it doesn't read the resource so it probably finishes the client and server differently. I will need to check, but I'm almost positive this won't do what you want to do anyway.

On the server first pass it doesn't see ready so it doesn't read it which means it doesn't suspend on the server. And will reply with Show fallback but not the Suspense fallback. 

Sigh.. I knew adding these states to `createResource` were a mistake.

**Comment by ryansolid** [comment]
Yeah in this case the data is showing as ready immediately at hydration time because it is serialized on the server and transported before Solid gets to hydrating. At which point the show fallback from the server doesn't match the show success case expected in the browser. Usually this wouldn't be a problem because if suspended we know that everything is aligned at hydration time, but with this we don't. I think it is important that even if not suspended (ie resource resolves synchronously) that it works on both sides so I don't see "fixing" this.

Using `data.loading` or `data.state` as guards to bypass Suspense pretty much makes our ability to match client and server impossible here.

**Comment by birkskyum** [comment]
Aaah, so just swapping Show with Suspense, and removing the 'when'/ .state part does the trick. 

Works beautifully - even with the use of innerHTML in this shiki+twoslash hover code-block demo:
https://stackblitz.com/edit/github-mabc11-dxwk48?file=src%2FCodeComponent.tsx
