### ISSUE TITLE
Custom elements using `is` not recognized as custom elements

### ISSUE THREAD

**Issue by thesmartwon** [solidjs/solid#2122]
I am experiencing #1735 with `<canvas is="my-web-component">`.

I assume this is because the `isCE` check (maybe [here?](https://github.com/ryansolid/dom-expressions/blob/main/packages/lit-dom-expressions/src/index.ts#L433)) is incorrect. The correct way to check for a custom element is to use the [`window.customElements`](https://developer.mozilla.org/en-US/docs/Web/API/Window/customElements) registry like so:
```js
const isCE = window.customElements.get(tagName) != undefined;
```

In the meantime I've worked around it by refactoring my custom element to `<my-web-component>` instead, but this is not ideal.

**Comment by ryansolid** [comment]
Yeah... you are right. Every place we check is probably looking for `-` character. Is it safe to assume all elements with an `"is"` attribute are custom elements too I wonder. The problem is we need to know this stuff at compile time so there is no checking the runtime registry. Having a compile time registry seems a bit awkward if it can be avoided.

**Comment by trusktr** [comment]
Yeah, I think we can expect spread not to work, like how a tag name is also not part of spread. The expectation that it has to be written in the template just like the tag name would be fine.

Maybe `Dynamic` needs a special `is` prop for this case, as opposed to supporting it by spread there.

```jsx
return <Dynamic component="canvas" is="my-special-canvas" />
```

**Comment by ryansolid** [comment]
Dynamic is pure runtime so it can't have special treatment. That being said it doesn't clone so I think it is fine. Unless is elements need to be created differently too.
