### ISSUE TITLE
Component doesn't reliably respond to a signal after hydration

### ISSUE THREAD

**Issue by fasiha** [solidjs/solid#2160]
### Describe the bug

I have SSR enabled, and a module-scoped signal that is set `onMount` in one component. A second component that reads that signal doesn't reliably get notified when that signal is set.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-rqx1ev?file=vite.config.ts,src%2Findex.tsx,index.html,src%2FAvatar.tsx,src%2FUser.tsx

### Steps to Reproduce the Bug or Issue

1. Go to https://stackblitz.com/edit/solidjs-templates-rqx1ev?file=vite.config.ts,src%2Findex.tsx,index.html,src%2FAvatar.tsx,src%2FUser.tsx (kindly put together by Astro dev @matthewp via https://github.com/withastro/astro/issues/11017)
2. Click "Login" button (this sets localStorage `user` to "ahmed")
3. Refresh a few times

### Expected behavior

After refresh, I expect both bold lines to say `User is "ahmed"` (responding to the `user` signal being set by the `User` component's `onMount`)

However, often one or both will say `User is ""`, not reacting to the signal. Sometimes this works, other times it doesn't.

### Screenshots or Videos

![solid-rehydrate-behavior](https://github.com/solidjs/solid/assets/37649/f38641e8-1243-4073-b63a-fb5fd6d37e01)

### Platform

- OS: dev is macOS but bug tested in macOS and Windows
- Browser: all browsers tested
- Version
```
    "solid-js": "^1.7.6"
    "vite": "^4.3.9",
    "vite-plugin-solid": "^2.7.0"
```

### Additional context

Hypothesis from https://github.com/withastro/astro/issues/11017:
> There appears to be a timing bug related to hydration and components that render asynchronously.

**Comment by ryansolid** [comment]
I see the issue it is just a bit tricky. The we are pretty lax when it comes to hydration in that we assume the server is correct and we don't correct text mismatches. If someone interacts with the page then we cancel hydration/streaming and apply the new state. However, if things are still hydrating we continue to assume the server is correct. What is happening in the example here is that since the one place is hydrating it assumes it doesn't need to do work but the signal under it has changed. So while the signal is being tracked and would update on another change it doesn't try to write the DOM initially. 

That being said in general lazy hydrating + shared state is just not a good idea. Because the client state can change and if it is shared hydration will break. Like consider a global counter that can be incremented and the lazy hydrated component shows/hides stuff based on whether the count is above 5. If anything changed the counter before it hydrated you'd have serious hydration errors. This error was less serious and wasn't detected, but it would cause hydration issues just the same in other solutions that were stricter.

**Comment by fasiha** [comment]
@ryansolid ahh, understood, thanks for that cogent explanation! Adding a `onMount(() => console.log("Mounting …", new Date().toISOString()))` to both components reveals that the incorrect behavior happens only when the signal-reader component (`AvatarSolid` in the example) is hydrated *after* the signal-setter component (`User`): the newly-hydrated component never "heard" the signal being set.

If I can burden your generosity some more. Should I just abandon the hydration + shared state model? Is that just a Bad Idea™️?

Or does one just have to be careful about this pitfall by making the signal-writer (`User`) write the signal only after it's confirmed that all readers have been hydrated? A terrible workaround might be to just wait 100 ms after page load to write to the signal. Are there better ways to work around this or should I just give up?

**Comment by katywings** [comment]
@fasiha Maybe instead of onMount you could use https://primitives.solidjs.community/package/lifecycle#ishydrated as a way to check if you are safe to change the signal 🤔
