### ISSUE TITLE
When `createResource` is used to load entities, and `createStore` is used to reference those entities, updates to store properties which reference entities should not mutate the original resource.

### ISSUE THREAD

**Issue by altearius** [solidjs/solid#2174]
### Describe the bug

Given that `createResource` is used to load entities,
And that `createStore` is used to create a store,
And one of the store properties is used to reference an entity found in the resource,
And the store property is updated to reference one entity,
And the same store property is later updated to reference a different entity,
And the same store property is later updated to reference the first entity again,
Then the original list of entities found in the resource should be unaffected.

The observed effect is that the underlying list of entities _in the resource_ is mutated, which I perceive to be a bug.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-mncih9?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Load the Stackblitz page and observe the entity list from the resource to be `[{"id":1,"name":"one"},{"id":2,"name":"two"}]`.
2. Click on "Target One" and observe that the first entity is targeted.
3. Click on "Target Two" and observe that the second entity is targeted.
4. Click on "Target One" and observe that the resource changes to `[{"id":2,"name":"two"},{"id":2,"name":"two"}]`.

### Expected behavior

On step 4, the value of the resource should not have changed.  The first entity should have been targeted.

### Screenshots or Videos

https://github.com/solidjs/solid/assets/270430/00e1c1b4-547b-4301-9c82-3bcd2f3d233f

### Platform

- OS: Tested on Ubuntu and Windows
- Browser: Brave
- Version: v1.66.113

**Comment by ryansolid** [comment]
This is due to the fact objects shallow merge(https://docs.solidjs.com/concepts/stores#modifying-objects). This is to be consistent across depth as `createStore` APIs originally were influenced by React class components `setState`. 

You can fix the issue by setting with an object:
```js
setStore({target: resource()?.children[1]});
```
While I've come to believe this API is non-intuitive in the past 6 years since I introduced it would be a breaking change to "fix" this. Our intention is to shift people off the this API over time in next major versions.
