### ISSUE TITLE
optional props typescript types error & props bug

### ISSUE THREAD

**Issue by rainyEra** [solidjs/solid#2199]
### Describe the bug

If all of my props are optional in a type, I shouldn't need to pass them in a hook, but I'm getting an error:

Expected 1 arguments, but got 0.typescript(2554)
useHook.tsx(1, 25): An argument matching this binding pattern was not provided.

Moreover, if you've passed inline params, they won't work - you'll get undefined. However, you can fix everything above if you pass {} in props. I think SolidJS should do this by itself because it causes significant issues when building a library for it.

### Your Example Website or App

https://codesandbox.io/p/devbox/still-lake-forked-9qsvdf?file=%2Fsrc%2FApp.tsx%3A5%2C29

### Steps to Reproduce the Bug or Issue

1. Go to the link
2. Pass { } to useHook
3. **Manually** press refresh button in the IDE browser
4. You'll see the text

### Expected behavior

If all of my props are optional, I shouldn't get an "Expected N arguments" TypeScript error, just like in React.
The developer shouldn't need to manually pass {} in props to make inline params work (they are undefined right now).

### Platform

- OS: [Windows,]
- Browser: [e.g. Firefox,]
- Version: [91.1]

**Comment by ryansolid** [comment]
Looks like I don't have permissions to see the reproduction.

**Comment by rainyEra** [comment]
> Looks like I don't have permissions to see the reproduction.

Yeah, my bad. It is available now.

**Comment by maciek50322** [comment]
This is the typescript that shows you the error. The hook is simply a function. You described the hook to require a parameter, that is an object with `param` property.
```ts
const useHook = ({ param = "inlineParam" }: { param?: string }) => { ... }
useHook(); // errors
useHook({}); // is fine
useHook({ param: "123" }); // is fine
```
With this syntax you descructure given parameter. Destructured object needs to exist, otherwise you would get error during destructuring, here typescript notifies you that the function expects an object, otherwise you would get runtime error. 
To make your parameter optional, you should pass the `?` between the parameter name and type, like so:
```ts
const useHook = (x?: { param?: string }) => { ... }
useHook(); // is fine
useHook({}); // is fine
useHook({ param: "123" }); // is fine
```
But if you desctructure your parameter immediately, you can not make it optional (object is required to destructure it), but you can give it default value if not passed:
```ts
const useHook = ({ param = "inlineParam" }: { param?: string } = {}) => { ... }
useHook(); // is fine
useHook({}); // is fine
useHook({ param: "123" }); // is fine
```

Note that only `= {}` (as first parameter's default value) is sufficient for `useHook()` to have it's `param` set to your default value `"inlineParam"` and if you instead set the `param` only inside parameter's default value:
```ts
const useHook = ({ param }: { param?: string } = { param: "inlineParam" }) => { ... }
```
Then `useHook()` would have it's `param` set to `"inlineParam"` and the `useHook({})` would have it's `param` set to `undefined`.


Also your hook isn't component, it doesn't need parameters inside single object. You could define your function as following:
```ts
const useHook = (param: string = "inlineParam") => { ... }
```


### You can learn more here:

https://www.typescriptlang.org/docs/handbook/2/functions.html#optional-parameters
