### ISSUE TITLE
Hydration removes server-side rendered lazy components

### ISSUE THREAD

**Issue by katywings** [solidjs/solid#2236]
### Describe the bug

If you server-render a lazy component inside a (triggered) Suspense boundary as a direct child, the lazy component will be removed during client-side hydration. 

Workaround:
Nesting the same lazy component in e.g. a `<div>` prevents the removal. Just nesting inside a `<>` or `<Show>` however doesn't prevent the removal.

### Your Example Website or App

https://stackblitz.com/edit/github-mjk4uu?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Implement some logic that triggers the suspense boundary (e.g. something with `createAsync`)
2. Render a `lazy` component inside of the suspense boundary as a direct child

### Expected behavior

I expected the client-hydration to properly pick up the server-rendered lazy components, instead of removing them.

### Screenshots or Videos

Demonstration of the bug:

https://github.com/user-attachments/assets/e8c9f886-c19a-4bc7-ae9c-aad03d312a19

---

Even more weird behaviour if you render a lazy element outside of Suspense:

![2024-07-23_15-22](https://github.com/user-attachments/assets/efc24b84-ff50-4d3d-a520-dbfdcf6ea366)

### Platform

- Browser: Chrome & Firefox
- Solid: 1.8.18

**Comment by ryansolid** [comment]
Yeah this has been a moving target unfortunately. We've had 3 different forms of fragment hydration and they have all seemed to leave gaps. Will add this to the list of cases to test against but fixing this might take a while.

**Comment by ryansolid** [comment]
Looking at this after doing some other fixes this had nothing to do with lazy components and everything to do with doing a falsey check instead of an undefined check in createResource. As it turns out we shortcut serializing the promise if it is available synchronously (like with deferStream).. then we just serialize the value.. unfortunately createResource saw `false` and thought there was no value there causing it to refetch during hydration and well.. start updating the DOM while it was trying to hydrate causing some mayhem.
