### ISSUE TITLE
Hydration error upon wrapper not rendering children (e.g. when wrapper returns `null`)

### ISSUE THREAD

**Issue by brillout** [solidjs/solid#2248]
### Describe the bug

Rendering this with SSR:

```jsx
function Page() {
  return (
    <>
      <Head>
        <span>Hello</span>
      </Head>
    </>
  );
}

function Head({ children }) {
  return null
}
```

Leads to an hydration error:

```
renderPageClientSide.js?v=893d3cd7:200 Error: Hydration Mismatch. Unable to find DOM nodes for hydration key: 000021030
    at getNextElement (chunk-JDADEQKQ.js?v=893d3cd7:361:37)
    at get children (+Page.tsx:15:12)
    at Head2 (+Page.tsx:22:17)
    at @solid-refresh:25:42
    at untrack (chunk-MLLIFDXK.js?v=893d3cd7:442:12)
    at HMRComp.createMemo.name [as fn] (@solid-refresh:25:28)
    at runComputation (chunk-MLLIFDXK.js?v=893d3cd7:712:22)
    at updateComputation (chunk-MLLIFDXK.js?v=893d3cd7:695:3)
    at createMemo (chunk-MLLIFDXK.js?v=893d3cd7:257:10)
    at [solid-refresh]Head (@solid-refresh:22:20)
```

### Your Example Website or App

https://github.com/brillout/solid-bug-wrapper-children-skip

### Steps to Reproduce the Bug or Issue

https://github.com/brillout/solid-bug-wrapper-children-skip#readme

### Expected behavior

No hydration error.

### Platform

- OS: Linux
- Browser: Chrome
- Version:  `1.8.19`

### Additional context

We're trying to implement a `<Head>` component for [`vike-solid`](https://github.com/vikejs/vike-solid).
- Like `vike-react`'s `<Head>` component: https://vike.dev/useConfig#config-head
- Similarly to Next.js's `<Head>` component: https://nextjs.org/docs/pages/api-reference/components/head

**Comment by ryansolid** [comment]
The problem here is eagerly rendering the children and then not inserting them which messes with id creation matching. I understand that this is a simplified execution but often these cases are masking something else that is undesirable to do anyway like creating children multiple times etc..

Related issue: https://github.com/solidjs/solid/issues/1977
Comment: https://github.com/solidjs/solid/issues/1977#issuecomment-1881539822

**Comment by ryansolid** [comment]
I'm interested in people's opinion on this is. There are options. But you understand the reason it can't hydrate is it can't find nodes that it is creating at that point because they weren't in the DOM. It means they were created unnecessarily on the server and we have no choice but to create them again in the browser since they don't exist.

The challenge might be that there is no way to differentiate this from any other sort of hydration error. At the point of creation, it isn't possible to know that this is because you don't intend to insert these nodes or that something else has gone wrong. So the only way to make this case pass is to not complain on any hydration error and just yolo it. That seems dangerous and even harder to debug.

**Comment by brillout** [comment]
> eagerly rendering the children

I see.

> I'm interested in people's opinion on this is.

I don't much about Solid internals, so I ain't sure. But, in principle, if the wrapper synchronously returns `null` then Solid could interpret this as "ignore children". Although, if the hydration error is currently shown synchronously, this would require the hydration error to be shown asynchronously in the next tick.

**Comment by brillout** [comment]
A user-land workaround is to use `<Show>`: https://github.com/vikejs/vike-solid/pull/104/commits/3d01dc7001c1fd2ef9b364a509966cbf1b04a00a. Although it's a bit of a bummer as it requires the user to always wrap `<Head>` with `<Show>`.

Any ideas for a workaround that would enable the user to simply write the following?

```jsx
import { Head } from 'vike-solid/Head'

function Movies() {
  // Fetch data
  const data = useSomeDataFetchingTool()

  // Render UI and <head> tags
  return (
    <Head>
      <meta property="og:image" content={data.previewImage} />
    </Head>
    <ul>{
      data.movies.map(({ title }) => (
        <li>{title}</li>
      ))
    }</ul>
  )
}
```

**Comment by ryansolid** [comment]
> But, in principle, if the wrapper synchronously returns null then Solid could interpret this as "ignore children". Although, if the hydration error is currently shown synchronously, this would require the hydration error to be shown asynchronously in the next tick.

Yeah that's too late unfortunately.. the problem is this destructuring renders the children:
```js
function Head({ children }) {}
```
Before we even get a `null` return or anything. There is no VDOM with Solid so like you use props.children.. well you've rendered children. 

Ideally the Head component would just not render anything inline ever. I'm gathering that stuff gets inserted in the head. I think though hydration Id's would still get messed up here because of the sequencing. We handle Asset rendering a little differently in @solidjs/meta it relies on `useAssets` which pull things outside of this whole loop. 

With streaming this whole topic in general is a pain to deal with for anyone and I think should eventually be handled by the core render libraries themselves. Like something you'd import from `solid-js/web`. We've been making do with our meta library so far but it took some doing. I intend to introduce core primitives to make handling automatic.

**Comment by brillout** [comment]
Indeed, [removing the destructuring](https://github.com/vikejs/vike-solid/pull/104/commits/99a72b9adc603e1d9fa17bb3a4b843a31e07eccc) solves the issue.

> We handle Asset rendering a little differently in @solidjs/meta it relies on `useAssets` which pull things outside of this whole loop. With streaming this whole topic in general is a pain to deal with for anyone and I think should eventually be handled by the core render libraries themselves. Like something you'd import from `solid-js/web`. We've been making do with our meta library so far but it took some doing. I intend to introduce core primitives to make handling automatic.

Sounds good!
