### ISSUE TITLE
Initializing multiple stores with same object

### ISSUE THREAD

**Issue by amiralitaheri** [solidjs/solid#2254]
### Describe the bug

Using one object to create multiple stores cause them to be coupled and change together.
For example in the code below when the color of one simple block changes, the color of all simple block change. Because we are initializing the stores with the same object `defaultState`.
Only by deep cloning the `defaultState` the problem would be solved.

```jsx
const defaultState = {
  backgroundColor: "red",
};

const SimpleBlock = () => {
  const [text, setText] = createSignal("");
  const [store, setStore] = createStore(defaultState);

  createEffect(() => {
    setText(`Click to change the color! My color is ${store.backgroundColor}`);
    // PS: The createEffect always changes the text, but the console.log triggers randomly.
    console.log(store.backgroundColor);
  });

  return (
    <div
      style={{ "background-color": store.backgroundColor }}
      onClick={() => {
        if (store.backgroundColor === "red") {
          setStore("backgroundColor", "blue");
        } else {
          setStore("backgroundColor", "red");
        }
      }}
    >
      {text()}
    </div>
  );
};
```

### Your Example Website or App

https://codesandbox.io/p/devbox/solid-createstore-wnscmw

### Steps to Reproduce the Bug or Issue

Go to codesandbox link provided and click on the boxes.

### Expected behavior

I'm not sure that this is a bug or the expected behavior, because all the examples in [docs](https://docs.solidjs.com/reference/store-utilities/create-store) create the initial state directly in store and don't use a variable.
But as a user I would loved to have some warning about this behavior, because debugging it is hard.

### Platform

not platform specific

**Comment by maciek50322** [comment]
It's expected behaviour. Store only "wraps" your object in proxy, so it can be used reactively. It doesn't do much else when creating the store. So here you "wrap" one object multiple times and the wrappers work with original object. 
Performance and memory wise it's useful for stores to not make a copy of given object, it's rarely needed and it allows managing shared state, so that's left for programmer to decide whether to reuse the object or copy it.

In the new docs I could find it mentioned that it uses proxies. The old docs & tutorial mentiones wrapping the initial state in proxies.

new docs:
(from your docs link at the bottom of page, there's link named "Stores Guide")
https://docs.solidjs.com/concepts/stores#creating-a-store

old docs:
https://www.solidjs.com/docs/latest/api#using-stores
https://www.solidjs.com/tutorial/stores_createstore

**Comment by amiralitaheri** [comment]
@maciek50322 Thanks for your explanations.
Yes, the docs says that it uses the proxy but never mentions that it doesn't copy the initial state, or it doesn't explicitly say that it wraps the initial state in a proxy.
I just thought mentioning that somehow could save a lot of time for newcomers.

**Comment by mdynnl** [comment]
> I just thought mentioning that somehow could save a lot of time for newcomers.

@amiralitaheri Yes, that'd be very helpful and feel free to make some effort [here in discord server](https://discord.com/channels/722131463138705510/861229287868858379)

**Comment by amiralitaheri** [comment]
@mdynnl I will close this and create a pull request or issue on the docs repo as soon as I can.
