### ISSUE TITLE
Cant set "open" attribute using Dynamic

### ISSUE THREAD

**Issue by kapilpipaliya** [solidjs/solid#2268]
### Describe the bug

Can't set the `open` attribute using Dynamic.

### Steps to Reproduce the Bug or Issue

```typescript
function Button() {
  return (
    <Dynamic component="button" open>
      {count()}
    </Dynamic>
  );
}
```
In this example, open attribute is not added to the button

### Expected behavior

open property should be added to the button element

**Comment by ryansolid** [comment]
It's because `open` is a boolean attribute so we set it as a property to properly handle set/removal. You should be able to see that through a ref: https://playground.solidjs.com/anonymous/fa376f4c-d757-4360-b8ec-0d7262007f4d

That being said `button` doesn't have `open` as a supported attribute anyway. If it had it would have been reflected I believe. If you want to force it you can use `attr:open` but then it won't function as a boolean. That being said that might be fine because `button` doesn't have an `open` attribute. https://playground.solidjs.com/anonymous/bd32204b-e8cc-4bec-8d0e-496f796bcaa1

**Comment by kapilpipaliya** [comment]
@ryansolid Thanks for the solution. I was using this modal component https://daisyui.com/components/modal/
It adds the open attribute to open the modal.
