### ISSUE TITLE
Hydration error using nested conditional anchor links

### ISSUE THREAD

**Issue by ryoid** [solidjs/solid#2274]
### Describe the bug

Nested conditional `<a>` links causes hydration errors. 

```tsx
<a href="/cell">
  <div>
    <a href="/cell/link/A">A</a>
    <Show when={true}>
      <a href="/cell/link/B">B</a>
    </Show>
  </div>
</a>
```

### Your Example Website or App

https://stackblitz.com/edit/github-dsb6uo?file=src%2Froutes%2Fexample2.tsx,src%2Froutes%2Fexample3.tsx,src%2Froutes%2Fexample1.tsx

### Steps to Reproduce the Bug or Issue

1. go to `/example1` route

- `example1.tsx` throws error `Hydration Mismatch. Unable to find DOM nodes for hydration key: 0000000010000000001`
- `example2.tsx` throws error `Cannot read properties of null (reading 'childNodes')`
- `example3.tsx` throws error `Cannot read properties of null (reading 'firstChild')`

### Expected behavior

Render without errors or 

### Platform

- OS: macOS/Windows
- Browser: Chrome

### Additional context

In my codebase the error I experienced was `Cannot read properties of null (reading 'nextSibling')` with a table row link. Upon searching I realised that nested anchor links are not actually valid, so I am not sure if this should be supported or not. But this does not error without a `<Show>`. Nevertheless a more descriptive error message would be nice as it was hard to trace this issue.

**Comment by ryansolid** [comment]
The issue is nested anchors are illegal in HTML. We can't guarantee the output will work properly when cloned as the browser will try to fix this. Is is possible that some solutions get around this when creating them one by one, but this is invalid markup. Because it is not an immediate descendant it seems to be getting past our detection but we can't do anything about the browser automatically fixing this sort of thing and breaking our walks.

Maybe this issue can help.
https://stackoverflow.com/questions/18666915/why-are-nested-anchor-tags-illegal
