### ISSUE TITLE
`<Show>` breaks reactivity when passing a function that doesn't return a tracking scope

### ISSUE THREAD

**Issue by JonahPlusPlus** [solidjs/solid#2324]
### Describe the bug

I expect reactivity to work with any type that acts as a JSX element, not just JSX itself.
However, when working with Show, I noticed that reactivity breaks when returning values from a function passed to `children`. In order to fix it, it's necessary to surround the output with fragment JSX.
This can be fixed by adding a fragment into `<Show>`'s source ([just around the call for `child`](https://github.com/solidjs/solid/blob/main/packages/solid/src/render/flow.ts#L126-L133)) in order so there is a tracking scope, or make it so the compiler is smart enough to recognize reactivity with JSX types (IDK how).
Funny enough, ESLint warns about this (I played around with `<Show>`'s implementation in the playground).

### Your Example Website or App

https://playground.solidjs.com/anonymous/06da5283-3cda-4ee9-a37c-51c0c07959b0

### Steps to Reproduce the Bug or Issue

1. Go to playground link
2. Start typing in the input
3. Notice that only a single character is printed
4. Change `v()` to `<>{v()}</>`
5. Try typing again and see that it works

### Expected behavior

As a developer, I expect it to not require fragment JSX to work.

### Platform

- OS: Windows
- Browser: Firefox
- Version: 130.0.1

**Comment by ryansolid** [comment]
This is by design. Having it track is the easier thing to happen, but much like components we chose to have render functions from control flow untracked. It is essentially for the same reason. One might have actual DOM elements being created here and having the whole function rerun would be wasteful. If you are looking for the whole block to rerun on change you can make the Show keyed with the prop. But in general this is behavior we are trying to avoid.

`v()` and `<>v()</>` are not semantically the same from our perspective. The first is a value and the second a fragment with a bound expression. Technically `v` the signal is closer to equivalent but we also made a deliberate choice to have TS complain in this case because while the underlying renderer could handle it, any random component might not. It also better enforces the bind by value convention we promote.

**Comment by JonahPlusPlus** [comment]
@ryansolid I see (I had a feeling that performance was behind this). Then it would be nice to have changes to the type system and perhaps more documentation on `<Show>`'s page.

When I see that both `v()` and `<>{v()}</>` are `JSX.Element`s, personally, I am led to believe that they are interchangeable (since there is no type distinction here between untracked and tracking). Perhaps the type of `<>{v()}</>` could become a new type like `JSX.ReactiveElement` or `JSX.JSXElement` and the definition of `JSX.Element` be altered to included it? Then at least one can get the sense of there being some semantic difference just by looking at the types.

**Comment by ryansolid** [comment]
`v()` satisfies JSX Element because it is function that is being called that returns a string. The fact that calling that function accesses reactivity or not has nothing to do with it. We aren't returning reactivity or not. We are returning a string or a fragment. I don't think TypeScript helps us here.

The trickier part is it isn't obvious here that we default processing callbacks passed to JSX as non-tracking. Event Handlers/render props etc... I believe this is documented but maybe not in the right way.

Again the return type isn't going to tell you this. There is a difference between passing a callback into JSX(ie a function reference) and calling a function inside JSX. The latter depends on the parent scope to track and from a TS perspective just passes the value.

**Comment by JonahPlusPlus** [comment]
But JSX creates subscribers right, so isn't there a way of communicating that side effect to users via the type system instead of relying on documentation?

My problem seems to be that I didn't understand the difference in reactivity between components that had `children` that were `JSX.Element` vs `() => JSX.Element` (I just assumed that since the first (generally) provided a tracking scope that the second did as well, but I see now it works only for the function itself i.e. `{toggle() ? (v => <>A: {v()}</>) : (v => <>B: {v()}</>)}`).

So maybe revised documentation is the solution. Also, thanks for your time on this and for being patient with me.
