### ISSUE TITLE
Effect + createRoot are not consistently repeated many times

### ISSUE THREAD

**Issue by MateuszDev96** [solidjs/solid#2349]
### Describe the bug

I create main root, add effect, create another nested root (as this can allow the main root to escape) and under this I create another effect but as many times as I press ‘update text’ I get different results. I understand quite deeply how this reactivity engine works (I have mine for my needs) + I have checked yet https://github.com/vobyjs/oby and only in SolidJS this bug occurs

### Your Example Website or App

https://playground.solidjs.com/anonymous/33443199-f39a-4d2e-9b1a-5b20be5fb0bd

### Steps to Reproduce the Bug or Issue

1. Go to https://playground.solidjs.com/anonymous/33443199-f39a-4d2e-9b1a-5b20be5fb0bd
2. Click "update text" many times
3. Results should be same for each click but it isnt

### Expected behavior

Results should be same for each click

### Platform

- (Brave) Version 1.71.118 Chromium: 130.0.6723.70 (Official version)  (64-bitowa)

**Comment by ryansolid** [comment]
It might be worth pointing out the console.log in the actual browser differ from what is being showed in the playground. The example doesn't release the nested Routes so it keeps accumulating more effects that keep logging more and more "calculating". So you click it once it shows up once, twice it shows up twice and so on. The other thing I'm noticing is that the order does drift over time but I think that is due to how we optimize the deps. We have no guarantee on parallel effects.

If there is an example which properly cleans things up I think maybe we can make more assumptions about the correct behavior should be. But looking at this it appears to be reasonable given the memory leak being created.

**Comment by MateuszDev96** [comment]
It is quite confusing that the playground behaves differently from the actual browser

Yes, I notice that too, rder of the effects is different, this should not be case, often the logic of the rest of the application depends on the order of these effects. This behaviour can lead to errors and in addition is not obvious like the issue someone once reported when createEffect is created without createRoot in which the order of execution is also different than when creating with createRoot

**Comment by ryansolid** [comment]
> It is quite confusing that the playground behaves differently from the actual browser
> 
> Yes, I notice that too, order of the effects is different, this should not be case, often the logic of the rest of the application depends on the order of these effects. This behaviour can lead to errors and in addition is not obvious like the issue someone once reported when createEffect is created without createRoot in which the order of execution is also different than when creating with createRoot

I'm gathering the playground is trying to dedupe comments or something. I'm not sure why it does that.

I remember the issue around effects being scheduled different inside and outside of roots. That had to do with the fact of using microtask queues there versus not since roots also act as sync scheduler and we don't have the same means without them.

That being said the way deps are managed in the current reactive system leads to it being possible for effects to execute in different orders (although computation will execute before anything that depends on it). The lack of that guarantee might be awkward but it is very much by design. It might not be desired behavior but it is also not a bug.

**Comment by titoBouzout** [comment]
Relying on the order of how things run is an antipattern. What we should rely on is on derivation.

Things may depend on many values, and these values will change at different times triggering different codes paths (lets say skipping re-running a memo that didn't change).  How dependencies are resolved could and will change depending on what seems to be efficient. In fact, I would say it would be nice if there were some randomness, so we learn sooner than letter to not rely on the order.

**Comment by MateuszDev96** [comment]
This is how I understand it, but don't you think that calling the same code without changing the parameters returns different results? I'm only referring to the case I described and for me it's an antipattern

**Comment by MateuszDev96** [comment]
As for me the topic is closed because in the real case (browser not a playground) solid-js behaves correctly, the order of calling effects that are disconnected from root can be a problem but it is repeatable (on a playground not!).  

In my implementation it looks like the screenshot, all the logs are at the top in the stack and what is created as a ‘runaway’ and executes on then goes to the very bottom and is not split in the stack like in solid-js. Maybe I'm clinging but I like to have predictable and consistent code

<img width="944" alt="Custom Implementation" src="https://github.com/user-attachments/assets/982ed7d2-a2e7-4cce-af8f-d051932f9984">
<img width="932" alt="SolidJS Implementation" src="https://github.com/user-attachments/assets/7d14aeae-8311-4b4a-912e-e36d9786deff">

**Comment by titoBouzout** [comment]
> This is how I understand it, but don't you think that calling the same code without changing the parameters returns different results?

The basic principle is that everything is derived, so you will always reach the same result. How to reach there is an implementation detail that more or less follows a pattern, but relying on that pattern is not relying on the actual thing: deriving values.

I sympathise because I also like consistency a lot, but the order of effects is something that eventually will cause problems. Besides not intended to be used that way, there are some concerns with dependency resolution on which the order that dependencies are resolved could improve performance avoiding re-evaluations (therefore changing the order as it considers best).  The "diamond problem" comes from time to time, I do not have a link at hand to give you to understand it better, but I found a quote that illustrates it pretty nicely:

>  is there a way to force reactions to be triggered in breadth-first rather than depth-first order? Say I have a signal A, and two memos B and C which both depend on A - and then another effect D which depends on both B and C. Now, D is very expensive to compute, so I want to ensure that both B and C are resolved before D runs. Otherwise, because of eagerness, D runs twice, once because of B and once because of C.

**Comment by titoBouzout** [comment]
Here is some sample code 
https://playground.solidjs.com/anonymous/53c7309d-29f9-4fa3-ab8f-7b2c88371aa8
Courtesy of https://discord.com/channels/722131463138705510/1257884630493958224/1257885876503969802

```js
  const [a, setA] = createSignal(1);
  const b = () => a() + 1;
  const c = () => a() < b();
```

You have A, B and C.
B depends on A
C depends on A and B
If you change A, then B updates, and C updates
If you change B, then C updates

The most efficient way would be to evaluate first A, then B because you already know it only depends on A, and leaving C for last, as you know it depends on both A and B.

Trying to evaluate C as soon as A changes, will mean you will run C, and then you will run B (as A changed), to then run again C (as B changed).
 
[just an illustration]
