### ISSUE TITLE
jsx intrinsic elements style property key cannot use LowerCamelCase

### ISSUE THREAD

**Issue by yuzhen1024** [solidjs/solid#2379]
### Describe the bug

Issue title

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

```js
function Component() {
  return (<div style={{
    // zIndex: 3000,  // Cannot compile correctly
    'z-index': 3000,  // ok, But is no syntax completion hint
  }}></div>)
}
```

### Expected behavior

![图片](https://github.com/user-attachments/assets/2b93de3b-9b8e-46a3-8b56-a878caca349d)
This, can use.

### Platform

-

### Additional context

"solid-js": "^1.9.3",

**Comment by ryansolid** [comment]
Not supporting camelCase is by design because it could never be just a compiler mechanism we'd need to support it at runtime which brings a bunch of transformations. We use element.style.setProperty instead of just `Object.assign(element.style)` which uses camelCase versions. By writing the dash case version using `setProperty` our style attribute also supports things like CSS variables and it is consistent with SSR which just outputs strings.

But I've never seen the types/completion have issues before. Our playground(https://playground.solidjs.com/) seems to completing properly. Is it possible React types are getting pulled into your editor?

**Comment by yuzhen1024** [comment]
> But I've never seen the types/completion have issues before. Our playground(https://playground.solidjs.com/) seems to completing properly. Is it possible React types are getting pulled into your editor?

Yes, completion hints work correctly.
Now I have found the cause of the problem, because I am not using `jsconfig.json` in my project.
