### ISSUE TITLE
`splitProps` does not reactive to empty field

### ISSUE THREAD

**Issue by zhaoyao91** [solidjs/solid#452]
**IMPORTANT: If you have a question or an idea for a new feature use Github Discussions instead**

**Describe the bug**

I use `sliptProps` for some state object. some key like `b` is not on the state yet, but will be added later. but the splitted props does not reactive to the coming b field.

**To Reproduce**

see [playground](https://playground.solidjs.com/#NobwRAlgJmBcYA4DsBmANhg1gdwOYFsAjABggBcBnAO2wEMoyA2NMAGjCtvwFM4x9aEKmzBkAngAde8SgA8RFAPYBXAE4BjaZHwTFqsgAIQB1dypRuqgwF8DAM1WL8BgORK00ALQArCgHpsbkIXAG4AHSoIHT1DY3VTWjJuAGUyRO5WAwoJDzIABUcJCkz47nSAUTs7bnVDWwcnV3cvX1CIiLtlKlqIRSoDAGEVKiTVAAoASiMIgwN1PopDYEX0zIpuMlT0gF0DAF45hKStpLGQWlgDAEYSy5RrCfb+uYWlihusgCZdg+zcgsURTGKySmWALloLkyLmC20eVBmhzKSUq1VqY0m+wAfNNnrN5lR3NwAHRoRS4MYQqFZK7E2jw2YPJ74o7cVE1MgYqZ7HEgRH4haKNAkskUmHU97EwgMmzwxHrMgASRGlgAbrQ0FzsbjZrMFSduGd+bqLlk0kk6QBqG7G2aES4gkm0a3GpnPayZK7Eb1y56mMhqfpjY1UZQYRETcJUaxPUzmSxankGAA8Qy6owMfixmSginUyh4I2JuA25WFhbIACExIqoJTaBIJC4JvCwNZtkA)

**Expected behavior**

both a and b are logged, but only a is logged

**Comment by ryansolid** [comment]
Yep... I was being lazy with my proxies opting for lighter getters where I thought possible.. the `others`(s2 in your example) would work fine but not the defined ones. I see now they all have to be proxies. Thanks for pointing this out.

**Comment by ryansolid** [comment]
I was wrong. I can do this without proxies. The problem was to reduce indirection I was using property descriptors to copy them across but even on state which is dynamic if the property hasn't been defined it won't end up in the descriptor list. The solution is just to create a description in these cases since it is clear the end-user will be listening to that location. While for non-state, like say props which do not include spread state, this is a pointless extra property that will never update the overhead is minimal. And for state also minimal. It creates an extra closure that could have been avoided in some cases if it were predefined but it's a fine tradeoff for not having to go double nested proxy here.
