### ISSUE TITLE
Using <For /> to Generate children of Component

### ISSUE THREAD

**Issue by jcuenod** [solidjs/solid#494]
I have a component that expects to receive a `[children]` array and interleaves them with other elements. In the parent, it sometimes makes sense to create the children with a `<For each={children} />`. The problem is that I'm getting a signal passed into the component now instead of an array of children. How do I handle that?

I tried

```js
const children = typeof props.children === "function"
    ? props.children()
    : props.children
```

But this doesn't seem to be working.

**Comment by ryansolid** [comment]
Use Solid's `children` helper: https://github.com/solidjs/solid/blob/main/documentation/api.md#children

The problem is every time you access `props.children` you are recreating the children. If you wrap with children it will flatten out all nested reactivity and give you a signal you can work with.
