### ISSUE TITLE
Virtual Scrolling

### ISSUE THREAD

**Issue by knpwrs** [solidjs/solid#510]
Does the Solid ecosystem have any libraries to support virtual scrolling (ala [`react-cool-virtual`](https://github.com/wellyshen/react-cool-virtual), [`react-window`](https://github.com/bvaughn/react-window), or [`react-virtualized`](https://github.com/bvaughn/react-virtualized))? If not, are there any generic virtual scrolling libraries that work well with Solid?

**Comment by mosheduminer** [comment]
I don't think the ecosystem has such libraries yet, but there are some codesandboxes that are basically complete implementations (these were shared a while back on the solid discord by @rturnq ).
https://codesandbox.io/embed/virtualized-list-9dw9q
https://codesandbox.io/embed/virtualized-sheet-8fokq
https://codesandbox.io/embed/virtualized-table-ks63n

When using these, keep in mind that imports of `createState` from "solid-js" need to be changed to `createStore` from "solid-js/store" in order to work with the 1.0 release.
