### ISSUE TITLE
Inconsistent JSX rendering of &nbsp;

### ISSUE THREAD

**Issue by Brendan-csel** [solidjs/solid#541]
**Describe the bug**
Special characters such as `&nbsp;` render differently if enclosed in an intrinsic tag (eg div) versus a component.

**To Reproduce**
[Per this playground example](https://playground.solidjs.com/?hash=1088612595&version=1.0.0):
``` jsx
const CustomDiv = props => <div {...props} />;

function App() {
  return (
    <>
      <div>One&nbsp;Two</div>
      <CustomDiv>One&nbsp;Two</CustomDiv>
    </>
  );
}
```

...renders...

```
One Two
One&nbsp;Two
```

**Expected behavior**
```
One Two
One Two
```

**Additional context**
These characters can be handy as a lazy way to add space before or after text.  For example to space text from an icon inside a button.  We've been migrating components from React and suddenly started noticing these showing up on our pages.

**Comment by ryansolid** [comment]
I thought this would be straight forward but it isn't. See: https://stackoverflow.com/questions/37909134/nbsp-jsx-not-working

The problem is we use methods `textContent` to dynamically set text. This is both performant and handles escaping. But character codes like that will not work. `innerHTML` works but that is dangerous. What I can do is resolve the encoding so that it works for top-level static JSXText. However anything dynamically inserted should not use those and just use the characters directly.
For example:
```jsx
// this does what is expected:
<CustomDiv>One&nbsp;Two</CustomDiv>
// this does not 
<CustomDiv>One{"&nbsp;"}Two</CustomDiv>
// do this instead
<CustomDiv>One{" "}Two</CustomDiv>
```

**Comment by Brendan-csel** [comment]
Thanks Ryan.  

Coincidentally I was just doing some performance tests swapping out textContent for innerHtml on line 336 in [dom-expressions/src/client.js](https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/client.js). and yes, it was about 5 to 6 times slower.

It would be great if there was a way to handle to top-level case as that would cover of pretty much all the times we'd run into this.

**Comment by ryansolid** [comment]
Technically it's released but you might need to blow out your node modules/locks.. babel-plugin-jsx-dom-expressions 0.29.3  used by babel-preset-solid has the fix, I will bump up the preset when I do my next Solid release.

**Comment by MateuszDev96** [comment]
and when is the next release planned?
