### ISSUE TITLE
Binding a context to a component is not working correctly?

### ISSUE THREAD

**Issue by lyohaplotinka** [solidjs/solid#542]
### Describe the bug
I noticed the following situation. There is a context, there is a root component, and there is a component that will be nested in the root.
The entire application is wrapped in a context, but before placing the nested component, the context value needs to be updated, so we wrap it again.

The component does not output directly via JSX, but via a variable (signal). And here I found three different behaviors:

1. Through the onMount hook
In this case, the nested component is rendered with the "old" context value (from the root component), that is, the "wrapper" is ignored;
```javascript
const [component, setComponent] = createSignal<any>()

onMount(() => {
  setComponent(NestedComponent) // will be rendered with "old" context data
})
```

2. Via setTimeount
In this case, none of the versions of the context is detected at all, we see data from the default context value;
```javascript
const [component, setComponent] = createSignal<any>()

setTimeout(() => {
  setComponent(NestedComponent) // will be rendered with default context data (not old, but default)
}, 5000)
```

3. Via onMount or setTimeout, but passing an arrow function that returns a component
In this case, everything works as expected: we see an updated version of the context.
```javascript
const [component, setComponent] = createSignal<any>()

onMount(() => {
  setComponent(() => NestedComponent) // works as I expected
})
```

I wonder if this is a mistake and what path is conceived by the developers in such a situation?

### To Reproduce
Please see this [Playground example](https://playground.solidjs.com/?hash=-2135549165&version=1.0.0), I think it is more informative.

### Expected behavior
No need to pass arrow function

Thank you, I wish the project all the best!

**Comment by ryansolid** [comment]
Like React's `useState`, Solid's signals support a setter version:
ex:
```js
setState(previousValue => previousValue + 1) 
```
This means to set a function you have to use a function form otherwise it will mistakenly execute it like a setter. What this means is that in all examples except the last you are executing it immediately. In another words executing the Component function inline.

In the first example executing under mount executes it immediately under that context instead of where it should used so you are getting the context above instead of the intended.

In the second example you are executing in a setTimeout. The problem is that until you set a signal and get the ball rolling it won't resume the reactive context. So basically it is being executed outside and only finding the default.

The last example sets it properly which defers execution until where the Component is used and works as intended.

The Typescript types somewhat guard against this but all the runtime can do is assume it is the setter function form. So this is all functioning as intended.

**Comment by lyohaplotinka** [comment]
@ryansolid thanks, that sounds logical. However, now there is another question from the same series. If I pass a JSX element to the signal, then regardless of whether the arrow function is passed to setComponent, the component is rendered with the default context value

```javascript
setTimeout(() => {
    /**
     * We will see default context data in both cases
     */
    setComponent(<NestedComponent />)
    setComponent(() => <NestedComponent />)
  }, 1000)
```

[Updated playground](https://playground.solidjs.com/?hash=-1996566649&version=1.0.0)

**Comment by ryansolid** [comment]
More than likely both of those are equivalent. You are rendering it in a `setTimeout`. Neither that nor an event handler executes under a reactive scope. To think about it another way you are completely rendering it and then placing a DOM element in the signal.

I see 2 options here:
1. Pass a factory function. Ie.. just set the Component itself rather than the instance like you did in the original example 3 above. In that case where you consume it will create it in the right place. If you need to set props you could do this:
```js
setComponent(() => () => <NestedComponent someProp={something} />)
```
2. Use the signal to pass information that informs the control flow of the main execution of your component. Whether that is a lookup or trigger of some conditional logic. Something like the examples in the tutorial on the Dynamic Control flow: https://www.solidjs.com/tutorial/flow_dynamic

**Comment by lyohaplotinka** [comment]
@ryansolid, thanks a lot for the explanation, I close the issue.
