### ISSUE TITLE
Remaining phantom updates

### ISSUE THREAD

**Issue by cynecx** [solidjs/solid#552]
**Describe the bug**
Phantom updates still occur (See the related discussion at https://github.com/solidjs/solid/discussions/505, even after the recent fix)

**To Reproduce**

https://playground.solidjs.com/?hash=-1391246675&version=1.0.0
https://gist.github.com/cynecx/1cc32b7b2eafc47d8b696cdfd518056b

To reproduce, add some nodes, then click reset.

**Expected behavior**
The `Expand` component should not be updated when its parent should've disposed that component.

**Comment by ryansolid** [comment]
Yeah I see it. This issue is specific to the array helpers. Nested roots are not properly tracing upwards. This is is a tricky one. The current implementation for tracing came out of a different bug fix so I need to make sure that I fix this and won't break that one either. I need a better general solution for this case.

**Comment by cynecx** [comment]
Thanks for looking into this. I've tested this out on my actual code base and it doesn't seem fixed. However the reproduction seems to be fixed. I am currently trying to extract a reproduction case :/

**Comment by cynecx** [comment]
Okay. Reducing the code to something small and reproducible was harder than anticipated.

https://playground.solidjs.com/?hash=-1903645007&version=1.0.2
https://gist.github.com/cynecx/d58f4f1b1387c24182157b36e27e38f9

To reproduce: Click "Load" -> "Add Button" -> "Load"

**Comment by ryansolid** [comment]
I really appreciate it. These are really hard to track down. And I thought I had nailed the generic case with the last case. Most of the problem is that in attempts to optimize I've been cutting out necessary behavior. It's really easy when I am missing cases to have optimizations break certain behavior.

**Comment by ryansolid** [comment]
Ok I see it. I walk up to check potentially stale owners. However, I was just going up to the topmost one. This works in most cases as they are shallow. But if the topmost doesn't actually cause the disposal (it's a false alarm) it continues on its way. And we run into the error.

I actually need to resolve all the potential ones down the tree. I figured out a quick fix but want to look at how to optimize this more given the implications on the core. Thank you so much for helping me find this case.

**Comment by cynecx** [comment]
Thanks a lot! I really appreciate it. The most recent release (1.0.3) seems to have fixed our production code :)

**Comment by ryansolid** [comment]
That's great to hear. And this exploration also led to a slight improvement in reactive update propagation performance.
