### ISSUE TITLE
observable -> Cannot read property 'isStopped' of undefined

### ISSUE THREAD

**Issue by Gavin-Gong** [solidjs/solid#554]
**Describe the bug**
try to use solidjs's `observable` and rxjs's `from` operator for converting a signal to stream, but got a little error。
It looks like solid’s `observable` cant adapt rxjs's observable interface。

![image](https://user-images.githubusercontent.com/9414378/125233293-d48e2780-e310-11eb-9e64-356261e1b0f2.png)
![image](https://user-images.githubusercontent.com/9414378/125233317-deb02600-e310-11eb-824f-8bbdc1af1f9b.png)

**To Reproduce**
just run the following code
```tsx
import { from, Observable } from "rxjs";
import { observable, createSignal, onMount } from "solid-js";

function App() {
  const [getText, setText] = createSignal("Hello Solid");
  onMount(() => {
    setInterval(() => {
      setText(new Date().toLocaleTimeString());
    }, 1000);
  });

  // workaround
  new Observable((sub) => {
    observable(getText).subscribe((v) => {
      sub.next(v);
    });
  }).subscribe((v) => {
    console.log("new Observable", v);
  });

  // bug
  const text$ = from(observable(getText));
  text$.subscribe((v) => {
    console.log("from operator", v);
  });

  return <div>{getText()}</div>;
}

export default App;
```

**Expected behavior**
work without any errors

**Reproduction**
repo
https://github.com/Gavin-Gong/solidjs-observable-reporting 

**Additional context**
maybe we could add some description of `observable`' `subscribe` method in documentions?

**Comment by ryansolid** [comment]
Hmm.. that's interesting. The idea is any object that uses the that has the observable symbol and returns a subscribable should work with `from` but that is library agnostic. I followed this: https://github.com/tc39/proposal-observable
RxJS is supposed to work with this but I can see the Types not being wise to it.

The TypeScript errors probably just need to be forced. It makes no sense to implement RxJS interfaces. However the isStopped error seems real. I just have no idea what that is as it isn't part of our internals or your app code. Maybe RxJS has newer docs about interfacing with TC39 spec observables.

**Comment by Gavin-Gong** [comment]
>  It makes no sense to implement RxJS interfaces.

@ryansolid Agree with your point . Hmmm, I think we could adjust the documention to close this issue. 
![image](https://user-images.githubusercontent.com/9414378/125236247-38ffb580-e316-11eb-9e67-8870fb258ae6.png)

**Comment by ryansolid** [comment]
I suspect looking around will find the issue. Something on the RxJS side since they are supposed to support this. Others have successfully made libraries around this using RxJS. Maybe they know something we do not know. Like I've had discussions like: https://github.com/solidjs/solid/discussions/410

So to my knowledge, this all works. Integrating with RxJS is the common case..

**Comment by Gavin-Gong** [comment]
Finally, I implmented a  rxjs custom operator to solve my problem. Code looks a little silly. 😃
```ts

function fromObservablePattern<T = unknown>(observableLike: any) {
  return new Observable<T>((sub) => {
    observableLike.subscribe!({
      next: (v: T) => sub.next(v),
      error: (v) => sub.error(v),
      complete: () => sub.complete(),
    });
  });
}
```

``` ts
import { observable, createSignal, onMount } from "solid-js";
function App() {
  const [getText, setText] = createSignal("Hello Solid");
  onMount(() => {
    setInterval(() => {
      setText(new Date().toLocaleTimeString());
    }, 1000);
  });
  fromObservablePattern<string>(observable(getText)).subscribe((v) => {
    console.log("custom operator", v);
  });
  return <div>{getText()}</div>;
}

export default App;

```

**Comment by ryansolid** [comment]
I'm glad that works, but legitimately confused as that is the whole point of TC39 compat. I used to use Zen Observable (internal to Apollo to test this) It's been a while since I pulled out RxJS, but everything I read suggests this should still work. Like this one: https://ncjamieson.com/how-to-use-interop-observables/. If you were going to need to do all this it would be sort of pointless including the observable helper in the library.

**Comment by Gavin-Gong** [comment]
@ryansolid  I mean if the sample code in the document does not work, it could be described more clearly to prevent misleading user like me.😁
On the other hand, Totally agree with your point. If rxjs is not fully implemented in accordance with the TC39 spec, also we do not need to adapt rxjs's implmention. Hmmm..  I learned a lot about Observable from your patiently reply.

**Comment by ryansolid** [comment]
I think we are misunderstanding each other. It is supposed to work and I'm confused why it doesn't. RxJS is supposed to work with TC39 spec and everywhere I look/read it claims it works. In so, the documentation should be correct and I'm confused why it doesn't work. The fact it doesn't work is troubling. There must be a missing step, maybe something missing from the documentation or some change RxJS that makes this no longer work. In either case I want to get to the bottom of it, since we shouldn't need to change anything on our side but something is clearly missing.
