### ISSUE TITLE
Hydration fails with use of `Dynamic` and fragments

### ISSUE THREAD

**Issue by pablo-abc** [solidjs/solid#581]
**Describe the bug**
Hello, I am working on this PR for Astro regarding the Solid renderer: https://github.com/snowpackjs/astro/pull/848
Currently it is using `render` to replace its children but I am trying to use `hydrate`. I've encountered two issues with it and I don't know if anyone here would have an idea of why they're happening:

1. If the parent component is a fragment with more than one children, the component does not get hydrated at all.
2. If there's a `Dynamic` component anywhere it fails with `Uncaught (in promise) TypeError: can't access property "length", current is undefined` from `insertExpression solid-js.web.v1.0.4.js:374` but _only_ if `Dynamic` has more than one child component.

**To Reproduce**
I've found this issue when working with `Astro`'s repo, I've made a branch with the issue.
The example Solid code is at: https://github.com/pablo-abc/astro/tree/hydration-solid/examples/framework-solid
The configuration for Solid is at: https://github.com/pablo-abc/astro/tree/hydration-solid/packages/renderers/renderer-solid

When I have some more time I can try to make a smaller repo with the issue.

**Expected behavior**
Should hydrate the component without any errors

**Additional context**
Since I don't have access to the whole HTML in the server side, I am adding the `hydration script` per component on the server side while looking for a better alternative.

**Comment by ryansolid** [comment]
Thanks for reporting. I will try to take a look soon. I'm a bit shocked to find out it uses `render` in the client. I hope we can do better but I suspect I will have to spend some time here. I don't see anything wrong with the compiled output so this is probably more nuanced and take some looking.

**Comment by ryansolid** [comment]
Ok I figured it out. 2 things:

1. Fragment is broken because of Hydration Marker mismatch. This is because you are importing the client version of `createComponent` on server render. Change this line: https://github.com/pablo-abc/astro/blob/hydration-solid/packages/renderers/renderer-solid/server.js#L1
to:
```js
import { createComponent } from 'solid-js/dist/server.js';
```
2. Dynamic components are actually really tricky with Hydration in that there is no mechanism to create a dynamic native tag in the compiler. So right now while the children are preserved and hydrated we always end up recreating the tag itself if it is native element(Components work fine). It ends up receiving the children then replacing the server rendered node. Not a huge deal as it's a single DOM node, but there is a check against existing DOM children during hydration that assumes they're present which they aren't in this case. I just am missing a null check. I will get that fixed up.

**Comment by ryansolid** [comment]
I'm curious what the plan is here. Is the intention to make a PR back into Astro? Now that I see what is going on I would like to see this happen as just re-rendering in the client is really wasteful.

**Comment by pablo-abc** [comment]
Hey, @ryansolid! My plan was to get this figured out and update my PR to Astro. But it ended upsetting merged without any more comments. 😅

Thanks for your help! I agree that just re-rendering is quite wasteful, I'll try this locally and post a PR if I can make this work.

The biggest issue regarding this is that there seems to be no way to add something _just once_ to the document with the current API. So for now I was adding the `generateHydrationScript` output to each component rendered by Astro which adds a `<script>` tag next to each hydrated component. 

I was digging through `dom-expressions`'s source code and I couldn't quite figure out if, for Astro's use-case, it'd be needed for the hydration script to be _generated_ or if I could just add the output to a `.js` file and call it at the top.

**Comment by ryansolid** [comment]
Need to test it. For synchronous rendering it is probably fine as long as the script executes first. But if it is async i imagine this doesn't work properly anyway since serialized data is per render and it is overwritten in the browser or missing depending on the case. The server is async safe but I didn't anticipate the browser needing to be so there is work to be done there. But that suggests multiple scripts regardless. Probably with options to namespace.
