### ISSUE TITLE
`classList` optimization

### ISSUE THREAD

**Issue by visualfanatic** [solidjs/solid#584]
When I was looking through `babel-plugin-optimize-clsx` readme I noticed how it optimizes:
```js
const x = clsx({
  btn: true,
  'btn-foo': isDisabled,
  'btn-bar': !isDisabled,
});
```
... into:
```js
const x = 'btn ' + (isDisabled ? 'btn-foo' : 'btn-bar');
```

Solid has pretty sweet `classList` prop which is compiled to `classList.toggle()` calls for client side and to `ssrClassList` on server side. I was wondering if it would benefit the performance without any downside if only dynamic values would be compiled to `classList.toggle()`/`ssrClassList` and the rest left as a static `class` attribute. What do you think?

**Comment by ryansolid** [comment]
I'm not sure we'd have to test. Because in one case we toggle a single class versus recomputing the string. In the case of style attribute, the former is definitely faster, but not sure it is the same with classes. clsx doesn't have the benefit of direct DOM access which could easily explain this.

On the server though it would benefit as all we are doing is concatenating strings and it's a form of loop unwinding. classList helper on the client is a fallback for some dynamic scenarios which aren't present during SSR so I imagine the ssrClassList helper could just be replaced.

**Comment by ryansolid** [comment]
I've done the SSR side of the optimization. Client-side is a bit more complicated since it wasn't already being merged as classes.

**Comment by ryansolid** [comment]
Implemented this finally.
