### ISSUE TITLE
Input element readonly attribute works strangely

### ISSUE THREAD

**Issue by galchenkov** [solidjs/solid#594]
Example:
https://playground.solidjs.com/?hash=-1101328069&version=1.0.7

In type definition we have two names: readonly and readOnly. readonly always fails to work. But readOnly works with true or null values (for removeAttribute). For example, disabled attribute works fine with boolean signal. For readonly need convert:
readOnly={readonly() ? true : null}. 

When server side rendered readOnly={false} will return readonly="" attribute and it will always be readonly input.

1. Maybe there is an error in the definition that readOnly is a BooleanAttribute?
2. Why we need two attributes readonly and readOnly?

Thanks.

**Comment by ryansolid** [comment]
Something is weird here. I thought it was a boolean attribute and treated it as such but that doesn't seem to be working properly. The camelcase version isn't being detected as the boolean property and being set as an attribute which sort of works except not in the false case since a "false" is still true. I probably should look at correcting the detection of that. 

But what is unexpected is why essentially `el.readonly = true` doesn't work.

**Comment by atk** [comment]
From what I see in the HTML standard, it's supposed to be a boolean attribute and not a property (https://html.spec.whatwg.org/multipage/input.html#attr-input-readonly).

Boolean attributes in HTML are usually set with their own name, but any string should suffice.

**Comment by ryansolid** [comment]
We compile all boolean attributes to properties since usually setting it with true and false behaves properly. With attributes you need to set to `null` as `false` becomes "false". I copied this mechanism from Inferno. It's just less code because there is no need for special casing, no runtime consideration. 

Ok I see the problem.. the attribute is "readonly" but the property is `readOnly`. I can just fix this by casing it properly.

**Comment by galchenkov** [comment]
> But what is unexpected is why essentially `el.readonly = true` doesn't work.

But el.readOnly = true|false work fine

**Comment by MarkChrisLevy** [comment]
Hi @ryansolid, fixing this issue for input caused an issue with custom element, that has readonly prop defined:
https://playground.solidjs.com/anonymous/388db506-50d3-485f-915f-2d9fd6143249

I think, that aliasing readonly to readOnly should be made only for ```<input>``` tag, as the spec doesn't define readOnly prop for HTMLElement.
