### ISSUE TITLE
Update store value in array in array bug

### ISSUE THREAD

**Issue by clinuxrulz** [solidjs/solid#603]
It seems like the view-state is not being updating when the value is being updated in an array in an array of a store.

playground example:
https://playground.solidjs.com/?hash=458727804&version=1.0.7

Then click cell 1,1 and press the delete key. You'll see the new table data being logged to the console (updated by the setState function returned by createStore). Yet the view showing the data did not update.

This could just be my miss-understanding of stores, do I need to reconstruct a new array for the row for the change to be tracked?

**Comment by clinuxrulz** [comment]
Also on line 267 in that example:
If I change:
```>{data()}</td>```
to:
```>{state.data[rowIdx][colIdx]}</td>```

Then it works. Am I meant to access the data from the root state object in the view render code?

**Comment by clinuxrulz** [comment]
My bad. No bug here. The outer use of Index already unwrapped the store so that the inner use of Index losses it's reactivity.

**Comment by ryansolid** [comment]
Hmm.. an interesting scenario. I see what's going on but I almost never use Index with Store's so I never hit this. Essentially Index uses its own signals to move things around but doesn't actually access the store under a tracking context. And just sets the value in the signal. This is fine in the shallow case since setting a value in an array triggers the parent. But when nested Index the parent is also not from the store. In so nothing actually subscribes the store itself, so when you set the store it gets missed.

This makes me think I should rethink the approach for `<Index>`.

**Comment by clinuxrulz** [comment]
I discovered the mistake i made. All good.

**Comment by ryansolid** [comment]
Yeah I mean it's fine but I also think it's not the most obvious behavior. May be worth at least considering doing something different. But glad we found the issue.
