### ISSUE TITLE
WARNING: computations created outside a `createRoot` or `render` will never be disposed

### ISSUE THREAD

**Issue by pheianox** [solidjs/solid#610]
# **Describe the bug**
Got a warning while creating modals using`<Portal>`.  

Like, I have a provider `<ModalProvider>` that  wraps my whole application just to share two functions `setModal()` and `removeModal()`. When you call the `setModal()` function and pass it a component, it will push that component to the `<Portal>` under the hood. Similarly `removeModal()` will just remove it from the `<Portal>`. 

When I push a modal I get this warning in the console. 

# **Expected behavior**
No warning in the console, cuz it makes me pee :)

# **Additional context**
> Sorry I cannot share some code, because the project is massive and has lots of solidjs components. 
> (Solidjs does great job! It will eventually take the place of React)

**Comment by ryansolid** [comment]
This doesn't give me a ton to go off of. I probably need to see a simple reproduction case. I can try a couple things when I get a chance. It's just any possible amount of things that would cause computation creation outside of a root. Some sort of async behavior perhaps.. creating a computation from an event handler without triggering via Signal.

**Comment by pheianox** [comment]
Got it. 

By the way, does Solid use `jQuery` under the hood? Just got a weird error from a file called jquery.min.js

**Comment by ryansolid** [comment]
Hah.. no. Check your extensions. Maybe run in an incognito window etc.

**Comment by ryansolid** [comment]
I know this isn't exactly your setup but I don't really know how to reproduce the issue. I will need a reproduction.

Here's what I was playing with: https://playground.solidjs.com/?hash=1814302839&version=1.1.0

**Comment by ryansolid** [comment]
Did you manage to resolve your issue?

**Comment by pheianox** [comment]
Nope, it still there. 

I'll try to make a small playground, kind of simulation of my project a bit later. Because the playground doesn't support custom html, I'll create a github repo for the test.

**Comment by pheianox** [comment]
Here's the repo https://github.com/pheianox/solid-modal-issue-test


### Get started quickly
```
git clone https://github.com/pheianox/solid-modal-issue-test.git
cd solid-modal-issue-test
npm install
npm run dev
```

**Comment by rturnq** [comment]
A likely culprit is the render call: https://github.com/pheianox/solid-modal-issue-test/blob/56ba024cdec633b57c02e55ba555282f08dbff96/src/index.jsx#L6

`render` should take a function that returns your root element instead of the component directly. Here is [an example](https://www.solidjs.com/guide#entry) from the docs.

**Comment by pheianox** [comment]
Unfortunately... still getting the warning. Something tricky is happening somewhere over there

**Comment by rturnq** [comment]
Ok, I cloned it and ran it locally. The issue is here: https://github.com/pheianox/solid-modal-issue-test/blob/56ba024cdec633b57c02e55ba555282f08dbff96/src/views/App.jsx#L6

Since `NotificationFromGod` is a function, when it is passed to the signal setter, it executes immediately as the function-form of the setter. This causes your component to run during the event where Solid isn't tracking. Change that to:
```js
function onOpenModal() {
  setModal(() => NotificationFromGod);
}
```

**Comment by pheianox** [comment]
Wow, exactly! NO WARNING. It was such an annoying thing, but now it's gone. Thank you! Thank you! Thank you!
