### ISSUE TITLE
Solid regular function components

### ISSUE THREAD

**Issue by amancoder28** [solidjs/solid#620]
Solid js regular function component dont accept the component type. But it is a really good thing to have.

`function App(props): Component {
      return <div> {props.children} </div>
}`

**Comment by ryansolid** [comment]
That's typescript I think. You are trying to accomplish the equivalent of this right:
```js
const App: Component = (props) => {
  return <div>{props.children}</div>
}
```
But what you wrote says that the function returns a `Component` rather than is a `Component`, which it doesn't. TypeScript not supporting typing functions like this is just a shortcoming of TypeScript. Same issue in React or any function component based system.

**Comment by modderme123** [comment]
I recommend using the `const` syntax, but you can also do `function App(props): JSX.Element`

**Comment by ryansolid** [comment]
As far as I can tell there is no action to be taken here. Thanks for creating the issue.
