### ISSUE TITLE
Asynchronous effects

### ISSUE THREAD

**Issue by Kestrer** [solidjs/solid#670]
It would be quite useful if Solid supported asynchronous effects. For example:

```tsx
function Loaded(props: { initialOption: boolean }) {
    const [option, setOption] = createSignal(props.initialOption);
    createAsyncEffect(async () => {
        await (await connectToServer()).setOption(option());
    });
    return <label>
        Option enabled:
        <input type="checkbox" checked={option()} onInput={e => setOption(e.target.value)} />
    </label>;
}
```

These asynchronous effects would:
- Guarantee that the closure passed to `createAsyncEffect` would never be run concurrently with itself.
- Not build up a backlog of unhandled updates, since old states aren't kept around so it would be pointless anyway.
- Track dependencies throughout the duration of it running.

What do you think?

**Comment by LXSMNSYC** [comment]
The thing about asynchronous callbacks is that the tracking context can never be resumed, which is problematic. Always take note that tracking context can only run synchronously before switching to its parent context.

Consider:

```js
doSomething(someDependencyA());
await doSomethingAgain();
doSomething(someDependencyB());
```

By the time `doSomethingAgain` resolves, the tracking context is no longer available and thus `someDependencyB` can no longer be tracked. There are work arounds however I don't think it's worth the merit. Besides, `createResource` already exists for our asynchronous needs.

**Comment by ryansolid** [comment]
> Track dependencies throughout the duration of it running.
This isn't possible as far as I've tried. This was one of my early thoughts on how to approach `createResource`. The problem is we need to set the global context on each resume. Async functions don't give us opportunity for that. Not in a clean way you'd be wrapping things and it would be a mess. I tried like having a custom promise wrapper, but even then the execution wasn't right.

Generators do what we'd want. So I explored Async Generators for a bit. The problem is tracking across start stop is weird business. I couldn't find a situation where it wasn't preferable to not track or break it into multiple computations. I'd be interesting to see what sort of things you were thinking of.

**Comment by atk** [comment]
I think we had something similar planned with createQueue in solid-primitives.

**Comment by Kestrer** [comment]
> The problem is we need to set the global context on each resume. Async functions don't give us opportunity for that.

You're right, I forgot you can't do that in Javascript. In that case, it might be better to only track at the start, since I think async functions are guaranteed to run eagerly. That would also help reduce race conditions in user code.

> I'd be interesting to see what sort of things you were thinking of.

Basically what I wrote in the initial post - I want the user to be able to modify settings with the UI that take immediate effect, and then they should propagate asynchronously to a more permanent storage in the background.

> Besides, `createResource` already exists for our asynchronous needs.

I don't think `createResource` would work for this use case, because `createResource` is more about asynchronously getting data and then updating the UI, rather than updating the UI and then asynchronously setting data.

**Comment by LXSMNSYC** [comment]
> I don't think createResource would work for this use case, because createResource is more about asynchronously getting data and then updating the UI, rather than updating the UI and then asynchronously setting data.

You can do it with createResource

```js
createResource(() => [name(), password()], async (args) => {
  await signIn(...args);
});
```

**Comment by ryansolid** [comment]
> You're right, I forgot you can't do that in Javascript. In that case, it might be better to only track at the start, since I think async functions are guaranteed to run eagerly. That would also help reduce race conditions in user code.

The other challenge here is we don't get to intercept between the promise chains. Like if you write `await await` like your example the caller gets a promise with all those `then`'s already chained. We have no way to cancel things in between. We can't stop the setter from being called. You'd need to wire that in your end user code.

If you remove both of those from the equation. Then you can pass in an async function into `createEffect` today and do this sort of thing.

```js
createEffect(async () => {
  let cancelled = false;
  onCleanup(() => cancelled = true);
  const connection = await connectToServer();
  if (cancelled) return;
  const options = await connection.doQuery();
  if (cancelled) return;
  setOption(options);
})
```
It's not pretty but I'm not sure with async functions alone we can do much else. By registering a cleanup we cancel the whole chain whenever the effect re-runs but it can resume at every point so you have to check.

**Comment by atk** [comment]
We could use an AbortController to intercept the async function, but we need to catch its error then.

**Comment by Kestrer** [comment]
> You can do it with `createResource`
> ```ts
> createResource(() => [name(), password()], async (args) => {
>   await signIn(...args);
> });
> ```

This doesn't prevent the callback from being called concurrently with itself. That opens the door to data races if e.g. the storage of an earlier value completes after the storage of a later value.

> We can't stop the setter from being called. You'd need to wire that in your end user code.

I wasn't actually expecting to want to cancel it - I think it would be better uncancelled, because that would avoid situations where continuous edits cause the data to never be saved.

**Comment by ryansolid** [comment]
> I wasn't actually expecting to want to cancel it - I think it would be better uncancelled, because that would avoid situations where continuous edits cause the data to never be saved.

You can do a similar trick with a counter to achieve that and then look at the latest committed number when new things complete to determine if it should write. The cancel was the easiest version. Same need to intercept before the setter to prevent the race conditions. All I'm saying is that you would need to intercept to prevent it from continuing short of doing something to reject the promise (like an Abort Controller), but to set that up the end user would need to wire that into promise creation in a way the primitive is aware of and we'd need to decide how to handle the rejection. Something like Abort Controller is standardized but other types of promises are not.

`createResource` does something similar to the cancel example in that it keeps track of the last created promise. Mostly that used with Suspense intermediate data isn't going to matter anyway since if another fetch is outgoing it's still suspending so it doesn't need to worry about throttling. In so while it aggressively cancels you should not have any race conditions.

> I wasn't actually expecting to want to cancel it - I think it would be better uncancelled, because that would avoid situations where continuous edits cause the data to never be saved.

This is sort of the problem. Because sometimes you want throttling and sometimes you want debouncing. And that determination in cascading cases like that can only be managed in the user side of the code anyway. What is really cool is with the primitive building blocks we have it is easy to create this in userland. So we're taking a more laid back approach to introducing more complex primitives since we don't need to do anything in the core to enable them.

They are doing some experimentation with building primitives around these ideas over at [solid-primitives](https://github.com/davedbase/solid-primitives). Which I think is probably worth checking out too.

**Comment by Kestrer** [comment]
Ah, so turns out I can implement this in user code:

```rust
function createAsyncEffect(fn: () => Promise<void>) {
  enum State { Idle, Running, Queued }

  const [registerEffectRerun, rerunEffect] = createSignal(undefined, { equals: false });

  let state = State.Idle;
  createEffect(() => {
    registerEffectRerun();
    if (state === State.Running) {
      state = State.Queued;
    } else if (state === State.Idle) {
      state = State.Running;
      void (async () => {
        await fn();
        const oldState = state;
        state = State.Idle;
        if (oldState === State.Queued) {
          rerunEffect();
        }
      })();
    }
  });
}
```

Given the opposition to this expressed, I think I will close this.

**Comment by ryansolid** [comment]
Yeah it isn't that object to the idea of it. Just that in general I'm taking the tact of not adding any primitives to core that could be implemented in userland and don't have direct tie with other core mechanisms. There are a few exceptions right now like `onMount` and the stuff around `observables` but definitely conscious of keeping that to a minimum. There is a careful balance here even with extending existing primitives, but definitely trying to side on less is more.

In general the combinations are endless of what we can build here so what I'd love to see is making it easier to facilitate sharing of these patterns so others can benefit from the work you've done without increasing our core API surface.
