### ISSUE TITLE
HTML entity not work in fragment <>...</>

### ISSUE THREAD

**Issue by weijarz** [solidjs/solid#691]
**Describe the bug**

HTML entities like `&nbsp;` is not work in <>...</> block.

```ts
    {/^http/.test(props.href) && (
      <>
        &nbsp;
        <img src="https://icons.getbootstrap.com/assets/icons/box-arrow-up-right.svg" />
      </>
    )}
```

**Reproduction**

<https://playground.solidjs.com/?version=1.1.6#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGU0Ac2hqps+YpU6DW09CysrGXoIZlw0WgheABkMAGsACkJ5QjIASn4rXkE4XCYEgB4ofgA6GszabMkAPhA67KrmAAs0NREhCEkCwv59AD0O3FxCfSqXMlwMrLIqjqEZPIAydd40waHeMsbdvd51iBMyQksE48Kyjg9eMhYAXhVxybJEfX00ZniljzFEy0WjkXCMKCEdoKfRQMhkYoGX7-fTAihaKCMeSGLT0QhaRiecZVMgANw8Kl4+kO1z2ZWpRxyA2u9KgNOZESiMTiCQAgoRCGk8iBBkISoxyjShmUOgBGRr8wgaZjOHknURwjrmXgAFTQuDUcHpcqlt2SEBSvBWcBkzwA5O9sl99EFNHpoTA7Y1XOpNLwAFKuenmlKm+ns8IQPpiRhpIW8Z6NfaKqmNLC8ES0Zj0eAQXBVQG4ACihtzuAAQvgAJIiHZgSGEFQ5HJXMCSAC6QA>

**Comment by ryansolid** [comment]
That's an interesting one. Since by default we pass dynamic strings to `textContent` rather than `innerHTML`. This one isn't dynamic per se, but even creating a textNode with `&nbsp;` doesn't work the way you'd want. Just was reading this: https://www.webdeveloper.com/d/193107-resolved-insert-ampnbsp-when-using-createtextnode
Babel parser doesn't give this information, so to accomplish this we'd need to convert any of these to in JSXText to unicode. I don't think that would be too tricky as it's purely compile time, we just need to find a good lookup.

In the meanwhile you can do this:
```js
 {/^http/.test(props.href) && (
      <>
        {" "}
        <img src="https://icons.getbootstrap.com/assets/icons/box-arrow-up-right.svg" />
      </>
    )}
```
But it would be better to make this consistent.
