### ISSUE TITLE
A `TypeError` is thrown when attempting to get the property descriptor of a wrapped array's length

### ISSUE THREAD

**Issue by otonashixav** [solidjs/solid#716]
**Describe the bug**
Trying to do the following results in a TypeError being thrown: 

```ts
import { createStore } from "solid-js/store";

const [store] = createStore({ list: [] });
Object.getOwnPropertyDescriptor(store.list, "length");
```

This is unexpected, but more importantly causes issues when the array is passed to `Object.keys` and other functions which try to do the above. For example, the following in dev mode will throw, as `Index` calls `createSignal` with each of the list's items as the initial value. In dev mode, a name will be assigned to the signal using `hashValue`, which uses `Object.keys` and `Object.getOwnPropertyDescriptors`, which both result in a `TypeError`.

```ts
import { createStore } from "solid-js/store";

const [store] = createStore({ list: [[], []] });
<Index each={store.list}>{() => {}}</Index>
```

I believe this is caused by the `length` property descriptor on arrays not being configurable.

**To Reproduce**
See reproduction.

**Expected behavior**
No error should be thrown. 

**Reproduction**
https://playground.solidjs.com/?hash=2011186416&version=1.2.2

**Additional context**
This bug was initially found here on discord: https://discord.com/channels/722131463138705510/722349143024205824/905493655874322462

**Comment by ryansolid** [comment]
Yeah I see it. This one is a bit annoying since it prevents us from doing some really nice stuff like translating reactivity from descriptors. It's built into the spec but it's really obnoxious. I think length is special which might be why it is affected and nothing else but I don't have many options here except to not wrap the descriptor. I tried a whole bunch of things and none of them worked. I hope length is the only thing like this.
