### ISSUE TITLE
Non-reactive property

### ISSUE THREAD

**Issue by galchenkov** [solidjs/solid#746]
**To Reproduce**
https://codesandbox.io/s/solid-app-router-nested-routes-forked-zkmld?file=/index.tsx

When I click "Link Page A", then "Link Page B", and so on in a circle, then everything works correctly. If you click on "Link Page B", and then on "Button Page A", then navigation does not occur (the button does not have a onClick handler). 

If you add a minor change in the createMemo (append empty string to result):
`createMemo(() => location.pathname + '')`
then everything works as it should.

**Expected behavior**
Click on "Link Page B" then click on "Button Page A" go to page A.

**Additional context**
Button is a component. When onClick handler is undefined, then css cursor style is default, when onClick handler setted - cursor is a pointer.

**Comment by rturnq** [comment]
What's happening here is the `onClick` property of the button is not being re-bound each time the `locationPath` changes.

An exceprt from the [docs](https://www.solidjs.com/docs/latest/api#on___)
> Events are never rebound and the bindings are not reactive, as it is expensive to attach and detach listeners. Since event handlers are called like any other function each time an event fires, there is no need for reactivity; simply shortcut your handler if desired.

I suspect what you are seeing by adding an empty string in the memo is Codesandbox refreshing while you are at `/page-b`. When the app renders at that path, the ternary is true and the `navigateToMain` function is bound. The quick fix here is to just move your logic into a function which will get bound once and execute the logic whenever clicked.

```jsx
<button onClick={() => locationPath() !== '/' && navigateToMain()}>
  Button Page A
</button>
```

**Comment by ryansolid** [comment]
Yes this is intentional. Event handlers are always going to be called imperatively as it is so no need to add extra tracking context and machinery here. If you don't like having the extra conditional on each execution you can do tricks like re-assign the function that is called from the event handler etc.

Under the hood we use event delegation here anyway so the button isn't aware of a click handler so you will need to handle pointer states anyway. But the style implications are a good point. Event delegation is common in many frameworks I wonder if they do anything special here. Hmm.. React doesn't. 

I'm going to consider this one by design.
