### ISSUE TITLE
HMR duplicates the output to the page 

### ISSUE THREAD

**Issue by makoven** [solidjs/solid#768]
**Describe the bug**
Every time after saving, the content of the page is not updated, but added 

**To Reproduce**
1. npx degit solidjs/templates/ts my-app
2. cd my-app && npm i && npm run dev
3. in _src/index.tsx_ comment out `import App from "./App";`
4. Add `function App() { return <div>Echo</div>; }`
5. Open localhost:3000 in the browser
5. Save the _src/index.tsx_ four times 
6. Behold in the browser:
Echo
Echo
Echo
Echo

**Comment by LXSMNSYC** [comment]
This might be because of the `render` call which is re-evaluated in HMR. Try adding `// @refresh reload` at the top of the file.

**Comment by makoven** [comment]
Thank you. This magic trick works. Surprisingly, the original example works fine without this line..

**Comment by LXSMNSYC** [comment]
> Thank you. This magic trick works. Surprisingly, the original example works fine without this line.. 

The reason it works properly was because the changes happens in src/index.tsx and not in src/App.tsx, in which case if it was the latter, HMR on re-evaluates that module and src/index.tsx is untouched.

Take note that the answer I gave you isn't a magic trick and is the official solution to `render`. There's another solution but the reason that solution isn't applied automatically is because the cleanup returned by `render` is meant to be handled by the user.

**Comment by makoven** [comment]
@LXSMNSYC Thanks for the enlightenment
