### ISSUE TITLE
Solid imports SSR bundle when using `generate: "universal"` in node environment

### ISSUE THREAD

**Issue by MrFoxPro** [solidjs/solid#781]
**Describe the bug**
`babel-preset-solid` pruduces server bundle when using universal renderer.

**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:
You can clone my repo and run with nativescript ('ns run android'). You will see that transpiled universal.js at node_modules has imports from 'solid-js' that referring to `dist/server.js`. 
https://github.com/MrFoxPro/solid-nativescript-experiments

**Expected behavior**
It should be configurable somehow or browser version should be selected when using `generate: "universal"`

**Reproduction**
If applicable, add a link to a simple reproduction on a site like https://github.com/MrFoxPro/solid-nativescript-experiments.

**Additional context**
I mentioned it in discord: 
https://discord.com/channels/722131463138705510/730114401427783713/927001847980511334

**Comment by LXSMNSYC** [comment]
`babel-preset-solid` doesn't have to do anything with this as it is the bundler's role to resolve these things.

**Comment by MrFoxPro** [comment]
btw it should be handled properly. any ideas?

**Comment by LXSMNSYC** [comment]
It seems that you're using webpack, you can use Webpack's exportsField and related options: https://github.com/webpack/webpack/pull/10953

**Comment by ryansolid** [comment]
Yeah I'm interested why it defaults to `node` sometimes a bundler's mode/target can affect which export conditions they use by default. It's possible something in the config points it to `node`. But there are ways to set it manually as mentioned above. Sometimes those settings just append conditions instead of replace them. So might be good to figure out where `node` comes in because it generally isn't default. And I imagine most native apps would prefer the client bundle. `browser` trumps `node` in our setup so adding that probably fixes it. But I wonder if there is more to this. Some other setting etc..

**Comment by LXSMNSYC** [comment]
We could probably ship a direct export path, something like `import * as solid from 'solid-js/browser';`

**Comment by ryansolid** [comment]
@MrFoxPro Any updates? Were you able to configure webpack to pull in the right things?

**Comment by MrFoxPro** [comment]
> @MrFoxPro Any updates? Were you able to configure webpack to pull in the right things?

I'm bit later to the party. Not yet, I just manually replaced imports in node_modules/solid

**Comment by ryansolid** [comment]
This issue is been dormant for 3 months. Closing as stale.
