### ISSUE TITLE
Can't Import 'effect' or 'insert' from 'solid-js/web'

### ISSUE THREAD

**Issue by Leoputera2407** [solidjs/solid#800]
I got this error, which boggles my mind since I saw that `effect` and `insert` is part of `solid-js/web`.
![Screen Shot 2022-01-18 at 11 53 34 AM](https://user-images.githubusercontent.com/33604451/150008862-69052fe3-5d74-4b37-a983-d590a7df21bc.png)

I'm currently using `solid-js@1.1.0`

**Comment by ryansolid** [comment]
Is this on the server? During Server rendering? solid-js/web helpers generally are internalized and differ between the web and the server. The reason we use the same import is so that the things that are shared like some of the control flow and some of the helpers that are present in both places.

**Comment by Leoputera2407** [comment]
Hi @ryansolid, this used during server rendering. So, does that mean I should use `solid-js/server` instead?

**Comment by ryansolid** [comment]
What are you trying to do? The compiler generates different output between server and client and I wouldn't expect you to access these helper directly generally. Is it that your app is complaining because it isn't working? Or is it you are trying to import specific helpers for some specific purpose?

**Comment by LXSMNSYC** [comment]
It seems to me that he's trying to use SolidJS in NextJS (implied by the style/design of the error overlay)

**Comment by ryansolid** [comment]
Closing as needs more information to follow up, and has gone stale.
