### ISSUE TITLE
produce() updates store but For renders list wrong

### ISSUE THREAD

**Issue by yonathan06** [solidjs/solid#826]
I'm trying to implement a DND sortable list with sortable.js
When the "drop" event is triggered, I updated the store using `produce()`
logging the new store show good result (the objects are in the sorted order)
but the list is rendered in a different order

maybe I'm missing something?

here is an example in stackblitz feel free to play with it and see the results

https://stackblitz.com/edit/solid-vite-rtvzss?file=src/index.tsx

**Comment by ryansolid** [comment]
More often than not the problem with sortable lists is the difference between where the DOM puts things and where the framework thinks things are. Generally, you need to put the element back where it was and then have the framework move it. This is true of every framework which is why they all have custom wrappers, like react-sortable or vue-sortable. To make matters more fun last I checked sortable doesn't give you an easy option to do this so each framework ends up creating the same boilerplate.

I think this works. I just whipped this up so I might have an error in the logic: https://playground.solidjs.com/?hash=-2144420676&version=1.3.3

Because these interactions can get more complicated I generally recommend people to use existing libraries for this sort of interaction, like https://github.com/thisbeyond/solid-dnd or one of the others.

Hopefully this explanation makes ense.

**Comment by yonathan06** [comment]
It makes a lot of sense, thank you for the detailed explanation and example!

Should check into solid-dnd, looks like what I was looking for
