### ISSUE TITLE
`createUniqueId` doesn't work with `document.querySelector`

### ISSUE THREAD

**Issue by fabien-ml** [solidjs/solid#853]
### Describe the bug

When querying an element that has an id generated by `createUniqueId` via `document.querySelector` the query fail because of the ":" in the id.

### Your Example Website or App

https://playground.solidjs.com/?version=1.3.7#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGU0Ac2hqsDpy4BVawBHejgASRFfWggAWQYIPmk5BWVVDW09CysrGXoIZlw0GN4AYQSXRgAKAEp+K14HGLI+YGYK3zI4XHL83ABdXgBePzhnN09vKoAGGssIRvaIFt4MRzh4ROHeWuGAPl4unoqq9r7dgGpeAEY5nIWm5b5NbfXxoLRQiJFa+YbeGLxc67IYHED-RbNdRwAB0aloHiqIlozHom1wMK+jHwrjgajghW4VQABgBiAAkIE0kmJNRq-0k9Ig-yEuCYCyqEN4AB4TPRcLgSpohlSRNICMQhio+QKYioARBShpmABrEVrIToyR7LmNEBnRK1SRc7n6GWCiA6h53CDG5kQISicRVEEHbm9RLiXj6Pa+ZGo9EwjzdACi+PRACF8JFOWAoIRCCo6fMwJJ+kA

### Steps to Reproduce the Bug or Issue

1. Go to the example link
2. Open the browser console
3. See the error `DOMException: Failed to execute 'querySelector' on 'Document': '#cl:0' is not a valid selector.`

### Expected behavior

It should perform the query

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by atk** [comment]
You could use `document.querySelector(\`[id=${I'd}]\`)`.

**Comment by fabien-ml** [comment]
@atr i think it should works, but it will be a bad DX if the developer have to query an element in a specific way just because of that `:`. @ryansolid a simple `-` is not possible ?

**Comment by rturnq** [comment]
It looks like using a `.` will fail too because this would be a compound selector id+class and class identifiers cannot begin with a number. To have `querySelector` interoperability we should follow [CSS identifier rules](https://www.w3.org/TR/CSS2/syndata.html#value-def-identifier).

> In CSS, *identifiers* (including element names, classes, and IDs in [selectors](https://www.w3.org/TR/CSS2/selector.html)) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit. Identifiers can also contain escaped characters and any ISO 10646 character as a numeric code (see next item). For instance, the identifier "B&W?" may be written as "B\&W\?" or "B\26 W\3F".

It seems like `-` or `_` would be safest.

**Comment by atk** [comment]
It would not work for querySelector for an id as that would assume a class name. `_` or `-` would work in terms of CSS selectors, as would any letter or number, I'm still not sure if the requirement to be able to use the id directly in querySelector is a reasonable one.

**Comment by ryansolid** [comment]
I use a bunch of `.` throughout though so I guess the first `.` would screw it up.  So if we want to fix this we need to change how all ids for hydration look like as well because when server-rendered they share the same counter. So to make this play nice we probably should us `-`. It will look visibly larger but not much other difference.

**Comment by snnsnn** [comment]
https://github.com/ai/nanoid allows to use custom subset  and limits. Maybe you can go something like that. 

```javascript
import { customAlphabet } from 'nanoid'
const nanoid = customAlphabet('1234567890abcdef', 10)
model.id = nanoid(5) //=> "f01a2"
```

**Comment by ryansolid** [comment]
The problem is we use this for client/server stable ids so while it should be considered opaque to the end user there is a very specific system involved. It doesn't makes sense to give the end user this sort of configuration. We just need to use selector safe symbols for the delimiter if we want to support this.

**Comment by LXSMNSYC** [comment]
Wasn't Marko uses the `-` separator for its ids?
