### ISSUE TITLE
Falsy spread condition throws error

### ISSUE THREAD

**Issue by juanrgm** [solidjs/solid#900]
### Describe the bug

If you spread a false value the code throws error.

```ts
import { createSignal } from "solid-js";
import { Dynamic, render } from "solid-js/web";

export function Counter() {
  const [value, setValue] = createSignal(false);
  return (
    <>
      <button onClick={() => setValue(true)}>setValue(true)</button>
      <Dynamic
        component="div"
        data-dummy={value()}
        {...(false && {})}
      >
        text
      </Dynamic>
    </>
  );
}

render(() => <Counter />, document.getElementById("app"));

```

### Your Example Website or App

https://playground.solidjs.com/?hash=305607774&version=1.3.13

### Steps to Reproduce the Bug or Issue

Click the button.

### Expected behavior

No error.

### Platform

- Browser: Chrome

**Comment by atk** [comment]
`false && {}` yields `false`. You cannot spread `false` as it is no object. This in erroneous usage, not an error in solid. What you want is `false || {}`.

**Comment by juanrgm** [comment]
`{...(false && {})}` evaluates to `{}` in JavaScript.

Typical case:

```js
const object = enabled => ({
  ...(enabled && {
    value: 1
  })
})

console.log(object(true)); // { value: 1 }
console.log(object(false)); // {}
```

**Comment by atk** [comment]
I should have clarified that spreading false in this case is not using the javascript mechanism, but instead an internal solid mechanism for JSX spreads and it does not work with false.

**Comment by juanrgm** [comment]
The problem is in `Dynamic` component, maybe in `spread` function.

This example it works: https://playground.solidjs.com/?hash=691527831&version=1.3.13

**Comment by otonashixav** [comment]
There are two issues here, both arising from `in` being used on a non-object type in `mergeProps` and in `spreadExpression`:
https://github.com/solidjs/solid/blob/main/packages/solid/src/render/component.ts#L105
https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/client.js#L325

In the latter case, there is no issue if `skipChildren` is true, since it never reaches the code which throws. However, if it is false e.g. [here](https://playground.solidjs.com/?hash=-381765044&version=1.3.13), you'll see a similar error. 

In both cases the type should be checked before `in` is used.
