### ISSUE TITLE
Using a createStore array with createContext

### ISSUE THREAD

**Issue by 0bon** [solidjs/solid#911]
### Describe the bug

I have been trying to wrap my head around this one for quite some time, but I cannot seem to find the issue.
Let's start with some code:

```
type ColumnType = Store<{
    name: string
    validator: string
}>;

type ColumnContextType = [
    Array<ColumnType>,
    {
        addCol: (name: string, validator: string) => void
    }
];

export const ColumnContext = createContext<ColumnContextType>([
    [],
    {
        addCol: () => undefined,
    },
]);

export const ColumnProvider: Component<{
    name: string;
    validator: string;
}> = (props) => {
    const a: Array<ColumnType> = [{
        name: props.name,
        validator: props.validator,
    }];
    const [state, setState] = createStore(a);

    const addCol = (name: string, validator: string) => {
        // todo
    };

    return (
        <ColumnContext.Provider value={[state, { addCol }]}>
            {props.children}
        </ColumnContext.Provider>
    );
};
```

When setting up the `FieldContext.Provider`, the `state` variable complains with the following error:
```
The type 'readonly { readonly name: string; readonly validator: string; }[]' is 'readonly' and cannot be assigned to the mutable type '{ readonly name: string; readonly validator: string; }[]'.
```

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

It should work, and it does work if I scrap the array, but for some reason using an array just doesn't want to play nice regardless of what I do.

### Platform

Using Solidjs  1.3.10

**Comment by ryansolid** [comment]
Sorry for the delay here. Is this a TS problem only?

Top level arrays in state have limitations since you can't listen to the array itself since the state object itself isn't reactive. So like it is unsuitable for iteration where entries can be added/removed. You are better nesting the array under a property. However, it should still "work" for existing indexes.

What I am seeing from the error is it is complaining about the difference between readonly and mutable types. Stores are treated as readonly types so I imagine that bug might be a red herring. Simply a type mismatch.

**Comment by otonashixav** [comment]
Use `ReadonlyArray` instead of `Array`, or instead type the array as the store instead of the array's contents only:
```ts
type ColumnType = {
    name: string
    validator: string
};

type ColumnContextType = [
    Store<Array<ColumnType>>,
    {
        addCol: (name: string, validator: string) => void
    }
];
```

**Comment by ryansolid** [comment]
Without further information I believe the solution has been provided. Closing.
