### ISSUE TITLE
Feature request: Show a warning when signals are mutated inside an effect

### ISSUE THREAD

**Issue by orenelbaum** [solidjs/solid#914]
Mutating signals within effects seems to be mostly discouraged and can be a foot gun for beginners. I think that it could be helpful to display a warning in the console whenever any signal is being mutated inside of an effect.
If there are use cases where some power users might choose to do this intentionally, maybe we can provide a configuration option to avoid those cases and not display any warnings.

**Comment by ryansolid** [comment]
It's tricky. Technically I tell people to use `createComputed` since most things should be conceptually derivations. However, where you truly wanted to update a signal `createEffect` is the right place to do it. Part of the reason I want to move away from `createComputed` is that things that write signals during the pure stage can do unpredictable things, especially in relationship to SSR and data serialization.

**Comment by orenelbaum** [comment]
Then wouldn't it make more sense to use render effects?

**Comment by ryansolid** [comment]
No, renderEffects are a special class where you want them to happen to move things forward ie to facilitate rendering. Those run on the server. Any signal update that would cause a reactive update we don't want on the server as it isn't reactive.

**Comment by orenelbaum** [comment]
Got it. Then I guess we don't need a warning.
