### ISSUE TITLE
createSelector always updates all items when used with reconcile

### ISSUE THREAD

**Issue by antross** [solidjs/solid#917]
### Describe the bug

Using `createSelector` triggers updates for the selected state of all items when state is set using `reconcile` instead of only triggering updates for the items whose selected state has changed.

### Your Example Website or App

https://playground.solidjs.com/?hash=1733980443&version=1.3.13

### Steps to Reproduce the Bug or Issue

1. Go to the linked playground example
2. Click an item in the Result area ("a" or "b")
3. Observe the logs in the Console area (new logs for `getSelected` appear for both "a" and "b")

### Expected behavior

I expected only the items whose selected state had changed to update. This works as expected if `reconcile` is removed from the call to set state (though that would cause other problems as I'm attempting to work with immutable state in my app per https://www.solidjs.com/tutorial/stores_immutable).

Expected logs (after loading and clicking "b" once):
```
"getSelected" "a"
"getSelected" "b"
"getSelected" "b"
```

Actual logs:
```
"getSelected" "a"
"getSelected" "b"
"getSelected" "a"
"getSelected" "b"
```

### Platform

- OS: [Windows]
- Browser: [Edge]
- Version: [99]

**Comment by mdynnl** [comment]
`reconcile` updates granularly messing up `createSelector` internal comparison.
Same behavior with manual reconcile https://playground.solidjs.com/?hash=777945966&version=1.3.13

Can be fixed by making a new reference https://playground.solidjs.com/?hash=-2087671868&version=1.3.13. Should `createSelector` handle that possiblity or users?

We could wrap it with a memo like https://playground.solidjs.com/?hash=1102333011&version=1.3.13. But I don't think  users should have to think about that and this does not fix extra comparisons.

**Comment by ryansolid** [comment]
Yeah, this is working as expected. Solid's store internals are mutable. `reconcile` basically takes immutable data (structured cloned) and diffs it into a mutable structure for fine-grained updates. Nested fine-grained has to be mutable as each layer holds references. To compare an array you need to clone it otherwise it morphs in place as @mdynnl suggested. I consider that the recommended answer.
